# Generated by Django 5.0.6 on 2026-04-02 20:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legacy', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID legacy (CSV)')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('abreviatura', models.CharField(max_length=50, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción / Nombre')),
                ('clave_hoja', models.CharField(blank=True, max_length=50, verbose_name='Clave hoja de trabajo')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('tipo_muestra', models.CharField(blank=True, max_length=100, verbose_name='Tipo de muestra')),
                ('metodologia', models.TextField(blank=True, verbose_name='Método analítico')),
                ('tipo_resultado', models.CharField(choices=[('NUMERICO', 'Numérico'), ('TEXTO', 'Texto libre'), ('OPCIONES', 'Opciones predefinidas'), ('CALCULO', 'Calculado por fórmula')], default='NUMERICO', max_length=12, verbose_name='Tipo de resultado')),
                ('unidades', models.CharField(blank=True, max_length=100, verbose_name='Unidades')),
                ('decimales', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales en reporte')),
                ('formula_calculo', models.TextField(blank=True, verbose_name='Fórmula de cálculo')),
                ('opciones_texto', models.TextField(blank=True, verbose_name='Opciones predefinidas (una por línea)')),
                ('imprime_en_negritas', models.BooleanField(default=False)),
                ('imprimir_metodo', models.BooleanField(default=False, verbose_name='Imprimir método en resultado')),
                ('es_venta_directa', models.BooleanField(default=True, help_text='True → aparece en PDV y lista de precios (ej: Ácido Úrico). False → solo disponible para armar perfiles (ej: Plaquetas).', verbose_name='¿Venta directa?')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones para el paciente')),
                ('notas', models.TextField(blank=True, verbose_name='Notas técnicas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiz', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analito',
                'verbose_name_plural': 'Analitos',
                'ordering': ['departamento', 'nombre'],
                'indexes': [models.Index(fields=['departamento'], name='lims_analit_departa_d19c09_idx'), models.Index(fields=['es_venta_directa'], name='lims_analit_es_vent_b086f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilLims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del perfil')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiz', models.DateTimeField(auto_now=True)),
                ('analitos', models.ManyToManyField(blank=True, help_text='Buscador inteligente: cualquier analito del catálogo.', related_name='perfiles', to='lims.analito', verbose_name='Analitos incluidos')),
            ],
            options={
                'verbose_name': 'Perfil LIMS',
                'verbose_name_plural': 'Perfiles LIMS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteLims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del paquete')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('venta_publico', models.BooleanField(default=True, verbose_name='¿Disponible para venta al público?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiz', models.DateTimeField(auto_now=True)),
                ('analitos', models.ManyToManyField(blank=True, related_name='paquetes', to='lims.analito', verbose_name='Analitos individuales incluidos')),
                ('perfiles', models.ManyToManyField(blank=True, related_name='paquetes', to='lims.perfillims', verbose_name='Perfiles incluidos')),
            ],
            options={
                'verbose_name': 'Paquete LIMS',
                'verbose_name_plural': 'Paquetes LIMS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Analito'), ('P', 'Perfil'), ('Q', 'Paquete')], max_length=1, verbose_name='Tipo de ítem')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de venta')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualiz', models.DateTimeField(auto_now=True)),
                ('analito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='lims.analito', verbose_name='Analito')),
                ('paquete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='lims.paquetelims', verbose_name='Paquete')),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='lims.perfillims', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='ValorReferenciaAnalito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('I', 'Indistinto'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('unidad_edad', models.CharField(choices=[('DIAS', 'Días (0–364 días de vida)'), ('ANOS', 'Años (≥ 1 año)')], help_text='DIAS: paciente < 1 año. ANOS: paciente ≥ 1 año.', max_length=5, verbose_name='Unidad de edad')),
                ('edad_minima', models.PositiveIntegerField(verbose_name='Edad mínima')),
                ('edad_maxima', models.PositiveIntegerField(verbose_name='Edad máxima')),
                ('ref_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Referencia mínima')),
                ('ref_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Referencia máxima')),
                ('texto_referencia', models.CharField(blank=True, max_length=200, verbose_name='Referencia en texto')),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='lims.analito', verbose_name='Analito')),
            ],
            options={
                'verbose_name': 'Valor de referencia',
                'verbose_name_plural': 'Valores de referencia',
                'ordering': ['analito', 'unidad_edad', 'edad_minima'],
                'indexes': [models.Index(fields=['analito', 'unidad_edad', 'sexo'], name='lims_valorr_analito_c26cad_idx')],
            },
        ),
    ]
