# Generated by Django 5.0.6 on 2026-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillims',
            name='id_perfil_legacy',
            field=models.CharField(blank=True, help_text='Identificador compuesto del CSV Examenes_Perfil para reimportaciones.', max_length=220, null=True, unique=True, verbose_name='ID perfil (legacy CSV)'),
        ),
    ]
