# Generated by Django 5.0.6 on 2026-04-02 21:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_perfillims_id_perfil_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='analito',
            name='costo_lista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio/costo de referencia importado desde Parametros.csv.', max_digits=10, verbose_name='Costo lista (CSV)'),
        ),
        migrations.AddField(
            model_name='paquetelims',
            name='costo_lista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo lista (Paquetes.csv)'),
        ),
        migrations.AddField(
            model_name='paquetelims',
            name='id_paquete_legacy',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Abreviatura paquete (CSV)'),
        ),
        migrations.AddField(
            model_name='perfillims',
            name='costo_lista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo lista (Examenes.csv)'),
        ),
        migrations.AddField(
            model_name='perfillims',
            name='id_examen_legacy',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Id_examen (CSV)'),
        ),
        migrations.AlterField(
            model_name='perfillims',
            name='id_perfil_legacy',
            field=models.CharField(blank=True, help_text='Codigo|Abreviatura del examen (Examenes.csv / Examenes_Perfil).', max_length=220, null=True, unique=True, verbose_name='ID perfil (legacy CSV)'),
        ),
    ]
