# Generated by Django 5.0.6

from django.db import migrations, models


def _marcar_calculados(apps, schema_editor):
    Analito = apps.get_model('lims', 'Analito')
    for a in Analito.objects.exclude(formula='').exclude(formula__isnull=True):
        a.es_calculado = True
        a.save(update_fields=['es_calculado'])


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_lims_v75_costos_y_legacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analito',
            old_name='formula_calculo',
            new_name='formula',
        ),
        migrations.AddField(
            model_name='analito',
            name='es_calculado',
            field=models.BooleanField(
                default=False,
                verbose_name='Calculado?',
                help_text=(
                    'True si el resultado se obtiene por motor interno (no se espera valor del equipo). '
                    'Util para HL7/receptor: disparar calculo en lugar de esperar OBX.'
                ),
            ),
        ),
        migrations.RunPython(_marcar_calculados, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='analito',
            index=models.Index(fields=['es_calculado'], name='lims_analit_es_calc_b71deb_idx'),
        ),
    ]
