# Generated by Django 5.0.6 on 2026-04-03 00:51

from django.db import migrations, models


def rellenar_codigo_rastreo_iso(apps, schema_editor):
    Analito = apps.get_model("lims", "Analito")
    for a in Analito.objects.all():
        if getattr(a, "codigo_rastreo_iso", None):
            continue
        base = (a.codigo or f"A{a.pk}").replace(" ", "_")[:48]
        iso = base
        n = 0
        while (
            Analito.objects.exclude(pk=a.pk)
            .filter(codigo_rastreo_iso=iso)
            .exists()
        ):
            n += 1
            iso = f"{base}-{n}"[:64]
        a.codigo_rastreo_iso = iso[:64]
        a.save(update_fields=["codigo_rastreo_iso"])


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0004_analito_formula_es_calculado"),
    ]

    operations = [
        migrations.AddField(
            model_name="analito",
            name="codigo_rastreo_iso",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identificador estable para trazabilidad (unico).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Codigo rastreo ISO",
            ),
        ),
        migrations.RunPython(rellenar_codigo_rastreo_iso, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="analito",
            name="es_calculado",
            field=models.BooleanField(
                default=False,
                help_text="True si el resultado se obtiene por motor interno (no se espera valor del equipo).",
                verbose_name="Calculado?",
            ),
        ),
        migrations.AlterField(
            model_name="analito",
            name="formula",
            field=models.TextField(
                blank=True,
                help_text="Expresion desde Parametros.csv (Formula). Puede referenciar otros analitos o variables.",
                verbose_name="Formula",
            ),
        ),
    ]
