# Generated by Django 5.0.6 on 2026-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_escudo_clinico_v114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analito',
            name='codigo_rastreo_iso',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador estable para trazabilidad (único). Se rellena al migrar; obligatorio en nuevos registros vía admin/LIMS.', max_length=64, null=True, unique=True, verbose_name='Código rastreo ISO'),
        ),
        migrations.AlterField(
            model_name='analito',
            name='es_calculado',
            field=models.BooleanField(default=False, help_text='True si el resultado se obtiene por motor interno (no se espera valor del equipo). Útil para HL7/receptor: disparar cálculo en lugar de esperar OBX.', verbose_name='¿Calculado?'),
        ),
        migrations.AlterField(
            model_name='analito',
            name='formula',
            field=models.TextField(blank=True, help_text='Expresión desde Parametros.csv (Formula). Puede referenciar otros analitos o variables.', verbose_name='Fórmula'),
        ),
        migrations.AlterField(
            model_name='valorreferenciaanalito',
            name='es_critico_si_fuera_de_rango',
            field=models.BooleanField(default=False, help_text='Si está activo, cualquier valor fuera de ref_mín/ref_máx se considera crítico.', verbose_name='Pánico si fuera de referencia'),
        ),
        migrations.AlterField(
            model_name='valorreferenciaanalito',
            name='mensaje_critico',
            field=models.CharField(blank=True, default='', help_text='Texto para notificaciones; si va vacío se arma un mensaje estándar.', max_length=300, verbose_name='Mensaje crítico (push / notificación)'),
        ),
        migrations.AlterField(
            model_name='valorreferenciaanalito',
            name='valor_critico_alto',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor estrictamente por encima de este límite = pánico (si está definido).', max_digits=14, null=True, verbose_name='Umbral crítico alto'),
        ),
        migrations.AlterField(
            model_name='valorreferenciaanalito',
            name='valor_critico_bajo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor estrictamente por debajo de este límite = pánico (si está definido).', max_digits=14, null=True, verbose_name='Umbral crítico bajo'),
        ),
    ]
