# Generated by Django 5.0.6 on 2026-04-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_pagoorden_empresa_tenant_guard'),
        ('lims', '0009_rename_analito_es_venta_a_vendible'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analito',
            name='lims_analit_es_vent_b086f7_idx',
        ),
        migrations.AlterField(
            model_name='analito',
            name='es_vendible_individualmente',
            field=models.BooleanField(default=False, help_text='True → puede ofertarse solo en recepción y en lista de precios (ej. ácido úrico). False → solo como parte de perfiles/paquetes o procesamiento interno (ej. plaquetas).', verbose_name='¿Vendible individualmente?'),
        ),
        migrations.AddIndex(
            model_name='analito',
            index=models.Index(fields=['es_vendible_individualmente'], name='lims_analit_es_vend_8b9854_idx'),
        ),
    ]
