# Generated by Django 5.0.6 on 2026-07-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_usuario_sucursal_fk'),
        ('lims', '0010_remove_analito_lims_analit_es_vent_b086f7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillims',
            name='analitos',
        ),
        migrations.CreateModel(
            name='PerfilAnalito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en el reporte')),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.analito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.perfillims')),
            ],
            options={
                'verbose_name': 'Analito de Perfil',
                'verbose_name_plural': 'Analitos de Perfiles',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['perfil', 'orden'], name='lims_perfil_perfil__0a97a5_idx')],
                'unique_together': {('perfil', 'analito')},
            },
        ),
    ]
