# Generated by Django 5.1.15 on 2026-07-11 11:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_perfil_analitos(apps, schema_editor):
    PerfilLims = apps.get_model('lims', 'PerfilLims')
    PerfilAnalito = apps.get_model('lims', 'PerfilAnalito')
    connection = schema_editor.connection
    old_table = 'lims_perfillims_analitos'

    if old_table not in connection.introspection.table_names():
        return

    with connection.cursor() as cursor:
        cursor.execute(f'SELECT perfillims_id, analito_id FROM {old_table}')
        rows = cursor.fetchall()

    if not rows:
        return

    perfil_empresa = dict(
        PerfilLims.objects.filter(id__in={perfil_id for perfil_id, _ in rows})
        .values_list('id', 'empresa_id')
    )
    existing = set(
        PerfilAnalito.objects.filter(
            perfil_id__in={perfil_id for perfil_id, _ in rows},
            analito_id__in={analito_id for _, analito_id in rows},
        ).values_list('perfil_id', 'analito_id')
    )

    nuevos = []
    orden_por_perfil = {}
    for perfil_id, analito_id in rows:
        empresa_id = perfil_empresa.get(perfil_id)
        if not empresa_id or (perfil_id, analito_id) in existing:
            continue
        orden = orden_por_perfil.get(perfil_id, 0)
        nuevos.append(
            PerfilAnalito(
                perfil_id=perfil_id,
                analito_id=analito_id,
                empresa_id=empresa_id,
                orden=orden,
            )
        )
        orden_por_perfil[perfil_id] = orden + 1

    PerfilAnalito.objects.bulk_create(nuevos, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_usuario_sucursal_fk'),
        ('lims', '0010_remove_analito_lims_analit_es_vent_b086f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAnalito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en el reporte')),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.analito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.perfillims')),
            ],
            options={
                'verbose_name': 'Analito de Perfil',
                'verbose_name_plural': 'Analitos de Perfiles',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RunPython(backfill_perfil_analitos, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='perfillims',
                    name='analitos',
                    field=models.ManyToManyField(blank=True, help_text='Buscador inteligente: cualquier analito del catálogo.', related_name='perfiles', through='lims.PerfilAnalito', to='lims.analito', verbose_name='Analitos incluidos'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='perfilanalito',
            index=models.Index(fields=['perfil', 'orden'], name='lims_perfil_perfil__0a97a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perfilanalito',
            unique_together={('perfil', 'analito')},
        ),
    ]
