# Generated by Django 5.1.15 on 2026-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_medico_lab_validation_pin_hash'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analito',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='analito',
            name='codigo_rastreo_iso',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador estable para trazabilidad (único). Se rellena al migrar; obligatorio en nuevos registros vía admin/LIMS.', max_length=64, null=True, verbose_name='Código rastreo ISO'),
        ),
        migrations.AlterField(
            model_name='analito',
            name='id_legacy',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID legacy (CSV)'),
        ),
        migrations.AlterField(
            model_name='paquetelims',
            name='id_paquete_legacy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Abreviatura paquete (CSV)'),
        ),
        migrations.AlterField(
            model_name='paquetelims',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del paquete'),
        ),
        migrations.AlterField(
            model_name='perfillims',
            name='id_examen_legacy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id_examen (CSV)'),
        ),
        migrations.AlterField(
            model_name='perfillims',
            name='id_perfil_legacy',
            field=models.CharField(blank=True, help_text='Codigo|Abreviatura del examen (Examenes.csv / Examenes_Perfil).', max_length=220, null=True, verbose_name='ID perfil (legacy CSV)'),
        ),
        migrations.AlterField(
            model_name='perfillims',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del perfil'),
        ),
        migrations.AddConstraint(
            model_name='analito',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_legacy'), name='lims_analito_empresa_id_legacy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analito',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='lims_analito_empresa_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analito',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_rastreo_iso'), name='lims_analito_empresa_rastreo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paquetelims',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_paquete_legacy'), name='lims_paquete_empresa_id_legacy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paquetelims',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='lims_paquete_empresa_nombre_uniq'),
        ),
        migrations.AddConstraint(
            model_name='perfillims',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_perfil_legacy'), name='lims_perfil_empresa_id_legacy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='perfillims',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_examen_legacy'), name='lims_perfil_empresa_id_examen_uniq'),
        ),
        migrations.AddConstraint(
            model_name='perfillims',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='lims_perfil_empresa_nombre_uniq'),
        ),
    ]
