# Generated by Django 5.0.6 on 2026-07-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_remove_perfillims_analitos_perfilanalito'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillims',
            name='analitos',
            field=models.ManyToManyField(blank=True, help_text='Buscador inteligente: cualquier analito del catálogo.', related_name='perfiles', through='lims.PerfilAnalito', to='lims.analito', verbose_name='Analitos incluidos'),
        ),
    ]
