# Generated by Django 5.1.15 on 2026-08-12 17:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_empresa(apps, schema_editor):
    Rango = apps.get_model('lims', 'ValorReferenciaAnalito')
    for rango in Rango.objects.filter(
        empresa__isnull=True,
        analito__empresa__isnull=False,
    ).select_related('analito').iterator():
        rango.empresa_id = rango.analito.empresa_id
        rango.save(update_fields=['empresa'])
    if Rango.objects.filter(empresa__isnull=True).exists():
        raise RuntimeError('LIMS: ValorReferenciaAnalito sin empresa determinable.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_scope_solicitud_autorizacion_by_empresa'),
        ('lims', '0012_alter_analito_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='valorreferenciaanalito',
            name='lims_valorr_analito_c26cad_idx',
        ),
        migrations.AddField(
            model_name='valorreferenciaanalito',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia_lims', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.RunPython(backfill_empresa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='valorreferenciaanalito',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia_lims', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='valorreferenciaanalito',
            index=models.Index(fields=['empresa', 'analito', 'unidad_edad', 'sexo'], name='lims_valorr_empresa_219e08_idx'),
        ),
    ]
