# Generated by Django 5.0.6 on 2026-03-31 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo', models.CharField(choices=[('LAB', 'Laboratorio (Reactivos / Calibradores)'), ('CONSULTORIO', 'Consultorio (Material de Curación)'), ('GENERAL', 'Insumos Generales (Papelería / Limpieza)')], max_length=15, verbose_name='Silo')),
                ('folio', models.CharField(max_length=30, verbose_name='Folio')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO', 'Recibido y Confirmado'), ('RECHAZADO', 'Rechazado por Receptor'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('motivo', models.TextField(verbose_name='Motivo del Traspaso')),
                ('razon_rechazo', models.TextField(blank=True, null=True, verbose_name='Razón de Rechazo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Despacho')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Recepción')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_despachados', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por')),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_recibidos', to='core.empresa', verbose_name='Empresa Destino')),
                ('empresa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_enviados', to='core.empresa', verbose_name='Empresa Origen')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_recibidos_personal', to=settings.AUTH_USER_MODEL, verbose_name='Receptor (firma PIN)')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Traspaso de Inventario',
                'verbose_name_plural': 'Traspasos de Inventario',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionDiscrepancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OC_DISCREPANCIA', 'Discrepancia en Recepción de OC'), ('TRASPASO_DISCREPANCIA', 'Discrepancia en Traspaso Recibido'), ('STOCK_CRITICO', 'Stock Crítico Detectado'), ('LOTE_CADUCADO', 'Lote Caducado en Almacén')], max_length=30, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='ADVERTENCIA', max_length=15, verbose_name='Nivel')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('detalle', models.TextField(verbose_name='Detalle de la Discrepancia')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('generada_en', models.DateTimeField(auto_now_add=True, verbose_name='Generada')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('notas_resolucion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_discrepancia', to='core.empresa', verbose_name='Empresa')),
                ('oc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='inventario.ordendecompra', verbose_name='OC Relacionada')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('traspaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='inventario.traspasoinventario', verbose_name='Traspaso Relacionado')),
            ],
            options={
                'verbose_name': 'Notificación de Discrepancia',
                'verbose_name_plural': 'Notificaciones de Discrepancia',
                'ordering': ['-generada_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaTraspasoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo', models.CharField(choices=[('LAB', 'Silo Laboratorio'), ('CONSULTORIO', 'Silo Consultorio'), ('GENERAL', 'Silo Generales')], max_length=15)),
                ('lote_object_id', models.PositiveIntegerField(verbose_name='ID del Lote')),
                ('nombre_articulo_snapshot', models.CharField(max_length=300, verbose_name='Artículo (snapshot al generar traspaso)')),
                ('numero_lote_snapshot', models.CharField(blank=True, max_length=120, null=True, verbose_name='Número de Lote (snapshot)')),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad Enviada')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cantidad Recibida')),
                ('empresa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_traspaso_origen', to='core.empresa', verbose_name='Empresa Origen')),
                ('lote_content_type', models.ForeignKey(limit_choices_to={'app_label': 'inventario', 'model__in': ['lotereactivolab', 'loteinsumoconsultorio', 'loteinsumogeneral']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Tipo de Lote')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.traspasoinventario', verbose_name='Traspaso')),
            ],
            options={
                'verbose_name': 'Línea de Traspaso',
                'verbose_name_plural': 'Líneas de Traspaso',
            },
        ),
        migrations.AddIndex(
            model_name='traspasoinventario',
            index=models.Index(fields=['empresa_origen', 'estado'], name='inventario__empresa_ff27a0_idx'),
        ),
        migrations.AddIndex(
            model_name='traspasoinventario',
            index=models.Index(fields=['empresa_destino', 'estado'], name='inventario__empresa_78aaa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='traspasoinventario',
            constraint=models.UniqueConstraint(fields=('empresa_origen', 'folio'), name='inventario_traspaso_empresa_folio_uniq'),
        ),
        migrations.AddIndex(
            model_name='notificaciondiscrepancia',
            index=models.Index(fields=['empresa', 'resuelta', '-generada_en'], name='inventario__empresa_4e3bf1_idx'),
        ),
    ]
