# Generated by Django 5.0.6 on 2026-04-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_notificaciondiscrepancia_tipo_hl7'),
        ('lims', '0007_forense_acceso_cofepris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaanaliticalab',
            name='parametro',
        ),
        migrations.AddField(
            model_name='salidaanaliticalab',
            name='analito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_analiticas', to='lims.analito', verbose_name='Analito LIMS'),
        ),
        migrations.AlterField(
            model_name='notificaciondiscrepancia',
            name='tipo',
            field=models.CharField(choices=[('OC_DISCREPANCIA', 'Discrepancia en Recepción de OC'), ('TRASPASO_DISCREPANCIA', 'Discrepancia en Traspaso Recibido'), ('STOCK_CRITICO', 'Stock Crítico Detectado'), ('LOTE_CADUCADO', 'Lote Caducado en Almacén'), ('HL7_MAPEO', 'HL7 — error de mapeo a LIMS'), ('HL7_CUARENTENA', 'HL7 — cuarentena (unidad/valor)')], max_length=30, verbose_name='Tipo'),
        ),
    ]
