# Generated by Django 5.0.6 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_forense_acceso_cofepris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciondiscrepancia',
            name='tipo',
            field=models.CharField(choices=[('OC_DISCREPANCIA', 'Discrepancia en Recepción de OC'), ('TRASPASO_DISCREPANCIA', 'Discrepancia en Traspaso Recibido'), ('STOCK_CRITICO', 'Stock Crítico Detectado'), ('LOTE_CADUCADO', 'Lote Caducado en Almacén'), ('HL7_MAPEO', 'HL7 — error de mapeo a LIMS'), ('HL7_CUARENTENA', 'HL7 — cuarentena (unidad/valor)'), ('QC_WESTGARD', 'CCI — rechazo reglas Westgard (ISO 15189)')], max_length=30, verbose_name='Tipo'),
        ),
    ]
