# Generated by Django 5.0.6 on 2026-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_notificacion_qc_westgard_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='factura_adjunta',
            field=models.FileField(blank=True, null=True, upload_to='compras/facturas/%Y/%m/', verbose_name='Factura del proveedor'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_EMPRESARIAL', 'Tarjeta Empresarial'), ('CREDITO', 'Crédito con proveedor')], max_length=25, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='compras/evidencia/%Y/%m/', verbose_name='Foto de evidencia (recepción de mercancía)'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='pagada',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='referencia_transferencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
