# Generated by Django 5.0.6 on 2026-06-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0009_reporteultrasonido_imagenultrasonido_and_more'),
        ('core', '0081_make_mensajeinterno_empresa_required'),
        ('inventario', '0008_agregar_evidencia_pagos_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaanaliticalab',
            name='formula_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_generadas', to='inventario.consumoestudioreactivo', verbose_name='Fórmula de Consumo Usada'),
        ),
        migrations.AlterField(
            model_name='salidaanaliticalab',
            name='idempotency_key',
            field=models.CharField(help_text='Determinista: lab_rp{resultado_id}_f{formula_id}_l{lote_id}.', max_length=190, unique=True, verbose_name='Clave de idempotencia'),
        ),
        migrations.AlterField(
            model_name='salidaconsumoconsultorio',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_insumos', to='consultorio.agendacita', verbose_name='Cita Médica'),
        ),
        migrations.AlterField(
            model_name='salidatecnicalab',
            name='ticket_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_tecnicas_reactivos', to='core.mantenimientoequipo', verbose_name='Ticket de Mantenimiento'),
        ),
    ]
