# Generated by Django 5.1.15 on 2026-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_salidaanaliticalab_formula_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotereactivolab',
            name='campos_pendientes',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos pendientes de trazabilidad'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='factura_documento',
            field=models.FileField(blank=True, null=True, upload_to='inventario/facturas/reactivos/%Y/%m/', verbose_name='Factura del lote'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='factura_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='factura_numero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Factura / Folio'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Puede quedar pendiente durante la migración.', null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='inserto_documento',
            field=models.FileField(blank=True, null=True, upload_to='inventario/insertos/reactivos/%Y/%m/', verbose_name='Inserto del fabricante'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='inserto_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de cargar'), ('NO_APLICA', 'No aplica'), ('NO_DISPONIBLE', 'No disponible durante la migración'), ('ADJUNTO', 'Adjunto'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=20, verbose_name='Estado del inserto'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='inserto_version',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Versión del inserto'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca comercial del producto; puede diferir del fabricante legal.', max_length=200, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='trazabilidad_estado',
            field=models.CharField(choices=[('ADAPTACION', 'Adaptación — faltan datos documentales'), ('COMPLETA', 'Completa')], default='ADAPTACION', max_length=15, verbose_name='Estado de trazabilidad'),
        ),
        migrations.AddField(
            model_name='lotereactivolab',
            name='trazabilidad_observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones de adaptación'),
        ),
    ]
