# Generated by Django 5.1.15 on 2026-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_lotereactivolab_campos_pendientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotereactivolab',
            name='factura_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de localizar'), ('NO_APLICA', 'No aplica'), ('NO_DISPONIBLE', 'No disponible durante la migración'), ('REGISTRADA', 'Registrada')], default='PENDIENTE', max_length=20, verbose_name='Estado de factura'),
        ),
    ]
