# Generated by Django 5.1.15 on 2026-07-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_lotereactivolab_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoreactivolab',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Marca'),
        ),
    ]
