# Generated by Django 5.1.15 on 2026-07-24 05:38

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_empresa_inventario_modo_adaptacion'),
        ('inventario', '0012_catalogoreactivolab_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaCompraLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inventario/compras_ocr/%Y/%m/%d/', validators=[core.validators.validate_image_upload])),
                ('texto_extraido', models.TextField(blank=True, default='')),
                ('datos_extraidos', models.JSONField(blank=True, default=dict)),
                ('sugerencias', models.JSONField(blank=True, default=list)),
                ('items_confirmados', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(db_index=True, default='PROCESADA', max_length=20)),
                ('confianza', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('error', models.TextField(blank=True, default='')),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_compra_laboratorio_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_compra_laboratorio', to='core.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura OCR de compra de laboratorio',
                'verbose_name_plural': 'Lecturas OCR de compras de laboratorio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
