# Generated by Django 5.1.15 on 2026-07-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_resultadoparametro_equipo'),
        ('inventario', '0013_lecturacompralaboratorio'),
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeticionAnaliticaLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pruebas', models.PositiveIntegerField(default=1, help_text='Normalmente 1; permite registrar más de una repetición explícita.', verbose_name='Pruebas adicionales')),
                ('motivo', models.TextField(verbose_name='Motivo de repetición')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha / Hora')),
            ],
            options={
                'verbose_name': 'Repetición Analítica',
                'verbose_name_plural': 'Repeticiones Analíticas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='consumoestudioreactivo',
            name='inventario_consumo_estudio_reactivo_uniq',
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Vacío = fórmula genérica; si existe una fórmula específica para el equipo, esa tiene prioridad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulas_consumo_reactivo', to='laboratorio.equipo', verbose_name='Equipo / Analizador'),
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='es_alternativa',
            field=models.BooleanField(default=False, help_text='Las alternativas compiten dentro de su grupo; solo la seleccionada descuenta.', verbose_name='Es alternativa'),
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='grupo_consumo',
            field=models.CharField(default='PRINCIPAL', help_text='Ej.: REACTIVO_PRINCIPAL, PUNTAS, DILUYENTE, CALIBRADOR.', max_length=80, verbose_name='Grupo de Consumo'),
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='prioridad',
            field=models.PositiveIntegerField(default=100, help_text='Menor número = mayor prioridad cuando se requiere desempate.', verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='seleccionada',
            field=models.BooleanField(default=True, help_text='Solo aplica a alternativas. El cambio conserva el historial de salidas anteriores.', verbose_name='Seleccionada para uso'),
        ),
        migrations.AddConstraint(
            model_name='consumoestudioreactivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'analito', 'reactivo', 'equipo', 'grupo_consumo'), name='inventario_consumo_estudio_reactivo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='consumoestudioreactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_alternativa', True), ('seleccionada', True)), fields=('empresa', 'analito', 'equipo', 'grupo_consumo'), name='inventario_consumo_alternativa_activa_uniq'),
        ),
        migrations.AddField(
            model_name='repeticionanaliticalab',
            name='registrada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeticiones_analiticas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
        migrations.AddField(
            model_name='repeticionanaliticalab',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeticiones_analiticas', to='core.resultadoparametro', verbose_name='Resultado repetido'),
        ),
        migrations.AddIndex(
            model_name='repeticionanaliticalab',
            index=models.Index(fields=['resultado', 'fecha'], name='inventario__resulta_6fb535_idx'),
        ),
    ]
