# Generated by Django 5.1.15 on 2026-07-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_resultadoparametro_equipo'),
        ('inventario', '0014_repeticionanaliticalab_and_more'),
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosteoEjecucionAnaliticaLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Determinación inicial'), ('REPETICION', 'Repetición')], max_length=12)),
                ('cantidad_ejecuciones', models.PositiveIntegerField(default=1)),
                ('costo_materiales', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ingreso_asignado', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('detalle_costos', models.JSONField(blank=True, default=list)),
                ('evento_key', models.CharField(max_length=190, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='consumoestudioreactivo',
            name='inventario_consumo_estudio_reactivo_uniq',
        ),
        migrations.AddField(
            model_name='consumoestudioreactivo',
            name='aplicacion',
            field=models.CharField(choices=[('ANALITO', 'Por analito / determinación'), ('MUESTRA', 'Una vez por muestra / orden')], default='ANALITO', help_text='MUESTRA evita descontar tubo/aguja/etc. una vez por cada analito del perfil.', max_length=10, verbose_name='Nivel de aplicación'),
        ),
        migrations.AlterField(
            model_name='consumoestudioreactivo',
            name='analito',
            field=models.ForeignKey(blank=True, help_text='Vacío únicamente para un consumible común de muestra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_reactivos', to='lims.analito', verbose_name='Analito LIMS'),
        ),
        migrations.AddConstraint(
            model_name='consumoestudioreactivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'analito', 'reactivo', 'equipo', 'grupo_consumo', 'aplicacion'), name='inventario_consumo_estudio_reactivo_uniq'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='analito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costeos_lab', to='lims.analito'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costeos_analiticos_lab', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costeos_analiticos_lab', to='core.ordendeservicio'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costeos_analiticos_lab', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='repeticion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costeos_lab', to='inventario.repeticionanaliticalab'),
        ),
        migrations.AddField(
            model_name='costeoejecucionanaliticalab',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costeos_lab', to='core.resultadoparametro'),
        ),
        migrations.AddIndex(
            model_name='costeoejecucionanaliticalab',
            index=models.Index(fields=['empresa', '-fecha'], name='inventario__empresa_8b952d_idx'),
        ),
        migrations.AddIndex(
            model_name='costeoejecucionanaliticalab',
            index=models.Index(fields=['orden', 'tipo'], name='inventario__orden_i_07ed47_idx'),
        ),
        migrations.AddIndex(
            model_name='costeoejecucionanaliticalab',
            index=models.Index(fields=['paciente', '-fecha'], name='inventario__pacient_691244_idx'),
        ),
    ]
