# Generated by Django 5.1.15 on 2026-07-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_resultadoparametro_equipo'),
        ('inventario', '0015_costeoejecucionanaliticalab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costeoejecucionanaliticalab',
            name='repeticion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costeos_lab', to='inventario.repeticionanaliticalab'),
        ),
        migrations.AlterField(
            model_name='costeoejecucionanaliticalab',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costeos_lab', to='core.resultadoparametro'),
        ),
    ]
