# Generated by Django 5.1.15 on 2026-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_resultadoparametro_equipo'),
        ('inventario', '0016_alter_costeoejecucionanaliticalab_repeticion_and_more'),
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumoestudioreactivo',
            name='inventario_consumo_estudio_reactivo_uniq',
        ),
        migrations.AddConstraint(
            model_name='consumoestudioreactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('analito__isnull', False)), fields=('empresa', 'analito', 'reactivo', 'equipo', 'grupo_consumo', 'aplicacion'), name='inventario_consumo_estudio_reactivo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='consumoestudioreactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('aplicacion', 'MUESTRA')), fields=('empresa', 'reactivo', 'equipo', 'grupo_consumo', 'aplicacion'), name='inventario_consumo_muestra_reactivo_uniq'),
        ),
    ]
