# Generated by Django 4.2 on 2026-01-26 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.TextField(help_text='Valor original antes del cambio (puede ser numérico o texto)', verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(help_text='Valor después del cambio', verbose_name='Valor Nuevo')),
                ('motivo_cambio', models.TextField(help_text='Explicación obligatoria del porqué se realizó la modificación', verbose_name='Motivo del Cambio')),
                ('fecha_hora_cambio', models.DateTimeField(auto_now_add=True, help_text='Timestamp inmutable del momento exacto del cambio', verbose_name='Fecha y Hora del Cambio')),
                ('resultado_validado_previamente', models.BooleanField(default=False, help_text='True si el resultado ya había sido validado antes del cambio (más crítico)', verbose_name='Resultado Ya Validado')),
                ('resultado_entregado_previamente', models.BooleanField(default=False, help_text='True si el resultado ya fue entregado al paciente (altamente crítico)', verbose_name='Resultado Ya Entregado')),
                ('hash_integridad', models.CharField(blank=True, help_text='SHA-256 del cambio para verificación forense', max_length=64, null=True, verbose_name='Hash de Integridad')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó el cambio', null=True, verbose_name='IP de Origen')),
                ('observaciones_supervisor', models.TextField(blank=True, help_text='Notas adicionales del supervisor que autorizó (si aplica)', null=True, verbose_name='Observaciones del Supervisor')),
                ('resultado_asociado', models.ForeignKey(help_text='El resultado que fue modificado', on_delete=django.db.models.deletion.PROTECT, related_name='historial_cambios_lab', to='core.resultadoparametro', verbose_name='Resultado Asociado')),
                ('usuario_responsable', models.ForeignKey(help_text='Químico o supervisor que autorizó el cambio', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_resultados_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Historial de Resultado',
                'verbose_name_plural': 'Historial de Resultados',
                'ordering': ['-fecha_hora_cambio'],
                'permissions': [('ver_historial_resultados', 'Puede ver el historial completo de cambios de resultados'), ('modificar_resultados_validados', 'Puede modificar resultados ya validados')],
            },
        ),
        migrations.AddIndex(
            model_name='historialresultados',
            index=models.Index(fields=['resultado_asociado', '-fecha_hora_cambio'], name='laboratorio_resulta_58ea33_idx'),
        ),
        migrations.AddIndex(
            model_name='historialresultados',
            index=models.Index(fields=['usuario_responsable', '-fecha_hora_cambio'], name='laboratorio_usuario_2a1bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialresultados',
            index=models.Index(fields=['-fecha_hora_cambio'], name='laboratorio_fecha_h_67c7da_idx'),
        ),
    ]
