# Generated by Django 5.0.14 on 2026-02-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_historialresultados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='keywords',
            field=models.TextField(blank=True, db_index=True, help_text="Sinónimos y términos alternativos para búsqueda rápida (ej: 'glucosa,azucar,glicemia,blood sugar'). Separados por comas.", null=True, verbose_name='Palabras Clave de Búsqueda'),
        ),
    ]
