# Generated by Django 5.0.14 on 2026-02-11 - R107 Cerebro de Inventario

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_estudio_keywords'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, help_text='Unidades consumidas por cada vez que se realiza este estudio.', max_digits=8, verbose_name='Cantidad por estudio')),
                ('es_critico', models.BooleanField(default=False, help_text='Si es True, el sistema alerta cuando este insumo está por agotarse.', verbose_name='Insumo Crítico')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_requeridos', to='laboratorio.estudio', verbose_name='Estudio')),
                ('producto', models.ForeignKey(help_text='Producto del inventario que se consume al realizar este estudio.', on_delete=django.db.models.deletion.PROTECT, related_name='uso_en_estudios', to='core.producto', verbose_name='Insumo / Reactivo')),
            ],
            options={
                'verbose_name': 'Insumo de Estudio',
                'verbose_name_plural': 'Insumos de Estudios',
                'ordering': ['estudio__nombre', 'producto__nombre'],
                'unique_together': {('estudio', 'producto')},
            },
        ),
    ]
