# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_insumoestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesanitario',
            name='firma_digital',
            field=models.ImageField(blank=True, help_text='Imagen de la firma para incluir en reportes PDF', null=True, upload_to='firmas_sanitarias/%Y/', validators=[core.validators.validate_image_upload], verbose_name='Firma Digital'),
        ),
    ]
