# Generated by Django 5.0.14 on 2026-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_responsablesanitario_firma_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='keywords',
            field=models.CharField(blank=True, db_index=True, help_text="Sinónimos y términos alternativos para búsqueda rápida (ej: 'glucosa,azucar,glicemia,blood sugar'). Separados por comas.", max_length=500, null=True, verbose_name='Palabras Clave de Búsqueda'),
        ),
    ]
