# Generated by Django 5.0.6 on 2026-03-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_orden_empresa_fk'),
        ('laboratorio', '0006_alter_estudio_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa/tenant dueño de esta orden (multi-tenant SaaS).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_laboratorio', to='core.empresa'),
        ),
    ]
