# Generated by Django 5.0.6 on 2026-03-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_orden_empresa_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='alerta_critica_enviada',
            field=models.BooleanField(default=False, help_text='True cuando ya se notificó al QC/médico sobre este valor crítico.'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='es_critico',
            field=models.BooleanField(db_index=True, default=False, help_text='True cuando el valor supera umbrales de pánico (ISO 15189).'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='parametro_ref',
            field=models.ForeignKey(blank=True, help_text='Parámetro de referencia (para laboratorio detallado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_parametro', to='laboratorio.parametro'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notas_ia',
            field=models.TextField(blank=True, help_text='Observación específica de la AI para este parámetro.', null=True),
        ),
        migrations.CreateModel(
            name='RangoReferenciaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Ambos')], default='A', max_length=1)),
                ('edad_min_anios', models.DecimalField(decimal_places=2, default=0, help_text='Edad mínima (años). 0 = recién nacido.', max_digits=5)),
                ('edad_max_anios', models.DecimalField(decimal_places=2, default=999, help_text='Edad máxima (años). 999 = sin límite.', max_digits=5)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, help_text='Límite inferior del rango normal.', max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, help_text='Límite superior del rango normal.', max_digits=10, null=True)),
                ('valor_critico_bajo', models.DecimalField(blank=True, decimal_places=4, help_text='Valor crítico inferior. Activa alerta de pánico a PRIS y QC.', max_digits=10, null=True)),
                ('valor_critico_alto', models.DecimalField(blank=True, decimal_places=4, help_text='Valor crítico superior. Activa alerta de pánico a PRIS y QC.', max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, default='', max_length=30)),
                ('fuente', models.CharField(choices=[('CLSI', 'CLSI EP28-A3c'), ('HARRISON', "Harrison's Principles"), ('OPS', 'OPS/OMS Valores de Referencia'), ('PRISLAB', 'Verificado por PRISLAB'), ('OTRO', 'Otra fuente bibliográfica')], default='PRISLAB', max_length=20)),
                ('referencia_bibliografica', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_verificacion', models.DateField(blank=True, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos_referencia_dinamicos', to='laboratorio.parametro', verbose_name='Parámetro')),
            ],
            options={
                'verbose_name': 'Rango de Referencia Dinámico',
                'verbose_name_plural': 'Rangos de Referencia Dinámicos',
                'ordering': ['parametro', 'sexo', 'edad_min_anios'],
                'unique_together': {('parametro', 'sexo', 'edad_min_anios', 'edad_max_anios')},
            },
        ),
        migrations.AddField(
            model_name='resultado',
            name='rango_usado',
            field=models.ForeignKey(blank=True, help_text='Rango dinámico ISO 15189 que se usó para la validación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to='laboratorio.rangoreferenciaparametro'),
        ),
        migrations.CreateModel(
            name='ResultadoHL7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_crudo', models.TextField(help_text='Mensaje HL7/ASTM raw recibido del analizador')),
                ('codigo_parametro_equipo', models.CharField(help_text='Código enviado por el equipo (ej: GLU, HGB)', max_length=50)),
                ('valor_raw', models.CharField(max_length=100)),
                ('unidad_raw', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido — Pendiente mapeo'), ('MAPEADO', 'Mapeado — Pendiente QC'), ('QC_OK', 'QC Aprobado — Listo para validar'), ('QC_FALLO', 'QC Fallido — Requiere revisión'), ('INTEGRADO', 'Integrado a Resultado'), ('RECHAZADO', 'Rechazado manualmente')], db_index=True, default='RECIBIDO', max_length=15)),
                ('ip_equipo', models.GenericIPAddressField(blank=True, null=True)),
                ('protocolo', models.CharField(choices=[('HL7', 'HL7 v2.x'), ('ASTM', 'ASTM E1394')], default='HL7', max_length=10)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_integracion', models.DateTimeField(blank=True, null=True)),
                ('notas_qc', models.TextField(blank=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_hl7', to='laboratorio.orden')),
                ('parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_hl7', to='laboratorio.parametro')),
            ],
            options={
                'verbose_name': 'Resultado HL7/ASTM',
                'verbose_name_plural': 'Resultados HL7/ASTM',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.AddField(
            model_name='resultado',
            name='origen_hl7',
            field=models.ForeignKey(blank=True, help_text='Resultado HL7/ASTM origen si fue integrado desde equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_integrados', to='laboratorio.resultadohl7'),
        ),
        migrations.AddIndex(
            model_name='resultadohl7',
            index=models.Index(fields=['estado', 'fecha_recepcion'], name='hl7_estado_fecha_idx'),
        ),
    ]
