# Generated by Django 5.0.6 on 2026-03-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_resultado_alerta_critica_enviada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoParametroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(help_text='Código interno del equipo (ej: WBC, HGB, GLU).', max_length=50)),
                ('factor_conversion', models.DecimalField(decimal_places=6, default=1.0, help_text='Factor de conversión de unidades (ej: 1.0 si las unidades coinciden).', max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_codigos', to='laboratorio.equipo', verbose_name='Equipo')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_equipo', to='laboratorio.parametro', verbose_name='Parámetro PRISLAB')),
            ],
            options={
                'verbose_name': 'Mapeo Código Equipo',
                'verbose_name_plural': 'Mapeos Códigos Equipos',
                'ordering': ['equipo__nombre', 'codigo_equipo'],
                'unique_together': {('equipo', 'codigo_equipo')},
            },
        ),
    ]
