# Generated by Django 5.0.6 on 2026-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_add_codigo_parametro_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ['estudio__nombre', 'orden_impresion', 'nombre'], 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.AddField(
            model_name='estudio',
            name='abreviatura',
            field=models.CharField(blank=True, db_index=True, help_text='Abreviatura del estudio usada en etiquetas ZPL y HL7 (ej: CH, BH, GLU).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False, el estudio existe pero no aparece en catálogo de venta.'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='metodo',
            field=models.CharField(blank=True, help_text='Método analítico (ej: Citometría de flujo, Colorimétrico Automatizado).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas visibles solo para el personal (no se imprimen al paciente).', null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='permite_venta_directa',
            field=models.BooleanField(default=True, help_text='Si True, puede venderse como prueba individual desde recepción/PDV.'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='sexo_aplicable',
            field=models.CharField(choices=[('Ambos', 'Ambos'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Ambos', help_text='Sexo al que aplica este estudio.', max_length=20),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tiempo_proceso',
            field=models.CharField(blank=True, help_text='Tiempo de procesamiento (ej: "2 horas", "24 horas").', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='titulo_alineacion',
            field=models.CharField(blank=True, help_text='Alineación del título en el reporte (Izquierda, Centro, Derecha).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='titulo_color',
            field=models.CharField(blank=True, help_text='Color HEX del título en el reporte PDF (ej: #cc1212).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='titulo_reporte',
            field=models.CharField(blank=True, help_text='Título a mostrar en el reporte PDF (puede diferir del nombre clínico).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='abreviatura',
            field=models.CharField(blank=True, db_index=True, help_text='Código corto del parámetro (ej: leuct, RBC, HGB). Clave en HL7/ASTM.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='decimales',
            field=models.SmallIntegerField(default=2, help_text='Número de decimales al reportar/validar el resultado.'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='departamento',
            field=models.CharField(blank=True, db_index=True, help_text='Sección de laboratorio (Hematología, Bioquímica Clínica, etc.).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='es_antibiograma',
            field=models.BooleanField(default=False, help_text='Si True, el resultado es un antibiograma (sensibilidad a antibióticos).'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='etiqueta_interfaz',
            field=models.CharField(blank=True, help_text='Nombre de la etiqueta en el analizador (puede diferir del código interfaz).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='formula',
            field=models.CharField(blank=True, help_text='Fórmula de cálculo si el parámetro es derivado (ej: VCM = HCT/RBC*10).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='imprimir_en_negritas',
            field=models.BooleanField(default=False, help_text='Si True, el resultado se imprime en negritas en el reporte PDF.'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='imprimir_metodo',
            field=models.BooleanField(default=False, help_text='Si True, el método analítico se imprime en el reporte PDF.'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='indicaciones',
            field=models.TextField(blank=True, help_text='Instrucciones de preparación del paciente para este parámetro.', null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales del parámetro para el reporte.', null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='orden_impresion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en el reporte PDF. Menor número = primero.'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='resultado_opciones',
            field=models.CharField(blank=True, help_text='Opciones de resultado separadas por | (para tipo Opciones).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tipo_muestra',
            field=models.CharField(blank=True, help_text='Tipo de muestra requerida (ej: SANGRE TOTAL-TUBO LILA).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tipo_referencia',
            field=models.CharField(choices=[('Rango numerico', 'Rango numérico'), ('Texto libre', 'Texto libre'), ('Sin referencia', 'Sin referencia')], default='Rango numerico', help_text='Tipo de rango de referencia para este parámetro.', max_length=30),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tipo_resultado',
            field=models.CharField(choices=[('Numerico', 'Numérico'), ('Texto', 'Texto'), ('Opciones', 'Opciones predefinidas')], default='Numerico', help_text='Forma de captura del resultado.', max_length=20),
        ),
        migrations.AddField(
            model_name='parametro',
            name='valor_normalidad_texto',
            field=models.TextField(blank=True, help_text='Rango de referencia en texto libre para parámetros cualitativos.', null=True),
        ),
    ]
