# Generated by Django 5.0.6 on 2026-03-30 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_usuario_mfa_activo_usuario_totp_secret_and_more'),
        ('laboratorio', '0010_add_catalogo_clinico_fields'),
        ('pacientes', '0002_solicitudaccesoportal_usuariopaciente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estudio',
            index=models.Index(fields=['codigo'], name='lab_estudio_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='estudio',
            index=models.Index(fields=['activo', 'categoria'], name='lab_estudio_activo_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='estudio',
            index=models.Index(fields=['nombre'], name='lab_estudio_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['empresa', 'estado_analisis'], name='lab_orden_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['empresa', '-fecha_creacion'], name='lab_orden_empresa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado_analisis'], name='lab_orden_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='parametro',
            index=models.Index(fields=['codigo_interfaz'], name='lab_param_codigo_interfaz_idx'),
        ),
        migrations.AddIndex(
            model_name='parametro',
            index=models.Index(fields=['estudio', 'orden_impresion'], name='lab_param_estudio_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='rangoreferenciaparametro',
            index=models.Index(fields=['parametro', 'activo'], name='lab_rango_param_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='rangoreferenciaparametro',
            index=models.Index(fields=['parametro', 'activo', 'edad_min_anios', 'edad_max_anios'], name='lab_rango_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['orden', 'parametro_ref'], name='lab_resultado_orden_param_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['es_critico'], name='lab_resultado_critico_idx'),
        ),
    ]
