# Generated by Django 5.0.6 on 2026-04-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_conveniopreciolims_and_legacy_lab_drop'),
        ('laboratorio', '0014_cci_westgard_p21'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicioncontrolinterno',
            options={'ordering': ['-fecha_medicion'], 'verbose_name': 'Medición control interno', 'verbose_name_plural': 'Mediciones control interno'},
        ),
        migrations.AlterField(
            model_name='estadocanalanalizador',
            name='estado_operativo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA_QC', 'Alerta QC (Westgard rechazo)'), ('BLOQUEO_METROLOGIA', 'Bloqueo metrología')], db_index=True, default='NORMAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='lotematerialcontrol',
            name='numero_lote',
            field=models.CharField(max_length=120, verbose_name='Número de lote'),
        ),
        migrations.AlterField(
            model_name='lotematerialcontrol',
            name='sd',
            field=models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Desviación estándar'),
        ),
        migrations.AlterField(
            model_name='materialcontrol',
            name='descripcion_niveles',
            field=models.CharField(blank=True, help_text='Ej. L1 Normal, L2 patológico alto', max_length=500, verbose_name='Niveles (texto)'),
        ),
        migrations.AlterField(
            model_name='notificacionpanico',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_panico_iso', to='core.ordendeservicio', verbose_name='Orden Asociada'),
        ),
        migrations.AlterField(
            model_name='resultadohl7huerfano',
            name='estado_revision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente revisión QC'), ('REVISADO', 'Revisado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadohl7huerfano',
            name='item_json',
            field=models.TextField(help_text='Ítem parseado + meta (JSON)'),
        ),
        migrations.AlterField(
            model_name='resultadohl7huerfano',
            name='motivo',
            field=models.CharField(choices=[('SIN_MAPEO_ANALITO', 'Código equipo sin match en LIMS'), ('UNIDAD_INCOMPATIBLE', 'Unidad equipo distinta al catálogo'), ('VALOR_NO_NUMERICO', 'Valor no convertible a Decimal (analito numérico)')], db_index=True, max_length=40),
        ),
    ]
