# Generated by Django 5.0.6 on 2026-04-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_pagoorden_empresa_tenant_guard'),
        ('laboratorio', '0015_alter_medicioncontrolinterno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='core.paciente'),
        ),
    ]
