# Generated by Django 5.1.15 on 2026-07-27 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_usuario_rol_farmacia'),
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=240)),
                ('descripcion', models.TextField()),
                ('origen', models.CharField(choices=[('AUDITORIA_INTERNA', 'Auditoria interna'), ('AUDITORIA_EXTERNA', 'Auditoria externa'), ('QUEJA', 'Queja o reclamacion'), ('QC', 'Control de calidad'), ('EQA', 'EQA / PEEC'), ('SENTINEL', 'Sentinel'), ('INCIDENTE', 'Incidente operativo'), ('OTRO', 'Otro')], max_length=30)),
                ('severidad', models.CharField(choices=[('MENOR', 'Menor'), ('MAYOR', 'Mayor'), ('CRITICA', 'Critica')], default='MENOR', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('INVESTIGACION', 'En investigacion'), ('ACCION_CORRECTIVA', 'Accion correctiva'), ('VERIFICACION', 'En verificacion'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=24)),
                ('causa_raiz', models.TextField(blank=True, default='')),
                ('correccion_inmediata', models.TextField(blank=True, default='')),
                ('accion_correctiva', models.TextField(blank=True, default='')),
                ('evidencia_verificacion', models.TextField(blank=True, default='')),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades_cerradas', to=settings.AUTH_USER_MODEL)),
                ('detectada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades_detectadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='core.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='NoConformidadEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=24)),
                ('estado_nuevo', models.CharField(max_length=24)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='laboratorio.noconformidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RondaEQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=240)),
                ('programa', models.CharField(max_length=240)),
                ('codigo_ronda', models.CharField(max_length=120)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('MUESTRA_RECIBIDA', 'Muestra recibida'), ('ENVIADA', 'Resultados enviados'), ('EVALUADA', 'Evaluada'), ('CERRADA', 'Cerrada')], db_index=True, default='PLANIFICADA', max_length=20)),
                ('evidencia', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas_eqa', to='core.empresa')),
                ('no_conformidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas_eqa', to='laboratorio.noconformidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_laboratorio', models.DecimalField(decimal_places=6, max_digits=18)),
                ('media_grupo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('desviacion_grupo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('z_score', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('evaluacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SATISFACTORIO', 'Satisfactorio'), ('ALERTA', 'Alerta'), ('NO_SATISFACTORIO', 'No satisfactorio')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_eqa', to='lims.analito')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.rondaeqa')),
            ],
        ),
        migrations.AddIndex(
            model_name='noconformidad',
            index=models.Index(fields=['empresa', 'estado'], name='lab_nc_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='noconformidad',
            index=models.Index(fields=['empresa', 'severidad'], name='lab_nc_emp_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='rondaeqa',
            index=models.Index(fields=['empresa', 'estado'], name='lab_eqa_emp_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='rondaeqa',
            constraint=models.UniqueConstraint(fields=('empresa', 'programa', 'codigo_ronda'), name='lab_eqa_emp_prog_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='resultadoeqa',
            constraint=models.UniqueConstraint(fields=('ronda', 'analito'), name='lab_eqa_ronda_analito_uniq'),
        ),
    ]
