# Generated by Django 5.1.15 on 2026-07-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_usuario_rol_farmacia'),
        ('laboratorio', '0017_noconformidad_noconformidadevento_rondaeqa_and_more'),
        ('lims', '0011_perfilanalito_alter_perfillims_analitos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo_equipo', models.CharField(max_length=200, verbose_name='Nombre exacto en el equipo')),
                ('codigo_metodo_equipo', models.CharField(blank=True, default='', max_length=100, verbose_name='Código del método en el equipo')),
                ('volumen_muestra', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volumen de muestra (µL)')),
                ('volumen_r1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volumen R1 (µL)')),
                ('volumen_r2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volumen R2 (µL)')),
                ('fuente_documental', models.CharField(max_length=500, verbose_name='Fuente documental')),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE_MAPEO', 'Pendiente de mapeo'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('INACTIVO', 'Inactivo')], default='PENDIENTE_MAPEO', max_length=24, verbose_name='Estado de validación')),
                ('activo', models.BooleanField(default=False)),
                ('validado_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metodos_equipos', to='lims.analito', verbose_name='Analito LIMS')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_equipos', to='core.empresa', verbose_name='Empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metodos_tecnicos', to='laboratorio.equipo', verbose_name='Equipo')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_equipos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Método de equipo',
                'verbose_name_plural': 'Métodos de equipos',
                'indexes': [models.Index(fields=['empresa', 'equipo', 'estado_validacion'], name='laboratorio_empresa_05c597_idx'), models.Index(fields=['analito', 'activo'], name='laboratorio_analito_cab844_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'equipo', 'nombre_metodo_equipo'), name='laboratorio_metodo_equipo_empresa_equipo_nombre_uniq')],
            },
        ),
    ]
