# Generated by Django 5.1.15 on 2026-07-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_usuario_rol_farmacia'),
        ('laboratorio', '0018_metodoequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria; obligatoria al activar una interfaz.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_laboratorio', to='core.empresa', verbose_name='Empresa/tenant'),
        ),
        migrations.CreateModel(
            name='InterfazEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCCA_CSV', 'INCCA CSV bidireccional'), ('ICON_HL7', 'Norma Icon HL7'), ('WONDFO_HL7', 'Wondfo Finecare HL7'), ('ASTM', 'ASTM E1394'), ('JSON', 'JSON/API')], max_length=20)),
                ('estado', models.CharField(choices=[('CONFIGURADA', 'Configurada'), ('EN_PRUEBA', 'En prueba'), ('VALIDADA', 'Validada'), ('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida')], default='CONFIGURADA', max_length=20)),
                ('modo', models.CharField(choices=[('SOMBRA', 'Recepción en sombra'), ('OPERATIVA', 'Operativa')], default='SOMBRA', max_length=12)),
                ('fuente_protocolaria', models.CharField(blank=True, default='', max_length=500)),
                ('carpeta_entrada', models.CharField(blank=True, default='', max_length=500)),
                ('carpeta_salida', models.CharField(blank=True, default='', max_length=500)),
                ('variable_api_key', models.CharField(blank=True, default='', help_text='Nombre de variable; nunca guardar la clave aquí.', max_length=120)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('validada_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces_equipos', to='core.empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces_configuradas', to='laboratorio.equipo')),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces_equipo_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interfaz de equipo',
                'verbose_name_plural': 'Interfaces de equipos',
                'indexes': [models.Index(fields=['empresa', 'tipo', 'estado'], name='laboratorio_empresa_c426ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'equipo'), name='laboratorio_interfaz_equipo_empresa_equipo_uniq')],
            },
        ),
    ]
