# Generated by Django 5.1.15 on 2026-08-12 17:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_empresa(apps, schema_editor):
    Responsable = apps.get_model('laboratorio', 'ResponsableSanitario')
    Resultado = apps.get_model('laboratorio', 'ResultadoHL7')
    for responsable in Responsable.objects.filter(
        empresa__isnull=True,
        usuario__empresa__isnull=False,
    ).select_related('usuario').iterator():
        responsable.empresa_id = responsable.usuario.empresa_id
        responsable.save(update_fields=['empresa'])
    # The historical model has no trustworthy tenant for these rows.
    if Responsable.objects.filter(empresa__isnull=True).exists():
        raise RuntimeError('core/laboratorio: ResponsableSanitario sin empresa determinable.')

    for resultado in Resultado.objects.filter(
        empresa__isnull=True,
        orden__empresa__isnull=False,
    ).select_related('orden').iterator():
        resultado.empresa_id = resultado.orden.empresa_id
        resultado.save(update_fields=['empresa'])
    if Resultado.objects.filter(empresa__isnull=True).exists():
        raise RuntimeError('core/laboratorio: ResultadoHL7 sin empresa determinable.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_scope_solicitud_autorizacion_by_empresa'),
        ('laboratorio', '0019_equipo_empresa_interfazequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablesanitario',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables_sanitarios', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='resultadohl7',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_hl7', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.RunPython(backfill_empresa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='responsablesanitario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_sanitarios', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='resultadohl7',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_hl7', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='responsablesanitario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Solo puede haber UN responsable activo por empresa a la vez', verbose_name='Responsable Activo'),
        ),
    ]
