# Generated by Django 5.1.15 on 2026-08-13 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_configuracion_pin_validacion_laboratorio'),
        ('laboratorio', '0020_responsablesanitario_empresa_resultadohl7_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesanitario',
            name='cedula_profesional',
            field=models.CharField(help_text='Número de cédula profesional emitida por la Dirección General de Profesiones', max_length=50, verbose_name='Cédula Profesional (DGP)'),
        ),
        migrations.AddConstraint(
            model_name='responsablesanitario',
            constraint=models.UniqueConstraint(fields=('empresa', 'cedula_profesional'), name='uniq_responsable_cedula_empresa'),
        ),
    ]
