runtime: python311
env: flex

# Configuración para Cloud Run
service: prislab-farmacia

# Variables de entorno
env_variables:
  DEBUG: 'False'
  PORT: '8080'

# Recursos
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
