# Generated by Django 4.2 on 2026-01-26 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicio',
            name='estado_clinico',
            field=models.CharField(choices=[('PENDIENTE_TOMA', 'Pendiente de Toma de Muestra'), ('TOMA_REALIZADA', 'Toma de Muestra Realizada'), ('EN_PROCESO', 'En Proceso de Análisis'), ('VALIDADO_PARCIAL', 'Validado Parcialmente'), ('COMPLETO', 'Completo - Todos los Resultados Validados'), ('ENTREGADO', 'Entregado al Paciente')], default='PENDIENTE_TOMA', help_text='Estado del análisis clínico (independiente del pago)', max_length=20, verbose_name='Estado Clínico'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='fecha_toma_muestra',
            field=models.DateTimeField(blank=True, help_text='Timestamp de cuando se tomó la muestra (NOM-007-SSA3-2011)', null=True, verbose_name='Fecha de Toma de Muestra'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='observaciones_clinicas',
            field=models.TextField(blank=True, help_text='Notas del químico o técnico de laboratorio', null=True, verbose_name='Observaciones Clínicas'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='requiere_maquila',
            field=models.BooleanField(default=False, help_text='True si algún estudio debe enviarse a laboratorio externo', verbose_name='Requiere Maquila Externa'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='token_acceso',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID único para acceso seguro vía QR y WhatsApp', verbose_name='Token de Acceso'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='usuario_tomo_muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_tomadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Tomó la Muestra'),
        ),
    ]
