# Generated by Django 4.2 on 2026-01-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migrar_datos_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicio',
            name='medico_referente',
            field=models.ForeignKey(blank=True, help_text='Médico que solicita los estudios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_referidas', to='core.medico', verbose_name='Médico Referente'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='origen_orden',
            field=models.CharField(choices=[('PUBLICO_GENERAL', 'Público General / Walk-in'), ('MEDICO_EXTERNO', 'Médico Externo / Referencia'), ('URGENCIA', 'Urgencia Hospitalaria'), ('CONVENIO', 'Convenio Institucional')], default='PUBLICO_GENERAL', help_text='¿De dónde proviene esta orden?', max_length=20, verbose_name='Origen de la Orden'),
        ),
    ]
