# Generated by Django 4.2 on 2026-01-26 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_citamedica_signosvitales_historiaclinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_estudio', models.CharField(max_length=50, unique=True, verbose_name='Folio del Estudio')),
                ('tipo_estudio', models.CharField(choices=[('USG_ABDOMINAL', 'Ultrasonido Abdominal'), ('USG_PELVICO', 'Ultrasonido Pélvico'), ('USG_OBSTETRICO', 'Ultrasonido Obstétrico'), ('USG_MAMARIO', 'Ultrasonido Mamario'), ('USG_TIROIDES', 'Ultrasonido de Tiroides'), ('USG_HEPATICO', 'Ultrasonido Hepático'), ('USG_RENAL', 'Ultrasonido Renal'), ('USG_MUSCULO', 'Ultrasonido Músculo-Esquelético'), ('RAYOS_X_TORAX', 'Rayos X de Tórax'), ('RAYOS_X_ABDOMEN', 'Rayos X de Abdomen'), ('RAYOS_X_HUESOS', 'Rayos X Óseo'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Estudio')),
                ('fecha_estudio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Estudio')),
                ('edad_paciente', models.IntegerField(verbose_name='Edad')),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indicacion_clinica', models.TextField(verbose_name='Indicación Clínica')),
                ('antecedentes_relevantes', models.TextField(blank=True, verbose_name='Antecedentes Relevantes')),
                ('tecnica_utilizada', models.TextField(blank=True, verbose_name='Técnica Utilizada')),
                ('equipo_utilizado', models.CharField(blank=True, max_length=200, verbose_name='Equipo')),
                ('descripcion_hallazgos', models.TextField(verbose_name='Descripción de Hallazgos')),
                ('interpretacion', models.TextField(verbose_name='Interpretación')),
                ('conclusiones', models.TextField(verbose_name='Conclusiones')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('estudios_complementarios', models.TextField(blank=True, verbose_name='Estudios Complementarios Sugeridos')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('INTERPRETADO', 'Interpretado'), ('VALIDADO', 'Validado'), ('ENTREGADO', 'Entregado')], default='BORRADOR', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_imagen', to='core.consultamedica')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('medico_interpretador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_interpretados', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_imagen', to='core.paciente')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_validados', to='core.medico')),
            ],
            options={
                'verbose_name': 'Estudio de Imagen',
                'verbose_name_plural': 'Estudios de Imagen',
                'ordering': ['-fecha_estudio'],
                'permissions': [('interpretar_estudios', 'Puede interpretar estudios de imagen'), ('validar_estudios', 'Puede validar estudios de imagen')],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEstudioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_estudio', models.CharField(choices=[('USG_ABDOMINAL', 'Ultrasonido Abdominal'), ('USG_PELVICO', 'Ultrasonido Pélvico'), ('USG_OBSTETRICO', 'Ultrasonido Obstétrico'), ('USG_MAMARIO', 'Ultrasonido Mamario'), ('USG_TIROIDES', 'Ultrasonido de Tiroides'), ('USG_HEPATICO', 'Ultrasonido Hepático'), ('USG_RENAL', 'Ultrasonido Renal'), ('USG_MUSCULO', 'Ultrasonido Músculo-Esquelético'), ('RAYOS_X_TORAX', 'Rayos X de Tórax'), ('RAYOS_X_ABDOMEN', 'Rayos X de Abdomen'), ('RAYOS_X_HUESOS', 'Rayos X Óseo'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Estudio')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('tecnica_texto', models.TextField(blank=True)),
                ('descripcion_hallazgos_texto', models.TextField(blank=True)),
                ('interpretacion_texto', models.TextField(blank=True)),
                ('conclusiones_texto', models.TextField(blank=True)),
                ('uso_publico', models.BooleanField(default=False, verbose_name='Disponible para todos los médicos')),
                ('veces_usada', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de Estudio',
                'verbose_name_plural': 'Plantillas de Estudios',
                'ordering': ['tipo_estudio', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogAccesoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(null=True)),
                ('tipo_acceso', models.CharField(choices=[('LECTURA', 'Lectura'), ('MODIFICACION', 'Modificación'), ('IMPRESION', 'Impresión'), ('EXPORTACION', 'Exportación')], max_length=20, verbose_name='Tipo de Acceso')),
                ('seccion_accedida', models.CharField(max_length=100, verbose_name='Sección Accedida')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('navegador', models.CharField(blank=True, max_length=200)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acceso', to='core.historiaclinica')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso a Expediente',
                'verbose_name_plural': 'Logs de Acceso a Expedientes',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='ImagenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='estudios_imagen/%Y/%m/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('ancho', models.IntegerField(blank=True, null=True)),
                ('alto', models.IntegerField(blank=True, null=True)),
                ('tamano_bytes', models.IntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.estudioimagen')),
            ],
            options={
                'verbose_name': 'Imagen de Estudio',
                'verbose_name_plural': 'Imágenes de Estudios',
                'ordering': ['estudio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambiosConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(verbose_name='Valor Nuevo')),
                ('razon_cambio', models.TextField(verbose_name='Razón del Cambio')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(null=True)),
                ('hash_integridad', models.CharField(max_length=64, verbose_name='Hash SHA256')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='core.consultamedica')),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-timestamp'],
                'permissions': [('ver_historial_cambios', 'Puede ver historial de cambios de consultas')],
            },
        ),
        migrations.CreateModel(
            name='AudioConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_archivo', models.FileField(upload_to='audios_consultas/%Y/%m/', verbose_name='Archivo de Audio')),
                ('duracion_segundos', models.IntegerField(verbose_name='Duración (segundos)')),
                ('formato', models.CharField(default='wav', max_length=10, verbose_name='Formato')),
                ('tamano_bytes', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('hash_sha256', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA256')),
                ('timestamp_inicio', models.DateTimeField(verbose_name='Inicio de Grabación')),
                ('timestamp_fin', models.DateTimeField(verbose_name='Fin de Grabación')),
                ('transcripcion_bruta', models.TextField(blank=True, verbose_name='Transcripción Automática')),
                ('transcripcion_editada', models.TextField(blank=True, verbose_name='Transcripción Editada')),
                ('transcripcion_procesada', models.BooleanField(default=False)),
                ('navegador', models.CharField(blank=True, max_length=200)),
                ('ip_origen', models.GenericIPAddressField(null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sesion', to='core.consultamedica')),
            ],
            options={
                'verbose_name': 'Audio de Consulta',
                'verbose_name_plural': 'Audios de Consultas',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='logaccesoexpediente',
            index=models.Index(fields=['historia_clinica', 'fecha_acceso'], name='core_logacc_histori_70d442_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccesoexpediente',
            index=models.Index(fields=['usuario', 'fecha_acceso'], name='core_logacc_usuario_dca6ff_idx'),
        ),
    ]
