# Generated by Django 5.0.14 on 2026-02-01 18:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudioimagen_plantillaestudioimagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicio',
            name='archivo_resultado',
            field=models.FileField(blank=True, help_text='PDF final con resultados de laboratorio (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='resultados_laboratorio/%Y/%m/', verbose_name='PDF de Resultados'),
        ),
        migrations.AddField(
            model_name='resultadoparametro',
            name='imagen_microscopio',
            field=models.ImageField(blank=True, help_text='Evidencia fotográfica del microscopio o equipo (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='evidencias_microscopio/%Y/%m/', verbose_name='Imagen de Microscopio'),
        ),
    ]
