# Generated by Django 5.0.14 on 2026-02-01 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ordendeservicio_archivo_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioconsulta',
            name='audio_archivo',
            field=models.FileField(help_text='Audio de consulta médica almacenado en Google Drive con trazabilidad forense', storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_audio_forense', verbose_name='Archivo de Audio'),
        ),
        migrations.AlterField(
            model_name='imagendetalle',
            name='imagen',
            field=models.ImageField(help_text='Imagen de estudio diagnóstico almacenada en Google Drive', storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='archivo_resultado',
            field=models.FileField(blank=True, help_text='PDF final con resultados de laboratorio (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_laboratorio', verbose_name='PDF de Resultados'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medico_firma_digital',
            field=models.ImageField(blank=True, help_text='Firma digital del médico almacenada en Google Drive', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_receta', verbose_name='Firma Digital'),
        ),
        migrations.AlterField(
            model_name='resultadoparametro',
            name='imagen_microscopio',
            field=models.ImageField(blank=True, help_text='Evidencia fotográfica del microscopio o equipo (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive', verbose_name='Imagen de Microscopio'),
        ),
    ]
