# Generated by Django 5.0.14 on 2026-02-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_actualizar_rutas_drive_bloque1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_nombre', models.CharField(blank=True, help_text="Identificador de la caja física (ej: 'Caja 1', 'Caja Principal')", max_length=100, null=True, verbose_name='Nombre de Caja')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso (Venta, Cobro)'), ('EGRESO', 'Egreso (Reembolso, Gasto)'), ('AJUSTE', 'Ajuste (Arqueo, Corrección)'), ('TRANSFERENCIA', 'Transferencia (Retiro a Bóveda)')], db_index=True, max_length=20, verbose_name='Tipo de Movimiento')),
                ('concepto', models.CharField(choices=[('VENTA', 'Venta de Producto/Servicio'), ('REEMBOLSO_DEVOLUCION', 'Reembolso por Devolución'), ('GASTO_MENOR', 'Gasto Menor (Operativo)'), ('ARQUEO', 'Arqueo de Caja'), ('RETIRO_BOVEDA', 'Retiro a Bóveda/Banco'), ('APERTURA_CAJA', 'Apertura de Caja (Fondo Inicial)'), ('CIERRE_CAJA', 'Cierre de Caja'), ('OTRO', 'Otro (Especificar en Referencia)')], db_index=True, max_length=50, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cantidad en pesos (siempre positiva, el tipo define si es ingreso/egreso)', max_digits=12, verbose_name='Monto')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora del Movimiento')),
                ('referencia', models.CharField(blank=True, help_text='Descripción adicional o número de folio relacionado', max_length=255, verbose_name='Referencia')),
                ('saldo_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de caja antes de este movimiento', max_digits=12, null=True, verbose_name='Saldo Anterior')),
                ('saldo_posterior', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de caja después de este movimiento', max_digits=12, null=True, verbose_name='Saldo Posterior')),
                ('devolucion_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='core.devolucionventa', verbose_name='Devolución Relacionada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='core.venta', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['empresa', 'sucursal', '-fecha_movimiento'], name='core_movimi_empresa_b407b1_idx'), models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='core_movimi_tipo_mo_4cbdab_idx'), models.Index(fields=['concepto', '-fecha_movimiento'], name='core_movimi_concept_29b4b9_idx'), models.Index(fields=['usuario_responsable', '-fecha_movimiento'], name='core_movimi_usuario_e15214_idx')],
            },
        ),
    ]
