# Generated by Django 5.0.14 on 2026-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_movimiento_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='transcripcion_completa',
            field=models.TextField(blank=True, help_text='Transcripción generada por IA del audio de la consulta. Respaldo legal NOM-004.', null=True, verbose_name='Transcripción Completa (Audio a Texto)'),
        ),
        migrations.AddField(
            model_name='plantillanotaclinica',
            name='especialidad',
            field=models.CharField(blank=True, default='', help_text='Ej: Pediatría, Ginecología, General. Vacío = disponible para todos.', max_length=150, verbose_name='Especialidad'),
        ),
    ]
