# Generated by Django 5.0.14 on 2026-02-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consultorio_isla_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmodulos',
            name='pin_precio_neto',
            field=models.CharField(default='1234', help_text='PIN numérico para autorizar descuento a precio de costo. Default: 1234', max_length=10, verbose_name='PIN Precio Neto (Staff)'),
        ),
    ]
