# Generated by Django 5.0.14 on 2026-02-10 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_pin_precio_neto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint de Push')),
                ('p256dh', models.CharField(help_text='Clave de cifrado del cliente', max_length=255, verbose_name='Clave Pública (p256dh)')),
                ('auth', models.CharField(help_text='Token de autenticación del cliente', max_length=255, verbose_name='Token de Autenticación')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y sistema operativo del dispositivo', max_length=500, verbose_name='User Agent')),
                ('nombre_dispositivo', models.CharField(blank=True, help_text='Ej: iPhone de Jonathan, Chrome en Desktop', max_length=100, verbose_name='Nombre del Dispositivo')),
                ('activa', models.BooleanField(default=True, verbose_name='Suscripción Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Última Notificación Enviada')),
                ('notificar_errores_500', models.BooleanField(default=True, verbose_name='Notificar Errores 500')),
                ('notificar_solo_criticos', models.BooleanField(default=False, help_text='Si está marcado, solo notifica severidad CRITICA/ALTA', verbose_name='Solo Errores Críticos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='core_pushsu_usuario_2488c4_idx'), models.Index(fields=['endpoint'], name='core_pushsu_endpoin_0a3bd0_idx')],
            },
        ),
    ]
