# Generated by Django 5.0.14 on 2026-02-10 08:35
# Corregida: migración en 3 pasos para evitar duplicados de UUID

import uuid
from django.db import migrations, models


def generar_uuids_unicos(apps, schema_editor):
    """Genera un UUID único para cada paciente existente."""
    Paciente = apps.get_model('core', 'Paciente')
    for paciente in Paciente.objects.all():
        paciente.uuid = uuid.uuid4()
        paciente.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pushsubscription'),
    ]

    operations = [
        # Paso 1: Agregar campo UUID sin restricción unique
        migrations.AddField(
            model_name='paciente',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (inmutable) para trazabilidad entre módulos', null=True, verbose_name='UUID del Paciente'),
        ),
        # Paso 2: Generar UUIDs únicos para filas existentes
        migrations.RunPython(generar_uuids_unicos, migrations.RunPython.noop),
        # Paso 3: Ahora sí agregar la restricción unique
        migrations.AlterField(
            model_name='paciente',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (inmutable) para trazabilidad entre módulos', null=True, unique=True, verbose_name='UUID del Paciente'),
        ),
    ]
