# Generated by Django 5.0.14 on 2026-02-10 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_paciente_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora del Comando')),
                ('url_actual', models.CharField(help_text='Contexto visual del usuario', max_length=500, verbose_name='URL Donde se Emitió el Comando')),
                ('datos_pantalla', models.TextField(blank=True, help_text='JSON o texto con contexto de lo que el usuario ve', null=True, verbose_name='Datos de Pantalla (Contexto)')),
                ('transcripcion', models.TextField(help_text='Texto reconocido por Web Speech API', verbose_name='Transcripción del Comando de Voz')),
                ('tipo_comando', models.CharField(choices=[('BUSQUEDA', 'Búsqueda de Información'), ('ACCION', 'Acción / Comando'), ('NAVEGACION', 'Navegación'), ('COMUNICACION', 'Comunicación (Walkie-Talkie)'), ('CONSULTA', 'Consulta a IA'), ('CRITICO', 'Comando Crítico (Requiere Auth)')], max_length=20, verbose_name='Tipo de Comando')),
                ('intencion_detectada', models.CharField(help_text="Ej: 'buscar_paciente', 'surtir_receta', 'cerrar_caja'", max_length=255, verbose_name='Intención Detectada por IA')),
                ('parametros_extraidos', models.JSONField(blank=True, default=dict, help_text="JSON con parámetros del comando. Ej: {'folio': '554', 'paciente': 'Juan'}", verbose_name='Parámetros Extraídos')),
                ('respuesta_ia', models.TextField(blank=True, help_text='Respuesta de Gemini al comando', null=True, verbose_name='Respuesta de la IA')),
                ('accion_ejecutada', models.CharField(blank=True, help_text="Vista/función que se ejecutó. Ej: 'farmacia.views.surtir_receta'", max_length=255, null=True, verbose_name='Acción Ejecutada')),
                ('estado', models.CharField(choices=[('EXITOSO', 'Ejecutado Exitosamente'), ('BLOQUEADO', 'Bloqueado por Permisos'), ('ERROR', 'Error en Ejecución'), ('CANCELADO', 'Cancelado por Usuario')], default='EXITOSO', max_length=20, verbose_name='Estado de Ejecución')),
                ('mensaje_error', models.TextField(blank=True, help_text='Si el comando falló, detalles del error', null=True, verbose_name='Mensaje de Error')),
                ('requiere_autenticacion', models.BooleanField(default=False, help_text='True si requirió WebAuthn / Huella', verbose_name='Requirió Autenticación Adicional')),
                ('autenticacion_exitosa', models.BooleanField(default=False, verbose_name='Autenticación Exitosa')),
                ('nivel_autorizado', models.CharField(default='STAFF', help_text='STAFF, DIRECTOR, etc.', max_length=50, verbose_name='Nivel de Autorización del Usuario')),
                ('audio_file', models.FileField(blank=True, help_text='Audio original del comando (opcional)', null=True, upload_to='voice_commands/%Y/%m/', verbose_name='Archivo de Audio')),
                ('duracion_segundos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duración del Audio (segundos)')),
                ('tiempo_procesamiento_ms', models.IntegerField(blank=True, help_text='Latencia desde transcripción hasta respuesta', null=True, verbose_name='Tiempo de Procesamiento (ms)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_commands', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Comando de Voz',
                'verbose_name_plural': 'Logs de Comandos de Voz',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_voice_logs', 'Puede ver todos los logs de voz'), ('delete_voice_logs', 'Puede eliminar logs de voz')],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='core_voicea_usuario_af8865_idx'), models.Index(fields=['tipo_comando', '-timestamp'], name='core_voicea_tipo_co_84a60b_idx'), models.Index(fields=['estado', '-timestamp'], name='core_voicea_estado_c689d7_idx'), models.Index(fields=['-timestamp'], name='core_voicea_timesta_568d36_idx')],
            },
        ),
    ]
