# Generated by Django 5.0.14 on 2026-02-11 - Convenios, CxC, NotaCredito

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mensajeinterno_audio_fields'),
    ]

    operations = [
        # ── CONVENIOS ──
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Empresa/Aseguradora')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa Privada'), ('ASEGURADORA', 'Aseguradora'), ('GOBIERNO', 'Gobierno / Dependencia'), ('ONG', 'ONG / Fundacion')], default='EMPRESA', max_length=20)),
                ('dias_credito', models.IntegerField(default=15, help_text='Plazo en dias para el pago (15, 30, 45, etc.)', verbose_name='Dias de Credito')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento General %')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Credito ($)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioPrecioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_convenio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Convenio')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_estudios', to='core.convenio')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_convenio', to='core.estudio')),
            ],
            options={
                'verbose_name': 'Precio de Estudio por Convenio',
                'verbose_name_plural': 'Precios de Estudios por Convenio',
                'unique_together': {('convenio', 'estudio')},
            },
        ),

        # ── CUENTAS POR COBRAR ──
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio CxC')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Pendiente')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emision')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha de Cobro')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Cobro'), ('PARCIAL', 'Pago Parcial'), ('COBRADO', 'Cobrado Totalmente'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='core.empresa')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='core.convenio', verbose_name='Empresa / Convenio')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='core.ordendeservicio', verbose_name='Orden de Servicio')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='core.venta', verbose_name='Venta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-fecha_vencimiento'],
                'indexes': [
                    models.Index(fields=['empresa', 'estado', '-fecha_vencimiento'], name='core_cuentap_empresa_idx'),
                    models.Index(fields=['convenio', 'estado'], name='core_cuentap_convenio_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Deposito')], default='TRANSFERENCIA', max_length=30)),
                ('referencia', models.CharField(blank=True, help_text='Numero de transferencia, cheque, etc.', max_length=200, null=True)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cuentaporcobrar')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Cuenta por Cobrar',
                'verbose_name_plural': 'Pagos de Cuentas por Cobrar',
                'ordering': ['-fecha_pago'],
            },
        ),

        # ── NOTAS DE CREDITO ──
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio Nota de Credito')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Nota')),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolucion de producto'), ('ERROR_COBRO', 'Error de cobro'), ('DESCUENTO_POST', 'Descuento posterior'), ('CANCELACION', 'Cancelacion de servicio'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(verbose_name='Descripcion detallada')),
                ('aplicada', models.BooleanField(default=False, verbose_name='Aplicada al saldo')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='core.empresa')),
                ('venta_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='core.venta')),
                ('orden_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='core.ordendeservicio')),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='core.devolucionventa')),
                ('emitida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Credito',
                'verbose_name_plural': 'Notas de Credito',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
