# Generated by Django 5.0.14 on 2026-02-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_medico_empresa_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='acepta_privacidad',
            field=models.BooleanField(default=False, verbose_name='Acepta Aviso de Privacidad'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='acepta_procesamiento',
            field=models.BooleanField(default=False, verbose_name='Acepta Procesamiento de Datos'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='fecha_firma',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Firma'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='firma_digital',
            field=models.TextField(help_text='Firma del paciente en formato base64', verbose_name='Firma Digital (base64)'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='hash_firma',
            field=models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 de Integridad'),
        ),
        migrations.AlterField(
            model_name='mensajeinterno',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
        migrations.AlterField(
            model_name='preordenlaboratorio',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preordenes', to='core.consultamedica', verbose_name='Consulta Médica'),
        ),
        migrations.AlterUniqueTogether(
            name='parametro',
            unique_together={('estudio', 'abreviatura')},
        ),
    ]
