# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='core_pacien_nombres_idx',
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='core_pacien_apellido_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagoorden',
            name='core_pagoord_fecha_p_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagoorden',
            name='core_pagoord_orden_f_idx',
        ),
        migrations.RenameIndex(
            model_name='ordendeservicio',
            new_name='core_ordend_fecha_c_f7ff31_idx',
            old_name='core_ordend_fecha_c_idx',
        ),
        migrations.RenameIndex(
            model_name='ordendeservicio',
            new_name='core_ordend_estado_941f2f_idx',
            old_name='core_ordend_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='ordendeservicio',
            new_name='core_ordend_empresa_95fbae_idx',
            old_name='core_ordend_empresa_f_idx',
        ),
        migrations.RenameIndex(
            model_name='ordendeservicio',
            new_name='core_ordend_empresa_20cf45_idx',
            old_name='core_ordend_empresa_e_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='core_venta_fecha_a21ebc_idx',
            old_name='core_venta_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='core_venta_empresa_5eeb38_idx',
            old_name='core_venta_empresa_f_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='core_venta_empresa_650c0b_idx',
            old_name='core_venta_empresa_e_idx',
        ),
        migrations.AlterField(
            model_name='audioconsulta',
            name='audio_archivo',
            field=models.FileField(help_text='Audio de consulta médica almacenado en Google Drive con trazabilidad forense', storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_audio_forense', validators=[core.validators.validate_audio_upload], verbose_name='Archivo de Audio'),
        ),
        migrations.AlterField(
            model_name='backupregistro',
            name='archivo_backup',
            field=models.FileField(upload_to='backups/', validators=[core.validators.validate_backup_upload], verbose_name='Archivo de Backup Comprimido y Encriptado'),
        ),
        migrations.AlterField(
            model_name='bitacora39a',
            name='pdf_firmado',
            field=models.FileField(blank=True, help_text='PDF de evaluación firmado electrónicamente como respaldo legal', null=True, upload_to='bitacoras_39a/', validators=[core.validators.validate_document_upload], verbose_name='PDF Firmado Digitalmente'),
        ),
        migrations.AlterField(
            model_name='certificadomedico',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_certificados/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='devolucionventa',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/%Y/%m/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='documentoconocimiento',
            name='archivo_pdf',
            field=models.FileField(upload_to='conocimiento/%Y/%m/%d/', validators=[core.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[core.validators.validate_image_upload], verbose_name='Logotipo Oficial'),
        ),
        migrations.AlterField(
            model_name='firmadigital',
            name='imagen_firma',
            field=models.ImageField(upload_to='firmas/', validators=[core.validators.validate_image_upload], verbose_name='Imagen de la Firma'),
        ),
        migrations.AlterField(
            model_name='gastooperativo',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='gastos_operativos/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='imagendetalle',
            name='imagen',
            field=models.ImageField(help_text='Imagen de estudio diagnóstico almacenada en Google Drive', storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive', validators=[core.validators.validate_image_upload], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mantenimientoequipo',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimiento_equipo/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='mensajeinterno',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audios/%Y/%m/', validators=[core.validators.validate_audio_upload], verbose_name='Nota de Voz'),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='archivo_resultado',
            field=models.FileField(blank=True, help_text='PDF final con resultados de laboratorio (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_laboratorio', validators=[core.validators.validate_document_upload], verbose_name='PDF de Resultados'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Obligatorio para pacientes ambulatorios (Lab)', null=True, validators=[core.validators.validate_fecha_nacimiento_razonable], verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medico_firma_digital',
            field=models.ImageField(blank=True, help_text='Firma digital del médico almacenada en Google Drive', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive_receta', validators=[core.validators.validate_image_upload], verbose_name='Firma Digital'),
        ),
        migrations.AlterField(
            model_name='resultadoparametro',
            name='imagen_microscopio',
            field=models.ImageField(blank=True, help_text='Evidencia fotográfica del microscopio o equipo (se almacena en Google Drive)', null=True, storage=core.models.get_google_drive_storage, upload_to='core.utils.paths.generar_ruta_drive', validators=[core.validators.validate_image_upload], verbose_name='Imagen de Microscopio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceauditlog',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio original del comando (opcional)', null=True, upload_to='voice_commands/%Y/%m/', validators=[core.validators.validate_audio_upload], verbose_name='Archivo de Audio'),
        ),
    ]
