# Generated by Django 5.0.14 on 2026-02-22 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_clinical_data_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEntregaResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.PositiveIntegerField(verbose_name='ID de Orden de Laboratorio')),
                ('folio_orden', models.CharField(blank=True, max_length=40, verbose_name='Folio de Orden')),
                ('paciente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('paciente_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Paciente')),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo electrónico'), ('PORTAL', 'Portal del paciente'), ('IMPRESO', 'Impreso en mostrador')], default='PRESENCIAL', max_length=20, verbose_name='Canal de Entrega')),
                ('estado', models.CharField(choices=[('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado por paciente'), ('PENDIENTE', 'Pendiente de entrega'), ('REIMPRESION', 'Reimpresión solicitada')], default='ENTREGADO', max_length=15, verbose_name='Estado')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Entrega')),
                ('firma_digital', models.TextField(blank=True, null=True, verbose_name='Firma Digital (base64)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('destino_envio', models.CharField(blank=True, max_length=200, verbose_name='Destino del Envío')),
                ('confirmado_lectura', models.BooleanField(default=False, verbose_name='Confirmado por el destinatario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Personal que entregó')),
            ],
            options={
                'verbose_name': 'Bitácora de Entrega de Resultados',
                'verbose_name_plural': 'Bitácora de Entregas de Resultados',
                'ordering': ['-fecha_entrega'],
                'permissions': [('view_bitacora_entregas', 'Puede ver bitácora de entregas'), ('reprint_resultados', 'Puede solicitar reimpresión de resultados')],
                'indexes': [models.Index(fields=['empresa', '-fecha_entrega'], name='core_bitaco_empresa_cb37a2_idx'), models.Index(fields=['orden_id'], name='core_bitaco_orden_i_37f56b_idx'), models.Index(fields=['paciente_id', '-fecha_entrega'], name='core_bitaco_pacient_b3f21f_idx')],
            },
        ),
    ]
