# Generated by Django 5.0.14 on 2026-02-22 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_bitacora_entrega_resultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico'), ('EXITO', 'Éxito'), ('SISTEMA', 'Sistema')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('modulo', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('FARMACIA', 'Farmacia'), ('CONSULTORIO', 'Consultorio'), ('FINANZAS', 'Finanzas'), ('RH', 'Recursos Humanos'), ('SISTEMA', 'Sistema'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Módulo origen')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, max_length=500, verbose_name='URL de acción (opcional)')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de objeto relacionado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='ID de objeto relacionado')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario (null = todos)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.empresa', verbose_name='Empresa')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Notificación del Sistema',
                'verbose_name_plural': 'Notificaciones del Sistema',
                'ordering': ['-creada'],
                'indexes': [models.Index(fields=['destinatario', 'leida', '-creada'], name='core_notifi_destina_7f5d2b_idx'), models.Index(fields=['empresa', '-creada'], name='core_notifi_empresa_0bce14_idx'), models.Index(fields=['modulo', '-creada'], name='core_notifi_modulo_9b55f2_idx')],
            },
        ),
    ]
