# Generated by Django 5.0.14 on 2026-02-22 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notificacion_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Quincena 1 — Febrero 2026', max_length=100, verbose_name='Nombre del período')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=15, verbose_name='Frecuencia de pago')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('ABIERTO', 'En captura'), ('CERRADO', 'Cerrado — en revisión'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_nomina', to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo base')),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas extra')),
                ('importe_he', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe horas extra')),
                ('bonificacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonificación / comisión')),
                ('percepciones_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otras percepciones')),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de percepciones')),
                ('imss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuota IMSS trabajador')),
                ('isr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ISR retenido')),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INFONAVIT')),
                ('prestamo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento por préstamo')),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otras deducciones')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de deducciones')),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Neto a pagar')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago efectivo')),
                ('metodo_pago', models.CharField(blank=True, help_text='EFECTIVO, TRANSFERENCIA, CHEQUE', max_length=30, verbose_name='Método de pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia / folio de transferencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_nomina', to='core.empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='core.periodonomina', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Recibo de Nómina',
                'verbose_name_plural': 'Recibos de Nómina',
                'ordering': ['-periodo__fecha_inicio', 'empleado'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
