# Generated by Django 5.0.14 on 2026-02-22 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_nomina_periodo_recibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del documento')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual operativo'), ('POLITICA', 'Política interna'), ('PROCESO', 'Procedimiento'), ('NORMATIVA', 'Normativa / NOM'), ('OTRO', 'Otro')], default='MANUAL', max_length=20)),
                ('archivo', models.FileField(upload_to='capacitacion/', verbose_name='Archivo PDF/DOCX')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / resumen')),
                ('contenido_texto', models.TextField(blank=True, verbose_name='Texto extraído (para búsqueda RAG)')),
                ('version', models.CharField(blank=True, default='1.0', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_capacitacion', to='core.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Capacitación',
                'verbose_name_plural': 'Documentos de Capacitación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CapsulaSabiduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(verbose_name='Contenido de la cápsula')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('veces_consultada', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsulas_sabiduria', to='core.empresa')),
                ('documento_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsulas', to='core.documentocapacitacion')),
            ],
            options={
                'verbose_name': 'Cápsula de Sabiduría',
                'verbose_name_plural': 'Cápsulas de Sabiduría',
                'ordering': ['-veces_consultada', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Turno Matutino, Guardia Nocturna', max_length=100, verbose_name='Nombre del turno')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='Día de la semana')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('tolerancia_minutos', models.PositiveSmallIntegerField(default=10, verbose_name='Tolerancia (minutos)')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, help_text='Dejar vacío para horario general del departamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabajo', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['dia_semana', 'hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FALTA', 'Falta'), ('RETARDO', 'Retardo'), ('PERMISO', 'Permiso con goce'), ('PERMISO_SG', 'Permiso sin goce'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad médica'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de incidencia')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('dias', models.PositiveSmallIntegerField(default=1, verbose_name='Días')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo / justificación')),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='incidencias/', verbose_name='Documento de soporte')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='core.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_asistencia', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Incidencia de Asistencia',
                'verbose_name_plural': 'Incidencias de Asistencia',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='AlertaBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico — protocolo de crisis')], default='MEDIO', max_length=10)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('VISTA', 'Vista por dirección'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=10)),
                ('descripcion', models.TextField(verbose_name='Descripción de la alerta')),
                ('accion_tomada', models.TextField(blank=True, verbose_name='Acción tomada')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_bienestar', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_bienestar', to=settings.AUTH_USER_MODEL)),
                ('visto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Bienestar',
                'verbose_name_plural': 'Alertas de Bienestar',
                'ordering': ['-fecha_alerta'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='core_alerta_empresa_e7b66a_idx'), models.Index(fields=['usuario', '-fecha_alerta'], name='core_alerta_usuario_4b1605_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversacionBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('PRIS', 'PRIS IA')], default='USUARIO', max_length=10)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado_salud', models.CharField(choices=[('NORMAL', 'Normal'), ('ATENCION', 'Requiere atención'), ('ALERTA', 'Alerta roja — riesgo')], default='NORMAL', max_length=10, verbose_name='Estado detectado por IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=True, help_text='Solo visible para el propio usuario y dirección ante alerta roja')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_bienestar', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_bienestar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación de Bienestar',
                'verbose_name_plural': 'Conversaciones de Bienestar',
                'ordering': ['fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'fecha_creacion'], name='core_conver_usuario_fd6f16_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentocapacitacion',
            index=models.Index(fields=['empresa', 'tipo', 'activo'], name='core_docume_empresa_16fe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='horariotrabajo',
            index=models.Index(fields=['empresa', 'activo'], name='core_horari_empresa_69c71f_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciaasistencia',
            index=models.Index(fields=['empresa', 'estado'], name='core_incide_empresa_c44450_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciaasistencia',
            index=models.Index(fields=['empleado', '-fecha_inicio'], name='core_incide_emplead_feb3c6_idx'),
        ),
    ]
