# Generated by Django 5.0.14 on 2026-02-22 18:30

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Remove duplicate indexes safely (may not exist in all DB backends)."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("DROP INDEX IF EXISTS core_pacien_nombre__3dc2ec_idx;")
            cursor.execute("DROP INDEX IF EXISTS core_pacien_telefon_357674_idx;")
        elif connection.vendor == 'sqlite':
            try:
                cursor.execute("DROP INDEX IF EXISTS core_pacien_nombre__3dc2ec_idx;")
            except Exception:
                pass
            try:
                cursor.execute("DROP INDEX IF EXISTS core_pacien_telefon_357674_idx;")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_documentocapacitacion_capsulasabiduria_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historialresultados',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
