# Generated by Django 5.0.14 on 2026-02-23 14:51

from django.db import migrations


def remove_indexes_safe(apps, schema_editor):
    """Remove indexes safely - they may already have been dropped by migration 0032."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        for idx_name in ('core_pacien_nombre__3dc2ec_idx', 'core_pacien_telefon_357674_idx'):
            try:
                if connection.vendor == 'postgresql':
                    cursor.execute(f"DROP INDEX IF EXISTS {idx_name};")
                else:
                    cursor.execute(f"DROP INDEX IF EXISTS {idx_name};")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_paciente_core_pacien_nombre__3dc2ec_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='paciente',
                    name='core_pacien_nombre__3dc2ec_idx',
                ),
                migrations.RemoveIndex(
                    model_name='paciente',
                    name='core_pacien_telefon_357674_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="SELECT 1;",  # No-op: indexes already dropped in 0032
                    reverse_sql="SELECT 1;",
                ),
            ],
        ),
    ]
