# Generated by Django 5.0.6 on 2026-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_estudio_venta_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='aplica_descuento_inapam',
            field=models.BooleanField(default=False, help_text='Si está activo, este estudio acepta el descuento INAPAM configurado en políticas.', verbose_name='Aplica Descuento INAPAM'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje aplicado (0-100). Aplica cuando tipo_descuento=PORCENTAJE o INAPAM.', max_digits=5, verbose_name='Porcentaje de Descuento'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='tipo_descuento',
            field=models.CharField(choices=[('NINGUNO', 'Sin Descuento'), ('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo'), ('INAPAM', 'INAPAM / 3ª Edad')], default='NINGUNO', max_length=12, verbose_name='Tipo de Descuento'),
        ),
    ]
