# Generated by Django 5.0.14 on 2026-03-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_descuentos_inapam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='aplica_descuento_inapam',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='venta_individual',
        ),
        migrations.RemoveField(
            model_name='ordendeservicio',
            name='porcentaje_descuento',
        ),
        migrations.RemoveField(
            model_name='ordendeservicio',
            name='tipo_descuento',
        ),
    ]
