# Generated by Django 5.0.6 on 2026-03-29 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_estudio_aplica_descuento_inapam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRELLENAR_FORM', 'Pre-llenar formulario'), ('CREAR_REGISTRO', 'Crear registro'), ('MODIFICAR_REGISTRO', 'Modificar registro'), ('NAVEGAR_MODULO', 'Navegar a módulo'), ('GENERAR_REPORTE', 'Generar reporte'), ('VALIDAR_RESULTADO', 'Validar resultado de laboratorio'), ('ALERTA_CRITICA', 'Alerta de valor crítico')], max_length=30, verbose_name='Tipo de acción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADO', 'Confirmado por usuario'), ('RECHAZADO', 'Rechazado por usuario'), ('EXPIRADO', 'Expirado sin respuesta')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('modulo_destino', models.CharField(blank=True, default='', help_text="Ej: 'laboratorio.recepcion', 'farmacia.pdv'", max_length=100, verbose_name='Módulo destino')),
                ('instruccion_original', models.TextField(help_text='Texto exacto del dictado o comando enviado a PRIS.', verbose_name='Instrucción original (voz/texto)')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='JSON con los campos que PRIS propone pre-llenar o ejecutar.', verbose_name='Datos propuestos')),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Respuesta del sistema tras confirmar la acción (IDs creados, errores, etc.).', verbose_name='Resultado de ejecución')),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de propuesta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('expira_en', models.DateTimeField(blank=True, help_text='Si no se confirma antes de esta fecha, pasa a estado EXPIRADO.', null=True, verbose_name='Expira en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_pris', to='core.empresa', verbose_name='Empresa')),
                ('usuario_confirmador', models.ForeignKey(blank=True, help_text='El usuario que dio el clic final de Confirmar o Rechazar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_pris_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que confirmó/rechazó')),
                ('usuario_solicitante', models.ForeignKey(blank=True, help_text='El usuario que dio la instrucción de voz o texto a PRIS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_pris_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que activó PRIS')),
            ],
            options={
                'verbose_name': 'Acción PRIS',
                'verbose_name_plural': 'Acciones PRIS',
                'ordering': ['-fecha_propuesta'],
                'indexes': [models.Index(fields=['estado', 'empresa'], name='pris_estado_empresa_idx'), models.Index(fields=['usuario_solicitante', 'estado'], name='pris_user_estado_idx')],
            },
        ),
    ]
