# Generated by Django 5.0.6 on 2026-03-29 19:32

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_orden_empresa_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mfa_activo',
            field=models.BooleanField(default=False, help_text='Si True, se requiere código TOTP en cada inicio de sesión', verbose_name='2FA Activado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Clave secreta TOTP para autenticación de dos factores', max_length=64, verbose_name='TOTP Secret (2FA)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Director General / Dueño'), ('CAJERO', 'Cajero'), ('MEDICO', 'Médico'), ('QUIMICO', 'Químico'), ('RECEPCION', 'Recepción'), ('GERENTE', 'Gerente')], default='CAJERO', max_length=50, verbose_name='Rol de Usuario'),
        ),
        migrations.CreateModel(
            name='AlertaBurnout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HUMOR_BAJO', 'Humor bajo sostenido (>5 días)'), ('ESTRES_ALTO', 'Estrés elevado sostenido (>5 días)'), ('NOM035_RIESGO', 'Riesgo NOM-035 medio/alto'), ('AUSENCIAS', 'Patrón de ausencias frecuentes'), ('TURNO_EXCESO', 'Horas extra excesivas (>50h/semana)')], max_length=20)),
                ('nivel_riesgo', models.IntegerField(choices=[(1, 'Sin riesgo'), (2, 'Riesgo bajo'), (3, 'Riesgo medio'), (4, 'Riesgo alto'), (5, 'Riesgo muy alto')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('notas_rrhh', models.TextField(blank=True, default='')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_burnout_atendidas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_burnout', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Alerta de Burnout',
                'verbose_name_plural': 'Alertas de Burnout',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas', models.IntegerField(default=1)),
                ('completada', models.BooleanField(default=False)),
                ('certificado_url', models.URLField(blank=True)),
                ('impartida_por', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_staff', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SesionCoachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COACHING', 'Coaching de desempeño'), ('APOYO', 'Apoyo psicológico'), ('SEGUIMIENTO', 'Seguimiento NOM-035'), ('DISCIPLINARIA', 'Sesión disciplinaria'), ('CAPACITACION', 'Capacitación')], max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=15)),
                ('fecha_sesion', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(default=60)),
                ('notas_privadas', core.fields.EncryptedTextField(blank=True, default='', help_text='Notas confidenciales del coach. CIFRADAS AES-256.')),
                ('compromisos', models.TextField(blank=True, default='', help_text='Compromisos no cifrados')),
                ('proxima_sesion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_coaching_impartidas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_coaching_recibidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sesión de Coaching (Staff)',
                'verbose_name_plural': 'Sesiones de Coaching (Staff)',
                'ordering': ['-fecha_sesion'],
            },
        ),
        migrations.CreateModel(
            name='DiarioEmocionalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('humor_general', models.IntegerField(choices=[(1, '😔 Muy mal'), (2, '😕 Mal'), (3, '😐 Regular'), (4, '🙂 Bien'), (5, '😀 Excelente')])),
                ('nivel_estres', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Nivel de estrés del 1 al 10')),
                ('contenido', core.fields.EncryptedTextField(blank=True, default='', help_text='Texto libre cifrado. SOLO legible por el empleado.')),
                ('horas_sueno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('actividad_fisica', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario_emocional_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diario Emocional (Staff)',
                'verbose_name_plural': 'Diarios Emocionales (Staff)',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionNOM035',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('periodo', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('respuestas_json', core.fields.EncryptedTextField(blank=True, default='', help_text='JSON con respuestas 1-5 para cada ítem. CIFRADO AES-256.')),
                ('score_total', models.IntegerField(default=0, help_text='Suma de respuestas')),
                ('nivel_riesgo', models.IntegerField(choices=[(1, 'Sin riesgo'), (2, 'Riesgo bajo'), (3, 'Riesgo medio'), (4, 'Riesgo alto'), (5, 'Riesgo muy alto')], default=1)),
                ('completada', models.BooleanField(default=False)),
                ('notas_evaluador', models.TextField(blank=True, default='')),
                ('aplicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_nom035', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Evaluación NOM-035',
                'verbose_name_plural': 'Evaluaciones NOM-035',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'periodo')},
            },
        ),
    ]
