# Generated by Django 5.0.6 on 2026-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_usuario_mfa_activo_usuario_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'fecha_caducidad'], name='core_lote_prod_caducidad_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'cantidad'], name='core_lote_prod_cantidad_idx'),
        ),
    ]
