# Generated by Django 5.0.6 on 2026-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_lote_perf_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['empresa', 'fecha_cita'], name='core_cita_emp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['empresa', 'estado'], name='core_cita_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['paciente', 'fecha_cita'], name='core_cita_pac_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['empresa', 'fecha_consulta'], name='core_cons_emp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['empresa', 'estado'], name='core_cons_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['paciente', 'fecha_consulta'], name='core_cons_pac_fecha_idx'),
        ),
    ]
