# Generated by Django 5.0.6 on 2026-03-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_clinico_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='numero_expediente',
            field=models.CharField(max_length=50, verbose_name='Número de Expediente'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', '-fecha'], name='gasto_empresa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['empresa', '-fecha'], name='gastocaja_empresa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='gastooperativo',
            index=models.Index(fields=['empresa', '-fecha'], name='gastoop_empresa_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinica',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_expediente'), name='historia_clinica_empresa_expediente_unique'),
        ),
    ]
