# Generated by Django 5.0.6 on 2026-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicio',
            name='requiere_factura',
            field=models.BooleanField(default=False, help_text='Indica si el paciente solicitó factura al momento del ingreso', verbose_name='Requiere Factura CFDI'),
        ),
    ]
