# Generated by Django 5.0.6 on 2026-03-31 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_requiere_factura_to_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicio',
            name='es_cxc',
            field=models.BooleanField(default=False, help_text='Orden confirmada con saldo pendiente registrado', verbose_name='Es Cuenta por Cobrar'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='motivo_cxc',
            field=models.CharField(blank=True, choices=[('CONVENIO', 'Convenio / Empresa'), ('CREDITO_DIRECTOR', 'Crédito Autorizado por Director'), ('COMPLEMENTO_POSTERIOR', 'Complemento Posterior'), ('PACIENTE_VIP', 'Paciente Frecuente / VIP'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='Motivo CxC'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='nota_cxc',
            field=models.TextField(blank=True, null=True, verbose_name='Nota CxC'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='monto_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='T. Crédito'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='monto_debito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='T. Débito'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('RUTINA', 'Rutina'), ('URGENTE', 'Urgente'), ('STAT', 'STAT — Inmediato'), ('CONTROL', 'Control de Calidad'), ('MAQUILA', 'Maquila (Externo)'), ('URGENCIA', 'Urgencia')], default='RUTINA', max_length=10, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Cobro'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarjeta (Total)'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Transferencia'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia / Autorización'),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Cobrado por'),
        ),
    ]
