# Generated by Django 5.0.6 on 2026-03-31 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_fase2b_2c_4_pagoorден_cxc_tipservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomamuestra',
            name='ayuno_confirmado',
            field=models.BooleanField(default=False, help_text='Paciente confirmó condición de ayuno cuando aplica', verbose_name='Ayuno Confirmado'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='consentimiento_firmado',
            field=models.BooleanField(default=False, help_text='Consentimiento informado firmado digitalmente', verbose_name='Consentimiento Firmado'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='duracion_extraccion_seg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración Extracción (seg)'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='hora_fin_extraccion',
            field=models.DateTimeField(blank=True, help_text='Timestamp en que se pulsó FINALIZAR Y ENVIAR', null=True, verbose_name='Hora Fin Extracción'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='hora_inicio_extraccion',
            field=models.DateTimeField(blank=True, help_text='Timestamp en que el flebotomista pulsó INICIAR TOMA', null=True, verbose_name='Hora Inicio Extracción'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='identidad_verificada',
            field=models.BooleanField(default=False, help_text='Flebotomista confirmó identidad del paciente antes de la extracción', verbose_name='Identidad Verificada'),
        ),
        migrations.AddField(
            model_name='tomamuestra',
            name='notas_ia',
            field=models.TextField(blank=True, help_text='Observaciones clínicas generadas automáticamente durante la grabación', null=True, verbose_name='Notas PRIS-IA'),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='estado_clinico',
            field=models.CharField(choices=[('PENDIENTE_TOMA', 'Pendiente de Toma de Muestra'), ('EN_EXTRACCION', 'En Proceso de Extracción'), ('TOMA_REALIZADA', 'Toma de Muestra Realizada'), ('EN_PROCESO', 'En Proceso de Análisis'), ('VALIDADO_PARCIAL', 'Validado Parcialmente'), ('COMPLETO', 'Completo - Todos los Resultados Validados'), ('ENTREGADO', 'Entregado al Paciente')], default='PENDIENTE_TOMA', help_text='Estado del análisis clínico (independiente del pago)', max_length=20, verbose_name='Estado Clínico'),
        ),
        migrations.CreateModel(
            name='AudioTomaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_cifrado', models.BinaryField(blank=True, null=True, verbose_name='Audio Cifrado (Fernet/AES-256)')),
                ('hash_sha256', models.CharField(blank=True, help_text='Integridad forense: hash del audio ANTES de cifrar', max_length=64, verbose_name='Hash SHA-256 del audio original')),
                ('duracion_segundos', models.IntegerField(default=0, verbose_name='Duración (seg)')),
                ('formato', models.CharField(default='webm', max_length=10, verbose_name='Formato')),
                ('timestamp_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Grabación')),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin Grabación')),
                ('transcripcion_ia', models.TextField(blank=True, help_text='Texto transcrito en tiempo real por el motor NLP', verbose_name='Transcripción PRIS-IA')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('motivo_acceso', models.TextField(blank=True, help_text='Solo DIRECTOR_QC. Debe registrar el motivo antes de descargar', verbose_name='Motivo de Acceso Justificado')),
                ('accedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_toma_accedidos', to=settings.AUTH_USER_MODEL, verbose_name='Último acceso por')),
                ('toma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core.tomamuestra', verbose_name='Toma de Muestra')),
            ],
            options={
                'verbose_name': 'Audio Toma de Muestra',
                'verbose_name_plural': 'Audios Toma de Muestra',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
