# Generated by Django 5.0.6 on 2026-04-01 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_toma_muestra_cubiculo_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmodulos',
            name='alerta_consumo_80_enviada',
            field=models.BooleanField(default=False, help_text='Se resetea automáticamente al inicio de cada mes.', verbose_name='Alerta 80% enviada'),
        ),
        migrations.AddField(
            model_name='configuracionmodulos',
            name='alerta_consumo_90_enviada',
            field=models.BooleanField(default=False, verbose_name='Alerta 90% enviada'),
        ),
        migrations.AddField(
            model_name='configuracionmodulos',
            name='limite_mensual_tokens_ia',
            field=models.PositiveIntegerField(default=50000, help_text='Tokens mensuales contratados cuando el lab usa la API Key maestra de PRISLAB.', verbose_name='Límite Mensual de Tokens IA'),
        ),
        migrations.AddField(
            model_name='configuracionmodulos',
            name='modo_ia',
            field=models.CharField(choices=[('APRENDIZAJE', '🧠 Aprendizaje — IA activa para poblar la base de reglas locales'), ('PRODUCCION', '🚀 Producción — IA completa con caché de reglas activo'), ('AHORRO_EXTREMO', '💡 Ahorro Extremo — Solo RAG local y checklist. Sin IA generativa')], default='PRODUCCION', help_text='Controla el nivel de uso de la API de Gemini.', max_length=20, verbose_name='Modo de Consumo de IA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='byok_gemini_api_key_enc',
            field=models.TextField(blank=True, help_text='Clave API de Google Gemini propia del laboratorio, cifrada con Fernet. Si está configurada, los costos de IA los asume directamente el cliente. Si vacía, se usa la MASTER_API_KEY de PRISLAB y se descuenta de la cuota contratada.', null=True, verbose_name='API Key Gemini (cifrada)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='drive_client_config_enc',
            field=models.TextField(blank=True, help_text='JSON de Service Account de Google Drive del laboratorio, cifrado con Fernet.', null=True, verbose_name='Drive Config (JSON cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='ID de la carpeta raíz en Google Drive donde se guardarán audios, PDFs y respaldos.', max_length=200, null=True, verbose_name='Google Drive Folder ID'),
        ),
        migrations.CreateModel(
            name='ReglaLocalIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('CHECKLIST_TOMA', 'Checklist Toma de Muestra'), ('DELTA_CHECK', 'Delta Check / Alerta de Resultado'), ('QC_WESTGARD', 'Control de Calidad Westgard'), ('DIAGNOSTICO_SUGERIDO', 'Diagnóstico Sugerido'), ('CROSS_SELLING', 'Venta Cruzada / Cross-selling'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Ámbito de la Regla')),
                ('clave', models.CharField(db_index=True, help_text="Identificador canónico para matchear esta regla, p. ej. 'CHECKLIST:AYUNO:GLUCOSA_EN_AYUNO' o 'DELTA:GLUCOSA:>500'. Se normaliza a lowercase sin tildes.", max_length=255, verbose_name='Clave de Búsqueda')),
                ('contexto_original', models.TextField(help_text='Texto / transcripción que originó esta regla.', verbose_name='Contexto Original')),
                ('respuesta_ia', models.TextField(help_text='Texto que PRIS-IA generó y que el QFB aprobó.', verbose_name='Respuesta IA Original')),
                ('respuesta_local', models.TextField(blank=True, help_text='Si el QFB ajustó la respuesta, se guarda aquí. Tiene prioridad.', verbose_name='Respuesta Local (Override del QFB)')),
                ('estado', models.CharField(choices=[('PROPUESTA', '⏳ Propuesta — Pendiente de revisión QFB'), ('APROBADA', '✅ Aprobada — Activa en producción'), ('RECHAZADA', '❌ Rechazada — No usar'), ('OBSOLETA', '🗄️ Obsoleta — Reemplazada por versión más nueva')], default='PROPUESTA', max_length=15, verbose_name='Estado')),
                ('confianza', models.DecimalField(decimal_places=2, default=0.8, help_text='Similarity score mínimo para aplicar esta regla automáticamente (0.0–1.0).', max_digits=4, verbose_name='Umbral de Confianza')),
                ('veces_usada', models.PositiveIntegerField(default=0, verbose_name='Veces usada en producción')),
                ('tokens_ahorrados', models.PositiveIntegerField(default=0, help_text='Acumulado de tokens que se habrían gastado sin esta regla.', verbose_name='Tokens Ahorrados')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por (QFB)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_locales_ia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Regla Local IA',
                'verbose_name_plural': 'Reglas Locales IA',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['empresa', 'ambito', 'estado'], name='ix_regla_ia_empresa_ambito')],
                'unique_together': {('empresa', 'ambito', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='UsoRecursosIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('tipo_proceso', models.CharField(choices=[('NLP_TOMA', 'NLP Checklist — Toma de Muestra'), ('RESUMEN_CLINICO', 'Resumen Clínico (Dictado / SOAP)'), ('RAG_CONSULTA', 'RAG — Consulta de Manuales'), ('OCR_DOCUMENTO', 'OCR — Lectura de Documento'), ('MARKETING_IA', 'IA Marketing / Campañas'), ('WORKLIST_SUGERENCIA', 'Sugerencia Worklist / Delta Check'), ('QC_ANALISIS', 'Análisis QC / Westgard'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Tipo de Proceso')),
                ('tokens_entrada', models.PositiveIntegerField(default=0, verbose_name='Tokens de Entrada')),
                ('tokens_salida', models.PositiveIntegerField(default=0, verbose_name='Tokens de Salida')),
                ('tokens_total', models.PositiveIntegerField(default=0, help_text='Suma entrada + salida', verbose_name='Tokens Totales')),
                ('fuente_key', models.CharField(choices=[('BYOK', 'BYOK — API Key propia del laboratorio'), ('MASTER', 'MASTER — API Key compartida de PRISLAB'), ('LOCAL', 'LOCAL — Respuesta de caché / regla local (sin costo)')], default='MASTER', max_length=10, verbose_name='Fuente de API Key')),
                ('modelo_usado', models.CharField(blank=True, default='', max_length=60, verbose_name='Modelo Gemini usado')),
                ('latencia_ms', models.PositiveIntegerField(default=0, verbose_name='Latencia (ms)')),
                ('usuario_id', models.IntegerField(blank=True, null=True, verbose_name='ID Usuario que disparó la llamada')),
                ('referencia', models.CharField(blank=True, default='', max_length=200, verbose_name='Referencia (ID Orden / Estudio / etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp exacto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_recursos_ia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Uso de Recursos IA',
                'verbose_name_plural': 'Uso de Recursos IA',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa', 'fecha'], name='ix_uso_ia_empresa_fecha'), models.Index(fields=['empresa', 'tipo_proceso'], name='ix_uso_ia_proceso')],
            },
        ),
    ]
