# Generated by Django 5.0.6 on 2026-04-01 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_ia_governance_byok_drive_cache'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentocapacitacion',
            name='core_docume_empresa_16fe7f_idx',
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='cedula_validador',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cédula profesional del validador'),
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='chunks_rag',
            field=models.PositiveIntegerField(default=0, help_text='Número de chunks vectoriales creados en la base RAG.', verbose_name='Fragmentos indexados'),
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='error_rag',
            field=models.TextField(blank=True, verbose_name='Detalle de error RAG'),
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='estado_rag',
            field=models.CharField(choices=[('SUBIDO', '🔴 Subido — pendiente de indexar'), ('PROCESANDO', '🟡 Procesando — extrayendo vectores'), ('ENTRENADO', '🟢 Entrenado — IA puede citar este documento'), ('ERROR', '❌ Error — revisar log')], db_index=True, default='SUBIDO', max_length=20, verbose_name='Estado de Entrenamiento IA'),
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='modulo_relacionado',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio Clínico'), ('FARMACIA', 'Farmacia'), ('CONSULTORIO', 'Consultorio Médico'), ('CALIDAD', 'Control de Calidad / ISO 15189'), ('GENERAL', 'General / Todos los módulos')], db_index=True, default='GENERAL', max_length=20, verbose_name='Módulo relacionado'),
        ),
        migrations.AddField(
            model_name='documentocapacitacion',
            name='validado_por_nombre',
            field=models.CharField(blank=True, default='Q.B. Giselle Margarita López Gutiérrez', max_length=200, verbose_name='Responsable sanitaria (validadora)'),
        ),
        migrations.AlterField(
            model_name='documentocapacitacion',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AlterField(
            model_name='documentocapacitacion',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual operativo'), ('POLITICA', 'Política interna'), ('PROCESO', 'Procedimiento'), ('NORMATIVA', 'Normativa / NOM'), ('OTRO', 'Otro')], default='MANUAL', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AddIndex(
            model_name='documentocapacitacion',
            index=models.Index(fields=['empresa', 'tipo', 'activo', 'estado_rag'], name='core_docume_empresa_357aca_idx'),
        ),
    ]
