# Generated by Django 5.0.6 on 2026-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_rag_fields_to_documentocapacitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='responsable_sanitaria_cedula',
            field=models.CharField(blank=True, default='', help_text='Cédula profesional del Responsable Sanitario registrada ante SEP/COFEPRIS.', max_length=50, verbose_name='Cédula Prof. Responsable'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_sanitaria_cofepris',
            field=models.CharField(blank=True, default='', help_text='Número de registro COFEPRIS del Responsable Sanitario (si aplica).', max_length=100, verbose_name='Registro COFEPRIS'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_sanitaria_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre completo con título profesional (ej. Q.B. Nombre Apellido). Aparece en todos los reportes.', max_length=200, verbose_name='Nombre Responsable Sanitario'),
        ),
    ]
