# Generated by Django 5.0.6 on 2026-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_responsable_sanitaria_to_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='seccionlaboratorio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='seccionlaboratorio',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='seccionlaboratorio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
