# Generated by Django 5.0.6 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auditoria_model_base_catalogo_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cuántas unidades de venta contiene 1 unidad de compra. Ej: 30 tabletas/caja', max_digits=10, null=True, verbose_name='Factor de Conversión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_fraccion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio unitario al menudeo (tableta, mL). Si es None se calcula como precio_publico / factor_conversion.', max_digits=10, null=True, verbose_name='Precio de Venta por Fracción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_receta',
            field=models.BooleanField(db_index=True, default=False, help_text='Activa validación obligatoria para Fracciones I, II, III (controlados) y cualquier medicamento que requiera prescripción. Cubre casos más allá de es_antibiotico.', verbose_name='Requiere Receta Médica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_compra',
            field=models.CharField(blank=True, help_text='Ej: Caja, Frasco, Ampolleta', max_length=50, null=True, verbose_name='Unidad de Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(blank=True, help_text='Ej: Tableta, mL, Blíster', max_length=50, null=True, verbose_name='Unidad de Venta al Menudeo'),
        ),
        migrations.AddField(
            model_name='receta',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Indicaciones especiales, observaciones de dispensación, notas del farmacéutico o instrucciones de uso especiales.', null=True, verbose_name='Información Adicional'),
        ),
        migrations.AddField(
            model_name='receta',
            name='numero_receta_externo',
            field=models.CharField(blank=True, help_text='Folio impreso en el talonario del médico. Distinto al folio_receta que genera PRISLAB automáticamente. Permite vincular el expediente digital con el papel físico.', max_length=100, null=True, verbose_name='Número de Receta (documento médico)'),
        ),
    ]
