# Generated by Django 5.0.6 on 2026-04-01 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_farmacia_sprint2_receta_fraccionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='clave_hoja_trabajo',
            field=models.CharField(blank=True, help_text='Dejar en blanco para no imprimir en hoja de trabajo del analizador', max_length=16, null=True, verbose_name='Clave Hoja de Trabajo'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_desactivados', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='es_exento_iva',
            field=models.BooleanField(default=False, verbose_name='¿Exento de IVA?'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, help_text='Se llena automáticamente al hacer Soft Delete', null=True, verbose_name='Fecha de Desactivación'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='imprime_en_negritas',
            field=models.IntegerField(choices=[(0, 'No imprimir'), (1, 'Imprimir solo cuando se vende individual'), (2, 'Imprimir solo cuando es parte de un perfil'), (3, 'Imprimir siempre')], default=0, verbose_name='¿Imprimir en Negritas?'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='imprimir_metodo',
            field=models.IntegerField(choices=[(0, 'No imprimir'), (1, 'Imprimir solo cuando se vende individual'), (2, 'Imprimir solo cuando es parte de un perfil'), (3, 'Imprimir siempre')], default=3, verbose_name='Imprimir Método en Resultado'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='indicaciones',
            field=models.TextField(blank=True, help_text='Instrucciones pre-analíticas (ej: ayuno 8h, no tomar medicamentos)', null=True, verbose_name='Indicaciones al Paciente'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='motivo_desactivacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo de Desactivación'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas (visibles en reporte)'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Solo visible en sistema. Nunca aparece en reportes al paciente.', null=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='permite_venta_directa',
            field=models.BooleanField(default=True, verbose_name='¿Permitir Venta Individual?'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='referencia_texto',
            field=models.TextField(blank=True, help_text="Usar cuando tipo_referencia=TEXTO_LIBRE. Ej: 'Negativo' o tabla libre.", null=True, verbose_name='Valor de Normalidad (Texto)'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='sexo',
            field=models.CharField(choices=[('I', 'Indistinto'), ('M', 'Masculino'), ('F', 'Femenino')], default='I', help_text='Filtro de género para el rango de referencia por defecto', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tiempo_proceso_dias',
            field=models.IntegerField(default=0, verbose_name='Días de Proceso'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tiempo_proceso_horas',
            field=models.IntegerField(default=0, verbose_name='Horas de Proceso'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tiempo_proceso_minutos',
            field=models.IntegerField(default=0, verbose_name='Minutos de Proceso'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tipo_referencia',
            field=models.CharField(choices=[('RANGO', 'Rango Numérico (Min-Max)'), ('TEXTO_LIBRE', 'Texto Libre (ej: Negativo/Positivo)')], default='RANGO', max_length=20, verbose_name='Tipo de Valor de Normalidad'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='titulo',
            field=models.CharField(blank=True, help_text='Si está vacío se usa el nombre. Permite separar nombre interno de nombre impreso.', max_length=512, null=True, verbose_name='Título (para reporte)'),
        ),
        migrations.AddField(
            model_name='rangoreferencia',
            name='reemplazado_por',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='core.rangoreferencia', verbose_name='Reemplazado por (nueva versión)'),
        ),
        migrations.AddField(
            model_name='rangoreferencia',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión. Cada edición crea una nueva versión incrementada.', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='rangoreferencia',
            name='vigente_desde',
            field=models.DateTimeField(blank=True, default=None, help_text='Fecha en que este rango entró en vigor', null=True, verbose_name='Vigente Desde'),
        ),
        migrations.AddField(
            model_name='rangoreferencia',
            name='vigente_hasta',
            field=models.DateTimeField(blank=True, help_text='null = rango actualmente vigente. Fecha = fue reemplazado por una nueva versión', null=True, verbose_name='Vigente Hasta'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='codigo_interfaz',
            field=models.CharField(blank=True, db_index=True, help_text='ID que envía el equipo automatizado (ASTM/HL7)', max_length=50, null=True, verbose_name='Código de Interfaz'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='codigo_loinc',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Código LOINC'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='decimales_reporte',
            field=models.IntegerField(default=2, help_text='Cantidad de decimales en el PDF final (ej: 2 = 15.50)', verbose_name='Decimales en Reporte'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='equipo_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo Origen'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Factor de Conversión'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='orden_impresion',
            field=models.IntegerField(default=0, help_text='Candado 3: controla el orden exacto de analitos en el reporte impreso', verbose_name='Orden de Impresión'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='requiere_confirmacion_manual',
            field=models.BooleanField(default=False, verbose_name='Requiere Confirmación Manual'),
        ),
    ]
