# Generated by Django 4.2 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Bankguard v1.14: Idempotency Key para MovimientoCaja
    Previene duplicados en retries HTTP/Celery
    """
    
    dependencies = [
        ('core', '0054_venta_inventario_descontado_v113'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='UUID único para evitar duplicados en retries/reconexiones HTTP/Celery',
                max_length=255,
                null=True,
                unique=True,
                verbose_name='Clave de Idempotencia'
            ),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['idempotency_key'], name='mov_caja_idem_idx'),
        ),
    ]
