# Generated by Django 4.2 on 2026-04-03

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):
    """
    Bankguard v1.14 — Niveles 2 y 3
    - PoliticaLimitesCaja (umbrales de riesgo)
    - GastoCajaEndurecido (validación de políticas)
    - CierreDiaConsolidado (hash SHA-256)
    - TicketInvestigacionCaja (workflow de discrepancias)
    """
    
    dependencies = [
        ('core', '0055_movimientocaja_idempotency_v114'),
    ]

    operations = [
        # =========================================================================
        # 1. POLITICA LIMITES CAJA (Nivel 2)
        # =========================================================================
        migrations.CreateModel(
            name='PoliticaLimitesCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_verde', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Gastos ≤ este monto: auto-aprobados', max_digits=10, verbose_name='Límite Zona Verde ($)')),
                ('limite_amarillo', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Gastos entre verde y amarillo: requieren comprobante', max_digits=10, verbose_name='Límite Zona Amarilla ($)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas_caja_creadas', to='core.usuario', verbose_name='Creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politica_caja', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Política de Límites de Caja',
                'verbose_name_plural': 'Políticas de Límites de Caja',
            },
        ),
        
        # =========================================================================
        # 2. GASTO CAJA ENDURECIDO (Nivel 2)
        # =========================================================================
        migrations.CreateModel(
            name='GastoCajaEndurecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('comprobante', models.FileField(blank=True, help_text='Obligatorio para gastos superiores al límite verde', null=True, upload_to='gastos_caja/%Y/%m/', verbose_name='Comprobante (PDF/Foto)')),
                ('autorizado', models.BooleanField(default=False, help_text='Requerido para gastos en Zona Roja (>$500)', verbose_name='Autorizado')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_caja_autorizados', to='core.usuario', verbose_name='Autorizado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_caja_endurecidos', to='core.empresa')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_caja_registrados', to='core.usuario', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto de Caja (Endurecido)',
                'verbose_name_plural': 'Gastos de Caja (Endurecidos)',
                'ordering': ['-fecha_registro'],
            },
        ),
        
        # =========================================================================
        # 3. CIERRE DIA CONSOLIDADO (Nivel 3)
        # =========================================================================
        migrations.CreateModel(
            name='CierreDiaConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de Cierre')),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Ingresos ($)')),
                ('total_egresos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Egresos ($)')),
                ('neto_dia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Neto del Día ($)')),
                ('num_ventas', models.PositiveIntegerField(default=0, verbose_name='Número de Ventas')),
                ('num_devoluciones', models.PositiveIntegerField(default=0, verbose_name='Número de Devoluciones')),
                ('num_gastos', models.PositiveIntegerField(default=0, verbose_name='Número de Gastos')),
                ('hash_integridad', models.CharField(editable=False, help_text='Firma digital del cierre. Cualquier modificación altera este valor.', max_length=64, verbose_name='Hash SHA-256')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_dia', to='core.empresa', verbose_name='Empresa')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_dia_generados', to='core.usuario', verbose_name='Generado por')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_dia', to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Cierre de Día Consolidado',
                'verbose_name_plural': 'Cierres de Día Consolidados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='cierrediaconsolidado',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'fecha'), name='unique_cierre_dia_sucursal'),
        ),
        
        # =========================================================================
        # 4. TICKET INVESTIGACION CAJA (Nivel 3)
        # =========================================================================
        migrations.CreateModel(
            name='TicketInvestigacionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_discrepancia', models.CharField(choices=[('HASH_INVALIDO', 'Hash de Cierre Alterado'), ('PAGO_SIN_MOVIMIENTO', 'Pago sin MovimientoCaja'), ('MOVIMIENTO_SIN_PAGO', 'MovimientoCaja sin Pago'), ('DIFERENCIA_MONTO', 'Diferencia de Monto (Pago vs Movimiento)'), ('Doble_Descuento', 'Posible Doble Descuento Inventario'), ('OTRO', 'Otro / Especificar')], max_length=30, verbose_name='Tipo de Discrepancia')),
                ('descripcion', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Esperado ($)')),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Real ($)')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia ($)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_INVESTIGACION', 'En Investigación'), ('RESUELTO', 'Resuelto'), ('FRAUDE_CONFIRMADO', 'Fraude Confirmado')], default='ABIERTO', max_length=30, verbose_name='Estado')),
                ('resolucion', models.TextField(blank=True, verbose_name='Resolución')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='core.usuario', verbose_name='Asignado a')),
                ('cierre_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.cierrediaconsolidado')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to='core.usuario', verbose_name='Creado por (automático)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_investigacion', to='core.empresa')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resueltos', to='core.usuario', verbose_name='Resuelto por')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_investigacion', to='core.venta')),
            ],
            options={
                'verbose_name': 'Ticket de Investigación Caja',
                'verbose_name_plural': 'Tickets de Investigación Caja',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
