# Generated by Django 5.1.x on 2026-04-03 00:00
"""
Migración 0059 — Arquitectura de Blindaje v2.0
NOM-004-SSA3-2012 · NOM-024-SSA3-2012 · Firma Electrónica Simple

Implementa las 3 capas de blindaje del expediente médico:
1. Capa Inmutabilidad — Blockchain de hashes SHA256
2. Capa Firma Vinculante — PIN-Lock
3. Capa Integración LIMS — Tokens v7.5
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('lims', '0001_initial'),  # Dependencia de LIMS para analitos
        ('core', '0058_resultadoparametro_analito_lims'),
    ]

    operations = [
        # ================================================================
        # 1. CAMPOS ADICIONALES AL MÉDICO (PIN-LAB + Validación Cédula)
        # ================================================================
        migrations.AddField(
            model_name='medico',
            name='lab_validation_pin_hash',
            field=models.CharField(
                blank=True,
                help_text='SHA256 del PIN de validación para firmar notas. NUNCA almacenar el PIN en texto plano.',
                max_length=64,
                verbose_name='Hash del PIN-LAB',
            ),
        ),
        migrations.AddField(
            model_name='medico',
            name='pin_configurado_en',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='PIN Configurado En',
            ),
        ),
        migrations.AddField(
            model_name='medico',
            name='cedula_validada',
            field=models.BooleanField(
                default=False,
                help_text='La cédula ha sido verificada ante COFEPRIS/instancia correspondiente',
                verbose_name='Cédula Profesional Validada',
            ),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_validacion_cedula',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Fecha de Validación de Cédula',
            ),
        ),

        # ================================================================
        # 2. MODELO: ExpedienteNotaSHA (Blockchain de Notas)
        # ================================================================
        migrations.CreateModel(
            name='ExpedienteNotaSHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('snapshot_jsonb', models.JSONField(help_text='Estado completo de la nota en formato JSON', verbose_name='Snapshot JSONB')),
                ('estado_nota', models.CharField(
                    choices=[
                        ('BORRADOR', 'Borrador — Editable'),
                        ('PRELIMINAR', 'Preliminar — Pendiente de firma'),
                        ('SELLADA', 'Sellada — Firmada con PIN'),
                        ('INMUTABLE', 'Inmutable — No modificable'),
                    ],
                    default='BORRADOR',
                    max_length=15,
                    verbose_name='Estado de la Nota',
                )),
                ('hash_sha256', models.CharField(
                    help_text='Hash criptográfico del snapshot',
                    max_length=64,
                    unique=True,
                    verbose_name='Hash SHA256',
                )),
                ('hash_anterior', models.CharField(
                    blank=True,
                    help_text='Hash del registro previo en la cadena',
                    max_length=64,
                    null=True,
                    verbose_name='Hash Anterior',
                )),
                ('cadena_valida', models.BooleanField(
                    default=True,
                    help_text='False si se detecta ruptura en el encadenamiento',
                    verbose_name='Cadena Válida',
                )),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_edicion', models.DateTimeField(auto_now=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('firmado_con_pin', models.BooleanField(default=False, verbose_name='Firmado con PIN')),
                ('pin_hash', models.CharField(
                    blank=True,
                    help_text='SHA256 del PIN usado para firmar (no almacenamos el PIN)',
                    max_length=64,
                    verbose_name='Hash del PIN',
                )),
                ('timestamp_firma', models.DateTimeField(blank=True, null=True)),
                # Relaciones
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='expediente_notas_sha',
                    to='core.empresa',
                    verbose_name='Empresa',
                )),
                ('medico', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='expedientes_generados',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Médico Responsable',
                )),
                ('nota_soap', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='expediente_shas',
                    to='core.notaclinicasoap',
                    verbose_name='Nota SOAP',
                )),
                ('paciente', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='expediente_notas_sha',
                    to='core.paciente',
                    verbose_name='Paciente',
                )),
            ],
            options={
                'verbose_name': 'Expediente Nota SHA (Blockchain)',
                'verbose_name_plural': 'Expedientes Notas SHA (Blockchain)',
                'ordering': ['nota_soap', '-version'],
                'app_label': 'core',
            },
        ),
        migrations.AddIndex(
            model_name='expedientenotasha',
            index=models.Index(fields=['empresa', 'paciente', '-timestamp_creacion'], name='core_exp_sha_emp_pac_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientenotasha',
            index=models.Index(fields=['hash_sha256'], name='core_exp_sha_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientenotasha',
            index=models.Index(fields=['estado_nota', 'firmado_con_pin'], name='core_exp_sha_est_fir_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expedientenotasha',
            unique_together={('nota_soap', 'version')},
        ),

        # ================================================================
        # 3. MODELO: NotaClinicaSellar (PIN-Lock)
        # ================================================================
        migrations.CreateModel(
            name='NotaClinicaSellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sello', models.CharField(
                    choices=[
                        ('EDITABLE', 'Editable — En redacción'),
                        ('PRE_SELLADA', 'Pre-sellada — Pendiente de PIN'),
                        ('SELLADA', 'Sellada — Firmada e inmutable'),
                    ],
                    default='EDITABLE',
                    max_length=15,
                    verbose_name='Estado de Sello',
                )),
                ('folio_unico', models.CharField(
                    blank=True,
                    help_text='Folio generado al momento de sellar',
                    max_length=50,
                    null=True,
                    unique=True,
                    verbose_name='Folio Único de Sello',
                )),
                ('pin_hash', models.CharField(
                    blank=True,
                    help_text='Almacenamos el hash, no el PIN',
                    max_length=64,
                    verbose_name='Hash SHA256 del PIN',
                )),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, verbose_name='Cédula Profesional')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad del Médico')),
                ('timestamp_pre_sellado', models.DateTimeField(blank=True, null=True)),
                ('timestamp_sellado', models.DateTimeField(blank=True, null=True)),
                ('pdf_firmado', models.FileField(
                    blank=True,
                    null=True,
                    upload_to='expedientes/pdf_firmados/%Y/%m/',
                    verbose_name='PDF Firmado',
                )),
                ('hash_pdf', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA256 del PDF')),
                ('qr_verificacion', models.TextField(blank=True, verbose_name='QR de Verificación')),
                ('token_verificacion', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    unique=True,
                )),
                # Relaciones
                ('expediente_sha', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sellos',
                    to='core.expedientenotasha',
                    verbose_name='Expediente SHA de referencia',
                )),
                ('medico_firmante', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='notas_selladas',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Médico Firmante',
                )),
                ('nota_soap', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sello_firma',
                    to='core.notaclinicasoap',
                    verbose_name='Nota SOAP',
                )),
            ],
            options={
                'verbose_name': 'Sello de Nota Clínica (PIN-Lock)',
                'verbose_name_plural': 'Sellos de Notas Clínicas (PIN-Lock)',
                'ordering': ['-timestamp_sellado'],
                'app_label': 'core',
            },
        ),
        migrations.AddIndex(
            model_name='notaclinicasellar',
            index=models.Index(fields=['estado_sello', 'timestamp_sellado'], name='core_sello_est_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='notaclinicasellar',
            index=models.Index(fields=['token_verificacion'], name='core_sello_token_idx'),
        ),
        migrations.AddIndex(
            model_name='notaclinicasellar',
            index=models.Index(fields=['folio_unico'], name='core_sello_folio_idx'),
        ),

        # ================================================================
        # 4. MODELO: ReglaPreparacionAnalito (Validación LIMS)
        # ================================================================
        migrations.CreateModel(
            name='ReglaPreparacionAnalito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiere_ayuno', models.BooleanField(default=False, verbose_name='Requiere Ayuno')),
                ('horas_ayuno', models.PositiveIntegerField(
                    default=8,
                    help_text='Mínimo de horas de ayuno requeridas',
                    verbose_name='Horas de Ayuno',
                )),
                ('requiere_preparacion_especial', models.BooleanField(
                    default=False,
                    verbose_name='Requiere Preparación Especial',
                )),
                ('instrucciones_preparacion', models.TextField(
                    blank=True,
                    help_text='Instrucciones detalladas para el paciente',
                    verbose_name='Instrucciones de Preparación',
                )),
                ('contraindicaciones', models.TextField(
                    blank=True,
                    help_text='Condiciones donde no aplicar (ej: embarazo, diabetes)',
                    verbose_name='Contraindicaciones',
                )),
                ('alerta_medico', models.TextField(
                    blank=True,
                    help_text='Mensaje de alerta al momento de prescribir',
                    verbose_name='Alerta al Médico',
                )),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                # Relación
                ('analito', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='regla_preparacion',
                    to='lims.analito',
                    verbose_name='Analito',
                )),
            ],
            options={
                'verbose_name': 'Regla de Preparación de Analito',
                'verbose_name_plural': 'Reglas de Preparación de Analitos',
                'app_label': 'core',
            },
        ),

        # ================================================================
        # 5. MODELO: OrdenTokenLIMS (Trazabilidad Token → Orden)
        # ================================================================
        migrations.CreateModel(
            name='OrdenTokenLIMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_json', models.JSONField(
                    help_text='Lista de tokens {tipo, codigo} usados',
                    verbose_name='Tokens Utilizados',
                )),
                ('texto_original', models.TextField(
                    help_text='Snapshot del texto donde se detectaron los tokens',
                    verbose_name='Texto Original de la Nota',
                )),
                ('preparacion_validada', models.BooleanField(
                    default=False,
                    verbose_name='Preparación Validada',
                )),
                ('alertas_preparacion', models.JSONField(blank=True, default=list, verbose_name='Alertas de Preparación')),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                # Relaciones
                ('medico_generador', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Médico que Generó',
                )),
                ('nota_soap', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ordenes_token_lims',
                    to='core.notaclinicasoap',
                    verbose_name='Nota SOAP Origen',
                )),
                ('orden_lims', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='orden_token_origen',
                    to='core.ordendeservicio',
                    verbose_name='Orden LIMS Generada',
                )),
            ],
            options={
                'verbose_name': 'Orden Token LIMS v7.5',
                'verbose_name_plural': 'Órdenes Token LIMS v7.5',
                'ordering': ['-timestamp_creacion'],
                'app_label': 'core',
            },
        ),

        # ================================================================
        # 6. MODELO: CatalogoCIE10 (Diagnósticos Codificados)
        # ================================================================
        migrations.CreateModel(
            name='CatalogoCIE10',
            fields=[
                ('codigo', models.CharField(
                    max_length=10,
                    primary_key=True,
                    serialize=False,
                    verbose_name='Código CIE-10',
                )),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('descripcion_larga', models.TextField(blank=True, verbose_name='Descripción Larga')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('capitulo', models.CharField(max_length=10, verbose_name='Capítulo CIE-10')),
                ('es_principal', models.BooleanField(
                    default=False,
                    verbose_name='Puede ser Diagnóstico Principal',
                )),
                ('sexo_restringido', models.CharField(
                    blank=True,
                    choices=[('M', 'Masculino'), ('F', 'Femenino')],
                    max_length=1,
                    verbose_name='Restricción de Sexo',
                )),
                ('edad_minima', models.PositiveIntegerField(
                    blank=True,
                    null=True,
                    verbose_name='Edad Mínima (años)',
                )),
                ('edad_maxima', models.PositiveIntegerField(
                    blank=True,
                    null=True,
                    verbose_name='Edad Máxima (años)',
                )),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catálogo CIE-10',
                'verbose_name_plural': 'Catálogo CIE-10',
                'ordering': ['codigo'],
                'app_label': 'core',
            },
        ),
        migrations.AddIndex(
            model_name='catalogocie10',
            index=models.Index(fields=['codigo', 'activo'], name='core_cie10_cod_act_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogocie10',
            index=models.Index(fields=['categoria', 'activo'], name='core_cie10_cat_act_idx'),
        ),
    ]
