# Generated by Django 5.1.x on 2026-04-03 12:00
"""
Migración 0060 — Reparación de las 3 Grietas Críticas del Blindaje v2.0

1. Serialización Canónica: Ya implementada en código (sort_keys=True, separators=(',', ':'))
2. Anclaje Externo (Hash Raíz Diario): Nuevo modelo HashRaizDiario
3. Evidencia Forense de Firma: Nuevos campos en NotaClinicaSellar
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0059_expediente_blindaje_v20'),
    ]

    operations = [
        # ═══════════════════════════════════════════════════════════════════════════
        # REPARACIÓN GRIETA #2: HashRaizDiario — Anclaje Externo
        # ═══════════════════════════════════════════════════════════════════════════
        migrations.CreateModel(
            name='HashRaizDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes')),
                ('dia', models.PositiveIntegerField(verbose_name='Día')),
                ('hash_raiz', models.CharField(
                    help_text='Hash de todos los hashes del día',
                    max_length=64,
                    unique=True,
                    verbose_name='Hash Raíz SHA256'
                )),
                ('total_notas_selladas', models.PositiveIntegerField(
                    default=0,
                    verbose_name='Notas Selladas'
                )),
                ('total_hashes_acumulados', models.PositiveIntegerField(
                    default=0,
                    verbose_name='Total de Hashes Acumulados'
                )),
                ('email_enviado_a', models.EmailField(
                    blank=True,
                    help_text='Dirección de email externa donde se envió el hash',
                    max_length=254,
                    verbose_name='Email Enviado A'
                )),
                ('timestamp_envio', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Timestamp de Envío'
                )),
                ('email_message_id', models.CharField(
                    blank=True,
                    help_text='ID del email para trazabilidad forense',
                    max_length=255,
                    verbose_name='Message-ID del Email'
                )),
                ('tx_id_blockchain', models.CharField(
                    blank=True,
                    help_text='ID de transacción si se ancla en blockchain público',
                    max_length=255,
                    verbose_name='TX ID Blockchain'
                )),
                ('url_ipfs', models.URLField(
                    blank=True,
                    help_text='Hash IPFS si se publica en IPFS',
                    verbose_name='URL IPFS'
                )),
                ('hash_anterior_dia', models.CharField(
                    blank=True,
                    help_text='Para encadenar días (cadena de bloques de días)',
                    max_length=64,
                    verbose_name='Hash Raíz del Día Anterior'
                )),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_calculo', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Timestamp de Cálculo'
                )),
                ('ip_calculador', models.GenericIPAddressField(
                    blank=True,
                    null=True,
                    verbose_name='IP del Servidor Calculador'
                )),
            ],
            options={
                'verbose_name': 'Hash Raíz Diario (Anclaje)',
                'verbose_name_plural': 'Hashes Raíz Diarios (Anclaje)',
                'ordering': ['-fecha'],
                'app_label': 'core',
            },
        ),
        migrations.AddIndex(
            model_name='hashraizdiario',
            index=models.Index(fields=['fecha', 'hash_raiz'], name='core_hash_raiz_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='hashraizdiario',
            index=models.Index(fields=['año', 'mes'], name='core_hash_raiz_año_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='hashraizdiario',
            index=models.Index(fields=['timestamp_envio'], name='core_hash_raiz_envio_idx'),
        ),

        # ═══════════════════════════════════════════════════════════════════════════
        # REPARACIÓN GRIETA #3: Campos de Evidencia Forense en NotaClinicaSellar
        # ═══════════════════════════════════════════════════════════════════════════
        
        # Origen de red
        migrations.AddField(
            model_name='notaclinicasellar',
            name='ip_origen',
            field=models.GenericIPAddressField(
                blank=True,
                help_text='Dirección IP desde donde se realizó la firma',
                null=True,
                verbose_name='IP de Origen'
            ),
        ),
        migrations.AddField(
            model_name='notaclinicasellar',
            name='user_agent',
            field=models.CharField(
                blank=True,
                help_text='Navegador y sistema operativo del dispositivo',
                max_length=500,
                verbose_name='User Agent'
            ),
        ),
        migrations.AddField(
            model_name='notaclinicasellar',
            name='dispositivo_id',
            field=models.CharField(
                blank=True,
                help_text='Identificador único del dispositivo (si está disponible)',
                max_length=100,
                verbose_name='ID de Dispositivo'
            ),
        ),
        
        # Geolocalización
        migrations.AddField(
            model_name='notaclinicasellar',
            name='ubicacion_latitud',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                verbose_name='Latitud'
            ),
        ),
        migrations.AddField(
            model_name='notaclinicasellar',
            name='ubicacion_longitud',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name='Longitud'
            ),
        ),
        migrations.AddField(
            model_name='notaclinicasellar',
            name='ubicacion_precision',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Precisión de la geolocalización en metros',
                null=True,
                verbose_name='Precisión (metros)'
            ),
        ),
        
        # Información de red adicional
        migrations.AddField(
            model_name='notaclinicasellar',
            name='isp_proveedor',
            field=models.CharField(
                blank=True,
                help_text='Proveedor de servicios de internet detectado',
                max_length=100,
                verbose_name='Proveedor ISP'
            ),
        ),
        migrations.AddField(
            model_name='notaclinicasellar',
            name='pais_detectado',
            field=models.CharField(
                blank=True,
                help_text='Código ISO del país detectado por IP',
                max_length=2,
                verbose_name='País (ISO)'
            ),
        ),
        
        # Nuevo índice forense
        migrations.AddIndex(
            model_name='notaclinicasellar',
            index=models.Index(fields=['ip_origen', 'timestamp_sellado'], name='core_sello_ip_ts_idx'),
        ),
    ]
