# Generated by Django 5.0.6 on 2026-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_usuario_es_auditor_supremo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='diagnostico_principal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Diagnóstico Principal'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='exploracion_fisica',
            field=models.TextField(blank=True, null=True, verbose_name='Exploración Física'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='padecimiento_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Padecimiento Actual'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='plan_tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Plan de Tratamiento'),
        ),
    ]
