# Generated by Django 5.0.6 on 2026-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_consultamedica_diagnostico_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cedula_profesional',
            field=models.CharField(max_length=50, verbose_name='Cédula Profesional'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('empresa', 'cedula_profesional'), name='unique_empresa_cedula_medico'),
        ),
    ]
