# Generated by Django 5.0.6 on 2026-06-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_default_pin_and_disable_emergency_bypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeinterno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_internos', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='mensajeinterno',
            index=models.Index(fields=['empresa', 'remitente', 'destinatario'], name='core_mensaj_empresa_ea03c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeinterno',
            index=models.Index(fields=['empresa', '-fecha'], name='core_mensaj_empresa_67f3db_idx'),
        ),
    ]
