# Generated by Django 5.0.6 on 2026-06-25 10:34

from django.db import migrations


def backfill_empresa(apps, schema_editor):
    MensajeInterno = apps.get_model('core', 'MensajeInterno')
    updated = 0
    for msg in MensajeInterno.objects.filter(empresa__isnull=True).select_related('remitente'):
        if msg.remitente and msg.remitente.empresa:
            msg.empresa = msg.remitente.empresa
            msg.save(update_fields=['empresa'])
            updated += 1
    if updated:
        print(f'  [backfill] {updated} MensajeInterno actualizados con empresa del remitente.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_empresa_fk_mensajeinterno'),
    ]

    operations = [
        migrations.RunPython(backfill_empresa, migrations.RunPython.noop),
    ]
