# Generated by Django 5.0.6 on 2026-07-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_backfill_usuario_sucursal_m2m'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usuario_sucursal',
            new_name='core_usuari_usuario_8f597b_idx',
            old_name='core_usuari_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario_sucursal',
            new_name='core_usuari_sucursa_3f0e2c_idx',
            old_name='core_usuari_sucursa_idx',
        ),
    ]
