# Generated by Django 5.0.6 on 2026-06-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_usuario_permiso_extra_abac'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_MetaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('meta_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta de Ingresos Anuales')),
                ('meta_ordenes', models.IntegerField(default=0, verbose_name='Meta de Órdenes Anuales')),
                ('meta_margen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Meta de Margen (%)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_metas', to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_metas', to='core.sucursal', verbose_name='Sucursal (global si None)')),
            ],
            options={
                'verbose_name': 'Meta Anual',
                'verbose_name_plural': 'Metas Anuales',
                'unique_together': {('empresa', 'sucursal', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='KPI_Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día para el que se calcula el snapshot', verbose_name='Fecha del Snapshot')),
                ('ingresos_total', models.DecimalField(decimal_places=2, default=0, help_text='Total de ventas + órdenes completadas', max_digits=15, verbose_name='Ingresos Totales')),
                ('ingresos_lab', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Lab')),
                ('ingresos_consultorio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Consultorio')),
                ('ingresos_farmacia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Farmacia')),
                ('ordenes_capturadas', models.IntegerField(default=0, verbose_name='Órdenes Capturadas Hoy')),
                ('ordenes_completadas', models.IntegerField(default=0, verbose_name='Órdenes Completadas Hoy')),
                ('tasa_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa Cumplimiento (%)')),
                ('movimientos_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Movimientos de Ingreso')),
                ('movimientos_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Movimientos de Egreso')),
                ('saldo_caja', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo de Caja')),
                ('cuentas_por_cobrar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CxC Pendiente')),
                ('margen_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen Promedio (%)')),
                ('pacientes_nuevos', models.IntegerField(default=0, verbose_name='Pacientes Nuevos')),
                ('pacientes_atendidos', models.IntegerField(default=0, verbose_name='Pacientes Atendidos')),
                ('inventario_bajo_stock', models.IntegerField(default=0, verbose_name='Ítems bajo stock')),
                ('cambios_registrados', models.IntegerField(default=0, verbose_name='Cambios en AuditLog')),
                ('calculado_en', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='core.sucursal', verbose_name='Sucursal (global si None)')),
            ],
            options={
                'verbose_name': 'KPI Snapshot',
                'verbose_name_plural': 'KPI Snapshots',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', '-fecha'], name='core_kpi_sn_empresa_e8d1ef_idx'), models.Index(fields=['empresa', 'sucursal', '-fecha'], name='core_kpi_sn_empresa_1ee3af_idx')],
                'unique_together': {('empresa', 'sucursal', 'fecha')},
            },
        ),
    ]
