# Generated by Django 5.0.6 on 2026-06-29 23:30 (renumbered to 0085 to avoid collision with 0084_rename)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_rename_core_usuari_usuario_idx_core_usuari_usuario_8f597b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Permiso_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_key', models.CharField(help_text="Ej: 'caja:cancelar_venta', 'lab:validar_resultados', 'consultorio:ver_expediente'", max_length=100, verbose_name='Clave de Permiso')),
                ('tipo_override', models.CharField(choices=[('GRANT', 'Otorgar permiso'), ('REVOKE', 'Revocar permiso')], default='GRANT', max_length=10, verbose_name='Tipo de Override')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Después de esta fecha, el override expira automáticamente.', null=True, verbose_name='Fecha de Vencimiento')),
                ('razon_negocio', models.TextField(help_text='Por qué se otorgó/revocó este permiso. Requerido para auditoría.', verbose_name='Razón de Negocio')),
            ],
            options={
                'verbose_name': 'Permiso Extra (ABAC)',
                'verbose_name_plural': 'Permisos Extra (ABAC)',
            },
        ),
        migrations.AddField(
            model_name='usuario_permiso_extra',
            name='otorgado_por',
            field=models.ForeignKey(help_text='Usuario que creó este override (debe ser ADMIN o SUPERADMIN).', on_delete=django.db.models.deletion.PROTECT, related_name='permisos_otorgados', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por'),
        ),
        migrations.AddField(
            model_name='usuario_permiso_extra',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Si se establece, el override solo aplica en esta sucursal. Vacío = todas las sucursales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario_extra', to='core.sucursal', verbose_name='Sucursal (opcional)'),
        ),
        migrations.AddField(
            model_name='usuario_permiso_extra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_extra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario_permiso_extra',
            index=models.Index(fields=['usuario', 'tipo_override'], name='core_usuari_usuario_6af74d_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario_permiso_extra',
            index=models.Index(fields=['sucursal', 'fecha_vencimiento'], name='core_usuari_sucursa_849be5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuario_permiso_extra',
            unique_together={('usuario', 'permiso_key', 'sucursal')},
        ),
    ]
