# Generated by Django 5.1.15 on 2026-07-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_usuario_sucursal_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='equivalencias_comerciales',
            field=models.TextField(blank=True, default='', help_text='Patentes, marcas o nombres alternativos separados por coma. Se usan para búsqueda equivalente; validar la composición antes de capturarla.', verbose_name='Equivalencias comerciales / nombres alternativos'),
        ),
    ]
