# Generated by Django 5.0.6 on 2026-06-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_rename_core_usuari_usuario_idx_core_usuari_usuario_8f597b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerechoOlvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitud Recibida'), ('EN_PROCESO', 'En Proceso de Evaluación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADO', max_length=20, verbose_name='Estado de Solicitud')),
                ('razon', models.TextField(verbose_name='Razón de Solicitud')),
                ('datos_a_eliminar', models.TextField(help_text='Descripción de qué datos desea eliminar', verbose_name='Datos Específicos a Eliminar')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('notas_procesamiento', models.TextField(blank=True, verbose_name='Notas de Procesamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_derecho_olvido', to='core.paciente', verbose_name='Paciente')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derechos_olvido_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Derecho al Olvido',
                'verbose_name_plural': 'Derechos al Olvido',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(help_text='Cédula QFB expedida por Secretaría de Educación', max_length=20, unique=True, verbose_name='Cédula Profesional')),
                ('numero_registro_cofepris', models.CharField(blank=True, help_text='Opcional: número de registro ante COFEPRIS', max_length=50, null=True, verbose_name='Número de Registro COFEPRIS')),
                ('fecha_vigencia_inicio', models.DateField(verbose_name='Vigencia Inicio')),
                ('fecha_vigencia_fin', models.DateField(verbose_name='Vigencia Fin')),
                ('certificado_digital', models.FileField(blank=True, help_text='.pfx o .pem para firma digital', null=True, upload_to='certificados_cofepris/', verbose_name='Certificado Digital')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_sanitarios', to='core.empresa', verbose_name='Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_sanitario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Responsable Sanitario',
                'verbose_name_plural': 'Responsables Sanitarios',
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLINICO', 'Datos Clínicos (Historia, Diagnósticos, Tratamientos)'), ('CONTACTO', 'Datos de Contacto (Telefono, Email, SMS)'), ('MARKETING', 'Datos para Marketing/Campañas'), ('INVESTIGACION', 'Datos para Investigación Médica')], max_length=50, verbose_name='Tipo de Consentimiento')),
                ('otorgado', models.BooleanField(default=True, help_text='True = consentimiento dado; False = revocado', verbose_name='Otorgado')),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Otorgamiento')),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revocación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Registro')),
                ('documento_consentimiento', models.FileField(blank=True, help_text='PDF firmado del consentimiento', null=True, upload_to='consentimientos_lgpd/', verbose_name='Documento de Consentimiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_lgpd', to='core.paciente', verbose_name='Paciente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Consentimiento LGPD',
                'verbose_name_plural': 'Consentimientos LGPD',
                'unique_together': {('paciente', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAccesoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_datos', models.CharField(help_text="Ej: 'historia_clinica', 'expediente', 'resultados_lab'", max_length=100, verbose_name='Tipo de Datos Accedidos')),
                ('accion', models.CharField(choices=[('READ', 'Lectura'), ('DOWNLOAD', 'Descarga'), ('EXPORT', 'Exportación')], default='READ', max_length=20, verbose_name='Acción')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Acceso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Acceso')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_datos', to='core.paciente', verbose_name='Paciente Accedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_datos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso a Datos Personales',
                'verbose_name_plural': 'Accesos a Datos Personales',
                'indexes': [models.Index(fields=['paciente', 'fecha_acceso'], name='core_regist_pacient_8594f5_idx'), models.Index(fields=['usuario', 'fecha_acceso'], name='core_regist_usuario_32862e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FirmaDigitalResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_referencia', models.CharField(help_text="Ej: 'OrdenDeServicio', 'ResultadoParametro'", max_length=50, verbose_name='Modelo Referencia')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID del Objeto')),
                ('hash_contenido', models.CharField(help_text='Hash del PDF/contenido firmado', max_length=512, verbose_name='Hash SHA-256 del Contenido')),
                ('firma_hexadecimal', models.TextField(help_text='Firma digital en formato hexadecimal', verbose_name='Firma (Hexadecimal)')),
                ('certificado_usado', models.TextField(blank=True, help_text='Serialización del certificado digital usado', verbose_name='Certificado Usado')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Firma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Firma')),
                ('verificada', models.BooleanField(default=False, help_text='True si la firma fue verificada mediante certificado', verbose_name='Firma Verificada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_digitales', to='core.paciente', verbose_name='Paciente')),
                ('responsable_sanitario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_resultados', to='core.responsablesanitario', verbose_name='Responsable Sanitario')),
            ],
            options={
                'verbose_name': 'Firma Digital',
                'verbose_name_plural': 'Firmas Digitales',
                'indexes': [models.Index(fields=['paciente', 'fecha_firma'], name='core_firmad_pacient_7c9070_idx'), models.Index(fields=['responsable_sanitario', 'fecha_firma'], name='core_firmad_respons_496fb6_idx')],
            },
        ),
    ]
