# Generated by Django 5.1.15 on 2026-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_producto_equivalencias_comerciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='inventario_modo_adaptacion',
            field=models.BooleanField(default=True, help_text='Permite operar con trazabilidad administrativa incompleta durante la migración. Los faltantes quedan registrados por lote; al desactivarlo se exigirá la trazabilidad completa.', verbose_name='Inventario en modo adaptación'),
        ),
    ]
