# Generated by Django 5.1.15 on 2026-07-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_empresa_inventario_modo_adaptacion'),
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoparametro',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo que produjo el resultado; determina la receta de consumo específica cuando existe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_parametro', to='laboratorio.equipo', verbose_name='Equipo / Analizador'),
        ),
    ]
