# Generated by Django 5.0.6 on 2026-07-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_usuario_permiso_extra_abac'),
        ('core', '0087_empresa_iso15189'),
    ]

    operations = [
    ]
