# Generated by Django 5.1.15 on 2026-07-25 21:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_gasto_sucursal(apps, schema_editor):
    GastoCaja = apps.get_model('core', 'GastoCaja')
    Usuario = apps.get_model('core', 'Usuario')
    for gasto in GastoCaja.objects.filter(sucursal__isnull=True).only('id', 'usuario_id'):
        sucursal_id = (
            Usuario.objects.filter(pk=gasto.usuario_id)
            .values_list('sucursales__id', flat=True)
            .first()
        )
        if sucursal_id:
            GastoCaja.objects.filter(pk=gasto.pk).update(sucursal_id=sucursal_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_configuracionmodulos_pin_precio_neto_4_digitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se realizó el gasto. Los registros históricos pueden quedar sin asignar.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_vales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto en Vales'),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='monto_vales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vales / Convenio'),
        ),
        migrations.RunPython(backfill_gasto_sucursal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('SPEI', 'Transferencia (SPEI)'), ('SANTANDER', 'Banco Santander'), ('BBVA', 'Banco BBVA'), ('BANAMEX', 'Banco Banamex'), ('OXXO', 'OXXO / 7-24'), ('TIENDA', 'Chedraui / Walmart / Ahorro'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('VALES', 'Vales / Convenio')], max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['empresa', 'sucursal', '-fecha'], name='gastocaja_emp_suc_fecha_idx'),
        ),
    ]
