# Generated by Django 5.1 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0094_configuracionmodulos_pin_cancelacion_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Administrador'),
                    ('DIRECTOR', 'Director General / Dueño'),
                    ('CAJERO', 'Cajero'),
                    ('FARMACIA', 'Administrador de Farmacia'),
                    ('MEDICO', 'Médico'),
                    ('QUIMICO', 'Químico'),
                    ('RECEPCION', 'Recepción'),
                    ('GERENTE', 'Gerente'),
                ],
                default='CAJERO',
                max_length=50,
                verbose_name='Rol de Usuario',
            ),
        ),
    ]
