# Generated by Django 5.1.15 on 2026-07-28 19:41

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_usuario_rol_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviomaquila',
            name='archivo_resultado',
            field=models.FileField(blank=True, null=True, upload_to='laboratorio/maquila_resultados/', validators=[core.validators.validate_document_upload]),
        ),
        migrations.AddField(
            model_name='enviomaquila',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida — pendiente de captura'), ('CANCELADA', 'Cancelada')], default='ENVIADA', max_length=12),
        ),
        migrations.AddField(
            model_name='enviomaquila',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviomaquila',
            name='notas_recepcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviomaquila',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquilas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('EN_PROCESO', 'En Proceso'), ('EN_MAQUILA', 'En Maquila Externa'), ('RESULTADOS_LISTOS', 'Resultados Listos'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=20, verbose_name='Estado'),
        ),
    ]
