# Generated by Django 5.1.15 on 2026-07-28 21:43

import core.models.base
import core.utils.paths
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_enviomaquila_archivo_resultado_enviomaquila_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeservicio',
            name='archivo_resultado',
            field=models.FileField(blank=True, help_text='PDF final con resultados de laboratorio (se almacena en Google Drive)', null=True, storage=core.models.base.get_google_drive_storage, upload_to=core.utils.paths.generar_ruta_drive_laboratorio, validators=[core.validators.validate_document_upload], verbose_name='PDF de Resultados'),
        ),
    ]
