# Generated by Django 5.1.15 on 2026-07-30 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_hash_farmacia_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientenotasha',
            name='timestamp_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
