# Generated by Django 5.1.15 on 2026-07-30 03:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_expedientenotasha_timestamp_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciaasistencia',
            name='documento_soporte',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/', validators=[core.validators.validate_document_upload], verbose_name='Documento de soporte'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='clabe_interbancaria',
            field=models.CharField(blank=True, default='', help_text='Obligatoria únicamente cuando el método de pago es SPEI.', max_length=20, null=True, verbose_name='CLABE para SPEI'),
        ),
    ]
