# Generated by Django 5.1.15 on 2026-07-30 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_incidenciaasistencia_documento_soporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambiosconsulta',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
