# Generated by Django 5.1.15 on 2026-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_historialcambiosconsulta_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Opcional. Si se captura, debe ser único dentro de la empresa.', max_length=100, null=True, verbose_name='Código de Barras / VIN'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False), models.Q(('codigo_barras', ''), _negated=True)), fields=('empresa', 'codigo_barras'), name='producto_empresa_codigo_barras_unico_no_vacio'),
        ),
    ]
