# Generated by Django 5.1.15 on 2026-08-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_scope_hashraizdiario_by_empresa'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hashraizdiario',
            name='core_hashra_fecha_8da07a_idx',
        ),
        migrations.RenameIndex(
            model_name='hashraizdiario',
            new_name='core_hashra_empresa_0b5687_idx',
            old_name='core_hash_empresa_fecha_idx',
        ),
    ]
