# Generated by Django 4.2 on 2026-01-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador del kiosco (ej: "Kiosco Recepción 1")', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del dispositivo (para identificación)', null=True)),
                ('mac_address', models.CharField(blank=True, help_text='Dirección MAC del dispositivo', max_length=17, null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del kiosco (ej: "Sala de Espera Principal")', max_length=255, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el kiosco está activo y disponible')),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que el kiosco se conectó al sistema', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('intervalo_polling', models.IntegerField(default=2, help_text='Intervalo de polling en segundos (cuánto tiempo espera entre consultas)')),
            ],
            options={
                'verbose_name': 'Kiosco',
                'verbose_name_plural': 'Kioscos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VerificacionKiosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado por Paciente'), ('RECHAZADO', 'Rechazado por Paciente'), ('EXPIRADO', 'Expirado (sin respuesta)')], default='PENDIENTE', help_text='Estado actual de la verificación', max_length=20)),
                ('datos_mostrar', models.JSONField(default=dict, help_text='Datos que se mostrarán al paciente en el kiosco (nombre, estudios, etc.)')),
                ('datos_confirmados', models.JSONField(blank=True, default=dict, help_text='Datos confirmados por el paciente (si hay cambios)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que el paciente confirmó', null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha y hora en que expira la verificación (si no se confirma)', null=True)),
                ('kiosco', models.ForeignKey(blank=True, help_text='Kiosco donde se mostrará la verificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones', to='iot.kiosco')),
                ('orden', models.ForeignKey(help_text='Orden de laboratorio asociada', on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_kiosco', to='laboratorio.orden')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que envió la verificación al kiosco', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_kiosco_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Kiosco',
                'verbose_name_plural': 'Verificaciones de Kiosco',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
