# Generated by Django 5.0.6 on 2026-04-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_consentimiento_marketing_y_orden_opcional'),
        ('iot', '0002_blindaje_hl7_admin_worm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccionhl7',
            options={'ordering': ['-creado'], 'verbose_name': 'Transacci?n HL7 (idempotencia)', 'verbose_name_plural': 'Transacciones HL7 (idempotencia)'},
        ),
        migrations.AlterField(
            model_name='transaccionhl7',
            name='hash_mensaje',
            field=models.CharField(db_index=True, help_text='SHA-256 hex del mensaje can?nico (orden + analito + valor + IP).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='verificacionkiosco',
            name='orden',
            field=models.ForeignKey(help_text='Orden de servicio LIMS (core) asociada', on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_kiosco', to='core.ordendeservicio'),
        ),
    ]
