# Generated by Django 5.0.6 on 2026-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_conveniopreciolims_and_legacy_lab_drop'),
        ('iot', '0003_alter_transaccionhl7_options_and_more'),
        ('laboratorio', '0015_alter_medicioncontrolinterno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionhl7',
            name='transaccion_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=190),
        ),
        migrations.AddConstraint(
            model_name='transaccionhl7',
            constraint=models.UniqueConstraint(condition=models.Q(('equipo__isnull', False), models.Q(('transaccion_id', ''), _negated=True)), fields=('equipo', 'transaccion_id'), name='unique_hl7_transaccion'),
        ),
    ]
