# Generated by Django 5.0.6 on 2026-06-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_default_pin_and_disable_emergency_bypass'),
        ('iot', '0004_transaccionhl7_equipo_transaccion_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosco',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el kiosco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kioscos', to='core.empresa'),
        ),
    ]
