# Generated by Django 5.1.15 on 2026-08-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_kiosco_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosco',
            name='api_token_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Hash de la credencial exclusiva de este kiosco.', max_length=256),
        ),
    ]
