# Generated by Django 4.2 on 2026-01-25 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la entrada', verbose_name='Fecha')),
                ('contenido_privado', models.TextField(help_text='Contenido del diario (simula cifrado visual en admin)', verbose_name='Contenido Privado')),
                ('sentimiento_ia', models.CharField(blank=True, help_text='Análisis de sentimiento generado por IA', max_length=50, null=True, verbose_name='Sentimiento IA')),
                ('nivel_riesgo', models.CharField(choices=[('VERDE', 'Bienestar/Normal (Privado)'), ('AMARILLO', 'Estrés/Ansiedad (Sugerir contenido)'), ('ROJO_VIDA', 'Riesgo de suicidio/autolesión (ALERTA JONATHAN)'), ('ROJO_VIOLENCIA', 'Violencia doméstica/externa (ALERTA JONATHAN)'), ('ROJO_ACOSO', 'Acoso laboral/sexual (ALERTA JONATHAN)'), ('ROJO_SUSTANCIAS', 'Consumo crítico (ALERTA JONATHAN)')], default='VERDE', help_text='Nivel de riesgo detectado (CRÍTICO: alerta a Jonathan)', max_length=20, verbose_name='Nivel de Riesgo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('alerta_enviada', models.BooleanField(default=False, help_text='Indica si se envió alerta a Jonathan por nivel de riesgo crítico', verbose_name='Alerta Enviada')),
            ],
            options={
                'verbose_name': 'Entrada de Diario Emocional',
                'verbose_name_plural': 'Entradas de Diario Emocional',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecursoCrecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del recurso', max_length=255, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('FINANZAS', 'Finanzas'), ('EMOCIONAL', 'Emocional'), ('SALUD', 'Salud'), ('PROFESIONAL', 'Profesional'), ('RELACIONES', 'Relaciones'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría')),
                ('url_contenido', models.URLField(help_text='URL del video, PDF o artículo', verbose_name='URL del Contenido')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del recurso', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Recurso Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Recurso de Crecimiento',
                'verbose_name_plural': 'Recursos de Crecimiento',
                'ordering': ['categoria', 'titulo'],
            },
        ),
    ]
