# Generated by Django 4.2 on 2026-01-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bienestar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioemocional',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que escribe esta entrada', on_delete=django.db.models.deletion.CASCADE, related_name='entradas_diario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='diarioemocional',
            unique_together={('usuario', 'fecha')},
        ),
    ]
