# Generated by Django 5.0.6 on 2026-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioemocional',
            name='anonimizado',
            field=models.BooleanField(default=False, help_text='Indica si el registro fue anonimizado por retención de datos', verbose_name='Anonimizado (NOM-035)'),
        ),
        migrations.AddField(
            model_name='diarioemocional',
            name='fecha_anonimizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se anonimizó el registro', null=True, verbose_name='Fecha de Anonimización'),
        ),
    ]
