# Generated by Django 4.2 on 2026-01-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único generado automáticamente (formato: 2 letras apellido P + 1 letra apellido M + 1 letra nombre + AAMMDD)', max_length=20, null=True, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_verificado', models.BooleanField(default=False, help_text='Indica si el teléfono del paciente ha sido verificado (requerido para envío de resultados).')),
                ('codigo_verificacion_sms', models.CharField(blank=True, help_text='Código de verificación enviado por SMS.', max_length=6, null=True)),
                ('fecha_verificacion_telefono', models.DateTimeField(blank=True, help_text='Fecha y hora en que se verificó el teléfono.', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
