# Generated by Django 5.0.14 on 2026-01-26 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudioimagen_plantillaestudioimagen_and_more'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAccesoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_identificacion', models.CharField(help_text='CURP o ID', max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='core.paciente')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Acceso al Portal',
                'verbose_name_plural': 'Solicitudes de Acceso al Portal',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('token_verificacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100)),
                ('token_recuperacion_expira', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_sms', models.BooleanField(default=False)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_portal', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Usuario del Portal',
                'verbose_name_plural': 'Usuarios del Portal',
            },
        ),
        migrations.CreateModel(
            name='AccesoExpedientePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('seccion_consultada', models.CharField(help_text='Ej: consultas, laboratorio, recetas, etc.', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('usuario_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_expediente', to='pacientes.usuariopaciente')),
            ],
            options={
                'verbose_name': 'Acceso al Expediente (Portal)',
                'verbose_name_plural': 'Accesos al Expediente (Portal)',
                'ordering': ['-fecha_acceso'],
            },
        ),
    ]
