# Generated by Django 5.0.6 on 2026-04-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0016_orden_paciente_core_y_drop_legacy_paciente'),
        ('pacientes', '0002_solicitudaccesoportal_usuariopaciente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
