# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_configuracion_pin_validacion_laboratorio'),
        ('pacientes', '0003_orden_paciente_core_y_drop_legacy_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaccesoportal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_acceso_portal', to='core.empresa'),
        ),
    ]
