# Generated by Django 4.2 on 2026-01-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estatus', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_SALA', 'En sala'), ('TERMINADA', 'Terminada')], default='PROGRAMADA', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita (Agenda)',
                'verbose_name_plural': 'Citas (Agenda)',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('exploracion_fisica', models.TextField(blank=True, null=True)),
                ('diagnostico_cie10', models.CharField(blank=True, help_text='Código CIE-10 (ej. E11)', max_length=30, null=True)),
                ('diagnostico_texto', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nota médica', max_length=200)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota Médica',
                'verbose_name_plural': 'Notas Médicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Somatometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, help_text='En metros o cm (definir estándar).', max_digits=6, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, help_text='Ej: 120/80', max_length=20, null=True)),
                ('sato2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='somatometria', to='consultorio.consultamedica')),
            ],
            options={
                'verbose_name': 'Somatometría',
                'verbose_name_plural': 'Somatometrías',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
