# Generated by Django 4.2 on 2026-01-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultorio', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notamedica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_medicas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='notamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_medicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_medicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='notamedica',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_medicas', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='consultorio.agendacita'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medicas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_medicas', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_consultorio', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_consultorio', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_consultorio', to='core.sucursal'),
        ),
    ]
