# Generated by Django 5.0.14 on 2026-02-09 21:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_consultorio_isla_independiente'),
        ('core', '0010_consultorio_isla_independiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la caja')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('LIQUIDADA', 'Liquidada')], default='ABIERTA', max_length=15, verbose_name='Estado de la caja')),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Efectivo')),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Tarjeta')),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Transferencia')),
                ('total_en_transito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto cobrado por recepción pendiente de entregar al médico', max_digits=12, verbose_name='Dinero en Tránsito (cobrado por recepción)')),
                ('total_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto ya entregado al médico', max_digits=12, verbose_name='Total Liquidado')),
                ('consultas_cobradas', models.IntegerField(default=0)),
                ('consultas_pendientes', models.IntegerField(default=0)),
                ('notas_cierre', models.TextField(blank=True, verbose_name='Notas de cierre')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_consultorio', to='core.empresa')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_consultorio', to=settings.AUTH_USER_MODEL, verbose_name='Médico titular')),
            ],
            options={
                'verbose_name': 'Caja de Consultorio',
                'verbose_name_plural': 'Cajas de Consultorio',
                'ordering': ['-fecha'],
                'unique_together': {('medico', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='CobroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('CONSULTA', 'Consulta Médica'), ('ULTRASONIDO', 'Ultrasonido'), ('CERTIFICADO', 'Certificado Médico'), ('PROCEDIMIENTO', 'Procedimiento Menor'), ('OTRO', 'Otro Servicio')], default='CONSULTA', max_length=20, verbose_name='Concepto del servicio')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción adicional')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del servicio')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pagado en Efectivo')),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pagado con Tarjeta')),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pagado por Transferencia')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Pago Mixto')], default='EFECTIVO', max_length=15, verbose_name='Método de pago')),
                ('cobrado_por', models.CharField(choices=[('MEDICO', 'Cobrado por el Médico'), ('RECEPCION', 'Cobrado en Recepción')], default='MEDICO', max_length=15, verbose_name='Cobrado por')),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=15)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de aprobación de tarjeta o referencia de transferencia', max_length=100, verbose_name='Referencia/Aprobación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cobro')),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='consultorio.cajaconsultorio', verbose_name='Caja del día')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_consultorio', to='core.consultamedica', verbose_name='Consulta vinculada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_consultorio', to='core.empresa')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_realizados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_consultorio', to='core.paciente')),
                ('usuario_cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_procesados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que procesó el cobro')),
            ],
            options={
                'verbose_name': 'Cobro de Consulta',
                'verbose_name_plural': 'Cobros de Consultorio',
                'ordering': ['-fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='ValeLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_adeudado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto que recepción debe entregar')),
                ('monto_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto ya entregado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de entrega'), ('LIQUIDADO', 'Liquidado (entregado al médico)'), ('PARCIAL', 'Parcialmente liquidado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('fecha_liquidacion', models.DateTimeField(blank=True, null=True)),
                ('folio_vale', models.CharField(max_length=50, unique=True, verbose_name='Folio del vale')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vale_liquidacion', to='consultorio.cobroconsulta', verbose_name='Cobro asociado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_liquidacion', to='core.empresa')),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_procesadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_pendientes', to=settings.AUTH_USER_MODEL, verbose_name='Médico acreedor')),
            ],
            options={
                'verbose_name': 'Vale de Liquidación',
                'verbose_name_plural': 'Vales de Liquidación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
