# Generated by Django 5.0.14 on 2026-02-10 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_cajaconsultorio_cobroconsulta_valeliquidacion'),
        ('core', '0011_add_pin_precio_neto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaSentinel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('MIDDLEWARE', 'Captura Automática (Middleware)'), ('FEEDBACK', 'Reporte del Usuario (Feedback)'), ('MANUAL', 'Registro Manual')], default='MIDDLEWARE', max_length=20, verbose_name='Origen de la incidencia')),
                ('url_afectada', models.URLField(blank=True, max_length=500, verbose_name='URL donde ocurrió el error')),
                ('metodo_http', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP (GET/POST)')),
                ('namespace', models.CharField(blank=True, default='consultorio', max_length=100, verbose_name='Namespace del módulo afectado')),
                ('codigo_http', models.IntegerField(default=500, verbose_name='Código HTTP del error')),
                ('tipo_excepcion', models.CharField(blank=True, max_length=255, verbose_name='Tipo de excepción (class name)')),
                ('traceback_completo', models.TextField(blank=True, verbose_name='Traceback técnico completo')),
                ('datos_request', models.JSONField(blank=True, default=dict, help_text='GET/POST params sin datos sensibles (passwords, tokens)', verbose_name='Datos del request (sanitizados)')),
                ('tag', models.CharField(default='#BUG_CONSULTA', max_length=50, verbose_name='Tag de clasificación')),
                ('descripcion_usuario', models.TextField(blank=True, help_text='Lo que el usuario describió que falló', verbose_name='Descripción en lenguaje natural')),
                ('analisis_ia', models.TextField(blank=True, help_text='Resumen ejecutivo del error para el Director', verbose_name='Análisis generado por Gemini')),
                ('contexto_cursor', models.TextField(blank=True, help_text='Bloque exportable para pegar en Cursor y corregir el bug', verbose_name='Contexto técnico para Cursor')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REPARACION', 'En Reparación'), ('SOLUCIONADO', 'Solucionado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la incidencia')),
                ('severidad', models.CharField(choices=[('CRITICA', 'Crítica (500 / DB Error)'), ('ALTA', 'Alta (404 / Lógica rota)'), ('MEDIA', 'Media (Warning / UX)'), ('BAJA', 'Baja (Cosmético / Informativo)')], default='ALTA', max_length=10, verbose_name='Severidad')),
                ('notas_resolucion', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_sentinel', to='core.empresa')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('usuario_reporta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que experimentó el error')),
            ],
            options={
                'verbose_name': 'Incidencia Sentinel',
                'verbose_name_plural': 'Incidencias Sentinel',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_creacion'], name='consultorio_estado_f25b50_idx'), models.Index(fields=['empresa', 'estado'], name='consultorio_empresa_884a8d_idx'), models.Index(fields=['severidad', '-fecha_creacion'], name='consultorio_severid_51c2f0_idx')],
            },
        ),
    ]
