# Generated by Django 5.0.14 on 2026-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0005_incidenciasentinel'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciasentinel',
            name='contexto_reparacion',
            field=models.JSONField(blank=True, default=dict, help_text='Datos estructurados generados por IA: archivo, línea, código propuesto, instrucciones SSH', verbose_name='Contexto de autocuración (JSON)'),
        ),
        migrations.AlterField(
            model_name='incidenciasentinel',
            name='url_afectada',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL donde ocurrio el error'),
        ),
    ]
