# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0006_incidenciasentinel_contexto_reparacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultamedica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Consulta Médica (LEGACY)', 'verbose_name_plural': 'Consultas Médicas (LEGACY)'},
        ),
        migrations.AlterField(
            model_name='archivoadjuntoconsulta',
            name='archivo',
            field=models.FileField(upload_to='adjuntos_consulta/%Y/%m/', validators=[core.validators.validate_document_upload], verbose_name='Archivo'),
        ),
    ]
