# Generated by Django 5.0.14 on 2026-02-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0008_clinical_data_protection'),
        ('core', '0031_documentocapacitacion_capsulasabiduria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUltrasonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABDOMINAL', 'Ultrasonido Abdominal'), ('OBSTETRICO', 'Ultrasonido Obstétrico'), ('PELVICO', 'Ultrasonido Pélvico'), ('TIROIDES', 'Ultrasonido de Tiroides'), ('RENAL', 'Ultrasonido Renal'), ('CARDIACO', 'Ecocardiograma'), ('PARTES_BLANDAS', 'Partes Blandas'), ('OTRO', 'Otro')], default='ABDOMINAL', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('ENTREGADO', 'Entregado al paciente')], default='BORRADOR', max_length=15)),
                ('semanas_gestacion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semanas de gestación (si aplica)')),
                ('hallazgos', models.TextField(verbose_name='Hallazgos / descripción del estudio')),
                ('conclusion', models.TextField(verbose_name='Conclusión / diagnóstico')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('fecha_estudio', models.DateTimeField(auto_now_add=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_usg', to='core.empresa')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_usg', to='core.medico')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_usg', to='core.ordendeservicio', verbose_name='Orden de servicio vinculada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_usg', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Reporte de Ultrasonido',
                'verbose_name_plural': 'Reportes de Ultrasonido',
                'ordering': ['-fecha_estudio'],
            },
        ),
        migrations.CreateModel(
            name='ImagenUltrasonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ultrasonido/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción de la imagen')),
                ('orden_display', models.PositiveSmallIntegerField(default=1, verbose_name='Orden de visualización')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='consultorio.reporteultrasonido')),
            ],
            options={
                'verbose_name': 'Imagen de Ultrasonido',
                'verbose_name_plural': 'Imágenes de Ultrasonido',
                'ordering': ['reporte', 'orden_display'],
            },
        ),
        migrations.AddIndex(
            model_name='reporteultrasonido',
            index=models.Index(fields=['empresa', 'estado'], name='consultorio_empresa_79642a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteultrasonido',
            index=models.Index(fields=['paciente', '-fecha_estudio'], name='consultorio_pacient_a60c5b_idx'),
        ),
    ]
