# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponmarketing',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cupones/%Y/%m/%d/', validators=[core.validators.validate_image_upload]),
        ),
    ]
