# Generated by Django 5.0.14 on 2026-02-22 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_nomina_periodo_recibo'),
        ('marketing', '0002_alter_cuponmarketing_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('empresa_prospecto', models.CharField(blank=True, max_length=200, verbose_name='Empresa del prospecto')),
                ('origen', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada telefónica'), ('WEB', 'Sitio web / formulario'), ('REFERIDO', 'Referido'), ('VISITA', 'Visita directa'), ('REDES', 'Redes sociales'), ('OTRO', 'Otro')], default='OTRO', max_length=15, verbose_name='Origen del contacto')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo contacto'), ('CONTACTADO', 'Contactado'), ('INTERESADO', 'Interesado'), ('COTIZADO', 'Cotización enviada'), ('GANADO', 'Convertido en paciente'), ('PERDIDO', 'Perdido')], default='NUEVO', max_length=15, verbose_name='Estado')),
                ('servicio_interes', models.CharField(blank=True, max_length=300, verbose_name='Servicio de interés')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor estimado ($)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Próximo contacto')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos_crm', to='core.empresa')),
                ('paciente_convertido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_prospecto', to='core.paciente', verbose_name='Paciente (si fue convertido)')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Prospecto CRM',
                'verbose_name_plural': 'Prospectos CRM',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('VISITA', 'Visita'), ('COTIZACION', 'Cotización'), ('NOTA', 'Nota interna')], default='NOTA', max_length=15, verbose_name='Tipo de contacto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado / respuesta')),
                ('nuevo_estado', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo contacto'), ('CONTACTADO', 'Contactado'), ('INTERESADO', 'Interesado'), ('COTIZADO', 'Cotización enviada'), ('GANADO', 'Convertido en paciente'), ('PERDIDO', 'Perdido')], max_length=15, verbose_name='Cambio de estado (si aplica)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_proximo', models.DateField(blank=True, null=True, verbose_name='Próximo seguimiento')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='marketing.prospectocrm')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Seguimiento CRM',
                'verbose_name_plural': 'Seguimientos CRM',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='prospectocrm',
            index=models.Index(fields=['empresa', 'estado', '-creado'], name='marketing_p_empresa_598914_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectocrm',
            index=models.Index(fields=['asignado_a', '-creado'], name='marketing_p_asignad_6d0a54_idx'),
        ),
    ]
