# Generated by Django 5.0.6 on 2026-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_crm_prospectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanamarketing',
            name='canal_comunicacion',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Notificación Push'), ('otro', 'Otro')], default='whatsapp', max_length=20, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='campanamarketing',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre de la campaña'),
        ),
    ]
