# Generated by Django 5.0.6 on 2026-04-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_backupinmutablelog'),
        ('marketing', '0004_campana_nombre_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='marketing.cuponmarketing')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupon_usos', to='core.empresa')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_marketing_uso', to='core.ordendeservicio')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_marketing_uso', to='core.paciente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_marketing_uso', to='core.venta')),
            ],
            options={
                'verbose_name': 'Uso de cupÃ³n',
                'verbose_name_plural': 'Usos de cupones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuponuso',
            constraint=models.UniqueConstraint(condition=models.Q(('orden__isnull', False)), fields=('cupon', 'paciente', 'orden'), name='marketing_cuponuso_cupon_paciente_orden_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cuponuso',
            constraint=models.UniqueConstraint(condition=models.Q(('venta__isnull', False)), fields=('cupon', 'venta'), name='marketing_cuponuso_cupon_venta_uniq'),
        ),
    ]

