# Generated by Django 5.0.6 on 2026-04-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_tracking_hit_and_consent_prospecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuponuso',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Uso de cupón', 'verbose_name_plural': 'Usos de cupones'},
        ),
        migrations.RenameIndex(
            model_name='marketingtrackinghit',
            new_name='marketing_m_empresa_7f2ed5_idx',
            old_name='marketing_m_trk_emp_fecha',
        ),
        migrations.RenameIndex(
            model_name='marketingtrackinghit',
            new_name='marketing_m_event_k_8e7a13_idx',
            old_name='marketing_m_trk_evt_fecha',
        ),
        migrations.AlterField(
            model_name='marketingtrackinghit',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Parámetros no sensibles acotados (tamaño limitado en vista).'),
        ),
        migrations.AlterField(
            model_name='prospectocrm',
            name='consentimiento_comunicaciones',
            field=models.BooleanField(default=False, help_text='LFPDPPP (México): opt-in explícito para envío de promociones o seguimiento comercial. Sin True, no se deben registrar hits de tracking vinculados a este prospecto.', verbose_name='Consentimiento comunicaciones comerciales'),
        ),
    ]
