# Generated by Django 5.0.14 on 2026-01-26 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_estudioimagen_plantillaestudioimagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('regimen_fiscal', models.CharField(choices=[('612', '612 - Personas Físicas con Actividades Empresariales'), ('616', '616 - Sin obligaciones fiscales'), ('626', '626 - Régimen Simplificado de Confianza'), ('601', '601 - General de Ley Personas Morales')], default='616', max_length=3)),
                ('uso_cfdi_default', models.CharField(choices=[('G03', 'G03 - Gastos en general'), ('D01', 'D01 - Honorarios médicos y gastos hospitalarios'), ('S01', 'S01 - Sin efectos fiscales')], default='D01', max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_facturacion', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Cliente de Facturación',
                'verbose_name_plural': 'Clientes de Facturación',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid_sat', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True)),
                ('folio_interno', models.CharField(max_length=50, unique=True)),
                ('serie', models.CharField(default='A', max_length=10)),
                ('folio', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago')], default='I', max_length=1)),
                ('forma_pago', models.CharField(choices=[('01', '01 - Efectivo'), ('03', '03 - Transferencia'), ('04', '04 - Tarjeta de crédito'), ('28', '28 - Tarjeta de débito')], default='01', max_length=2)),
                ('metodo_pago', models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], default='PUE', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], db_index=True, default='BORRADOR', max_length=20)),
                ('xml_timbrado', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='contabilidad.clientefacturacion')),
                ('orden_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.ordendeservicio')),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura CFDI 4.0',
                'verbose_name_plural': 'Facturas CFDI 4.0',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.IntegerField()),
                ('clave_producto_servicio', models.CharField(default='85121801', max_length=10)),
                ('clave_unidad', models.CharField(default='E48', max_length=10)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('objeto_impuesto', models.CharField(choices=[('01', 'No objeto de impuesto'), ('02', 'Sí objeto de impuesto')], default='02', max_length=2)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='contabilidad.facturacfdi')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
                'ordering': ['factura', 'numero_linea'],
            },
        ),
        migrations.CreateModel(
            name='ImpuestoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRASLADO', 'Traslado'), ('RETENCION', 'Retención')], max_length=10)),
                ('impuesto', models.CharField(choices=[('001', 'ISR'), ('002', 'IVA'), ('003', 'IEPS')], default='002', max_length=3)),
                ('tasa_o_cuota', models.DecimalField(decimal_places=6, default=0.16, max_digits=10)),
                ('tipo_factor', models.CharField(default='Tasa', max_length=10)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='contabilidad.conceptofactura')),
            ],
            options={
                'verbose_name': 'Impuesto de Concepto',
                'verbose_name_plural': 'Impuestos de Conceptos',
            },
        ),
        migrations.AddIndex(
            model_name='facturacfdi',
            index=models.Index(fields=['cliente', 'estado'], name='contabilida_cliente_f748b4_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacfdi',
            index=models.Index(fields=['fecha_emision'], name='contabilida_fecha_e_ba963e_idx'),
        ),
    ]
