# Generated by Django 5.0.6 on 2026-03-31 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefacturacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_facturacion', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='clientefacturacion',
            name='rfc',
            field=models.CharField(db_index=True, max_length=13),
        ),
        migrations.AddConstraint(
            model_name='clientefacturacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'rfc'), name='unique_rfc_por_empresa'),
        ),
    ]
