# Generated by Django 5.0.6 on 2026-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_clientefacturacion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacfdi',
            name='timbrando_en_proceso',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
