# Generated by Django 5.0.6 on 2026-04-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_facturando_timbrado_intento_p16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacfdi',
            name='timbrado_intento_en',
            field=models.DateTimeField(blank=True, help_text='Marca de tiempo al entrar en FACTURANDO; usado por reconciliar_facturas_pendientes.', null=True, verbose_name='Inicio intento timbrado'),
        ),
    ]
