# Generated by Django 5.0.6 on 2026-04-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_facturacfdi_timbrado_intento_en'),
        ('core', '0073_conveniopreciolims_and_legacy_lab_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacfdi',
            name='pago_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_cfdi', to='core.pagoorden', verbose_name='Pago de orden (laboratorio)'),
        ),
        migrations.AddField(
            model_name='facturacfdi',
            name='venta_farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_cfdi', to='core.venta', verbose_name='Venta (farmacia / PDV)'),
        ),
    ]
