# Generated by Django 5.0.6 on 2026-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_facturacfdi_puente_lab_farmacia_cfdi40'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacfdi',
            name='ultimo_error_pac',
            field=models.TextField(blank=True, default='', help_text='Texto devuelto por Facturama/SAT o error interno al timbrar.', verbose_name='Último mensaje del PAC / error'),
        ),
    ]
