# Generated by Django 5.0.6 on 2026-06-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_clientefacturacion_empresa_not_null'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facturacfdi',
            new_name='contabilida_empresa_e9f2ce_idx',
            old_name='contab_empresa_serie_folio_idx',
        ),
    ]
