# Generated by Django 5.0.6 on 2026-06-25 23:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_facturacfdi_empresa_not_null'),
        ('core', '0081_make_mensajeinterno_empresa_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto')], max_length=10)),
                ('naturaleza', models.CharField(choices=[('DEUDOR', 'Deudor'), ('ACREEDOR', 'Acreedor')], default='DEUDOR', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('INGRESOS', 'Ingresos'), ('EGRESOS', 'Egresos'), ('DIARIO', 'Diario'), ('AJUSTE', 'Ajuste'), ('CIERRE', 'Cierre')], default='DIARIO', max_length=10)),
                ('concepto', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Póliza contable',
                'verbose_name_plural': 'Pólizas contables',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('cargo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.cuentacontable')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='contabilidad.poliza')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
            },
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_cuenta_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('empresa', 'folio'), name='unique_folio_poliza_empresa'),
        ),
    ]
