# Generated by Django 5.0.6 on 2026-07-10 01:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_catalogo_cuentas_polizas'),
        ('core', '0084_remove_usuario_sucursal_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(help_text='Nombre o Razón Social del proveedor', max_length=200)),
                ('rfc_proveedor', models.CharField(blank=True, max_length=13)),
                ('folio_factura', models.CharField(blank=True, max_length=50)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Compra / Gasto',
                'verbose_name_plural': 'Compras / Gastos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALARIO', 'Salario base'), ('HONORARIOS', 'Honorarios médicos'), ('COMISIONES', 'Comisiones por venta'), ('OTRO', 'Otro tipo de pago')], default='SALARIO', max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retenciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_nomina', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='core.empresa')),
                ('poliza_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas', to='contabilidad.poliza')),
            ],
            options={
                'verbose_name': 'Nómina / Honorario',
                'verbose_name_plural': 'Nóminas y Honorarios',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
