# Generated by Django 5.1.15 on 2026-09-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_compra_nomina'),
        ('core', '0108_configuracion_pin_validacion_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefacturacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_facturacion', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='facturacfdi',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa emisora del CFDI (denormalizada de cliente.empresa para integridad y performance)', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cfdi', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='core.empresa'),
        ),
    ]
