# Generated by Django 5.0.6 on 2026-06-18 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0076_alter_consultamedica_diagnostico_principal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('autor_externo', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_cursos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Curso de academia',
                'verbose_name_plural': 'Cursos de academia',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='AccesoAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_accesos', to='core.empresa')),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academia_accesos_otorgados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_accesos', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='academia.cursoacademia')),
            ],
            options={
                'verbose_name': 'Acceso a academia',
                'verbose_name_plural': 'Accesos a academia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VideoAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('bunny_video_id', models.CharField(max_length=64)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academia.cursoacademia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_videos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Video de academia',
                'verbose_name_plural': 'Videos de academia',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SesionVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('segundos_acumulados', models.PositiveIntegerField(default=0)),
                ('finalizada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_sesiones', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_sesiones', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='academia.videoacademia')),
            ],
            options={
                'verbose_name': 'Sesion de visualizacion',
                'verbose_name_plural': 'Sesiones de visualizacion',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.AddConstraint(
            model_name='cursoacademia',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='uq_academia_curso_empresa_slug'),
        ),
        migrations.AddConstraint(
            model_name='accesoacademia',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario', 'curso'), name='uq_academia_acceso_empresa_usuario_curso'),
        ),
        migrations.AddConstraint(
            model_name='videoacademia',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='uq_academia_video_curso_orden'),
        ),
        migrations.AddConstraint(
            model_name='videoacademia',
            constraint=models.UniqueConstraint(fields=('curso', 'bunny_video_id'), name='uq_academia_video_curso_bunny'),
        ),
    ]
