# Generated by Django 5.0.6 on 2026-03-31 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
        ('mantenimiento', '0001_cmms_v8_2_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código / Serial del Sensor')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Ubicación')),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Temperatura (°C)'), ('HUMEDAD', 'Humedad Relativa (%)'), ('TEMPERATURA_HUMEDAD', 'Temperatura + Humedad'), ('CO2', 'CO2 (ppm)')], max_length=25, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('temp_min_aceptable', models.DecimalField(decimal_places=1, default=2.0, max_digits=5, verbose_name='Temperatura Mínima Aceptable (°C)')),
                ('temp_max_aceptable', models.DecimalField(decimal_places=1, default=8.0, max_digits=5, verbose_name='Temperatura Máxima Aceptable (°C)')),
                ('hum_min_aceptable', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Humedad Mínima Aceptable (%)')),
                ('hum_max_aceptable', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Humedad Máxima Aceptable (%)')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_iot', to='core.empresa', verbose_name='Empresa')),
                ('expediente', models.ForeignKey(blank=True, help_text='Equipo al que está físicamente instalado este sensor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='mantenimiento.expedienteequipo', verbose_name='Equipo Vinculado')),
            ],
            options={
                'verbose_name': 'Sensor IoT',
                'verbose_name_plural': 'Sensores IoT',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensorIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/Hora Lectura')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura (°C)')),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Humedad Relativa (%)')),
                ('fuera_de_rango', models.BooleanField(db_index=True, default=False, verbose_name='Fuera de Rango')),
                ('origen', models.CharField(choices=[('API', 'API REST (IoT)'), ('MANUAL', 'Captura Manual')], default='API', max_length=10, verbose_name='Origen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_sensor', to='core.empresa', verbose_name='Empresa')),
                ('ticket_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_detonadoras', to='mantenimiento.ticketmantenimientocmms', verbose_name='Ticket Generado por esta Lectura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='mantenimiento.sensoriot', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor IoT',
                'verbose_name_plural': 'Lecturas de Sensores IoT',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoMetrologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CALIBRACION', 'Calibración Metrológica'), ('CALIFICACION_IQ', 'Calificación de Instalación (IQ)'), ('CALIFICACION_OQ', 'Calificación de Operación (OQ)'), ('CALIFICACION_PQ', 'Calificación de Desempeño (PQ)'), ('VERIFICACION', 'Verificación Periódica'), ('MANTENIMIENTO_PREVENTIVO', 'Mantenimiento Preventivo Certificado')], max_length=30, verbose_name='Tipo de Certificado')),
                ('numero_certificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número / Folio del Certificado')),
                ('laboratorio_emisor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratorio / Entidad Emisora')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer (≤30 días)'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado / Sustituido')], default='VIGENTE', max_length=15, verbose_name='Estado')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='metrologia/certificados/', verbose_name='Archivo PDF del Certificado')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alerta_30d_enviada', models.BooleanField(default=False, help_text='Marca automática del cron para evitar alertas duplicadas.', verbose_name='Alerta 30 días enviada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_metrologia', to='core.empresa', verbose_name='Empresa')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='mantenimiento.expedienteequipo', verbose_name='Equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Certificado de Metrología',
                'verbose_name_plural': 'Certificados de Metrología',
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['empresa', 'estado', 'fecha_vencimiento'], name='mantenimien_empresa_4b36d9_idx'), models.Index(fields=['expediente', 'tipo'], name='mantenimien_expedie_64f44f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sensoriot',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='mantenimiento_sensoriot_empresa_codigo_uniq'),
        ),
        migrations.AddIndex(
            model_name='lecturasensoriot',
            index=models.Index(fields=['sensor', '-timestamp'], name='mantenimien_sensor__69b461_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturasensoriot',
            index=models.Index(fields=['empresa', 'fuera_de_rango', '-timestamp'], name='mantenimien_empresa_152e7b_idx'),
        ),
    ]
