# Generated by Django 5.0.6 on 2026-04-02 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
        ('mantenimiento', '0002_sensoriot_lecturasensoriot_certificadometrologia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InCCAInterfaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('input_path', models.CharField(blank=True, default='input', max_length=500, verbose_name='Carpeta INPUT')),
                ('output_path', models.CharField(blank=True, default='output', max_length=500, verbose_name='Carpeta OUTPUT')),
                ('input_filter', models.CharField(blank=True, default='*.csv', max_length=100, verbose_name='Filtro INPUT')),
                ('output_prefix', models.CharField(blank=True, default='hostq_', max_length=100, verbose_name='Prefijo OUTPUT')),
                ('dont_delete_input', models.BooleanField(default=True, verbose_name='No borrar INPUT')),
                ('poll_interval_sec', models.PositiveIntegerField(default=60, verbose_name='Intervalo de polling (seg)')),
                ('last_inputdate_seen', models.DateTimeField(blank=True, null=True, verbose_name='Último INPUTDATE observado')),
                ('last_output_scan', models.DateTimeField(blank=True, null=True, verbose_name='Último escaneo OUTPUT')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incca_configs_creadas', to='core.usuario', verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incca_configs', to='core.empresa', verbose_name='Empresa')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incca_config', to='mantenimiento.expedienteequipo', verbose_name='Equipo (Expediente)')),
            ],
            options={
                'verbose_name': 'Config InCCA (CSV)',
                'verbose_name_plural': 'Configs InCCA (CSV)',
            },
        ),
        migrations.CreateModel(
            name='InCCAFileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Input (LIS→InCCA)'), ('OUT', 'Output (InCCA→LIS)')], default='OUT', max_length=3)),
                ('filename', models.CharField(max_length=260, verbose_name='Archivo')),
                ('full_path', models.CharField(blank=True, default='', max_length=800, verbose_name='Ruta completa')),
                ('file_mtime', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DETECTADO', 'Detectado'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error'), ('IGNORADO', 'Ignorado')], default='DETECTADO', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('raw_preview', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_events', to='mantenimiento.inccainterfaceconfig', verbose_name='Config')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incca_file_events', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evento InCCA (archivo)',
                'verbose_name_plural': 'Eventos InCCA (archivos)',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='InCCAOutputRowStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('process_number', models.CharField(blank=True, default='', max_length=80)),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('method_name', models.CharField(blank=True, default='', max_length=200)),
                ('pid', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.TextField(blank=True, default='')),
                ('raw_fields_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incca_output_rows', to='core.empresa', verbose_name='Empresa')),
                ('file_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='mantenimiento.inccafileevent', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Fila InCCA (staging)',
                'verbose_name_plural': 'Filas InCCA (staging)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inccainterfaceconfig',
            index=models.Index(fields=['empresa', 'habilitado'], name='mantenimien_empresa_0f4cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='inccafileevent',
            index=models.Index(fields=['empresa', 'direction', 'status', '-detected_at'], name='mantenimien_empresa_7ef61a_idx'),
        ),
        migrations.AddIndex(
            model_name='inccafileevent',
            index=models.Index(fields=['config', 'direction', 'filename'], name='mantenimien_config__92b14e_idx'),
        ),
        migrations.AddConstraint(
            model_name='inccafileevent',
            constraint=models.UniqueConstraint(fields=('config', 'direction', 'filename', 'sha256'), name='mantenimiento_incca_fileevent_config_dir_file_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='inccaoutputrowstaging',
            index=models.Index(fields=['empresa', 'order_number', '-created_at'], name='mantenimien_empresa_4a55d0_idx'),
        ),
    ]
