# Generated by Django 5.0.6 on 2026-04-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_incca_csv_interface_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inccafileevent',
            new_name='mantenimien_empresa_978693_idx',
            old_name='mantenimien_empresa_7ef61a_idx',
        ),
        migrations.RenameIndex(
            model_name='inccafileevent',
            new_name='mantenimien_config__8bf502_idx',
            old_name='mantenimien_config__92b14e_idx',
        ),
        migrations.RenameIndex(
            model_name='inccainterfaceconfig',
            new_name='mantenimien_empresa_ab98b8_idx',
            old_name='mantenimien_empresa_0f4cf4_idx',
        ),
        migrations.RenameIndex(
            model_name='inccaoutputrowstaging',
            new_name='mantenimien_empresa_9452b8_idx',
            old_name='mantenimien_empresa_4a55d0_idx',
        ),
        migrations.AddField(
            model_name='salidarefaccionmantenimiento',
            name='costo_total_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total Congelado'),
        ),
        migrations.AddField(
            model_name='salidarefaccionmantenimiento',
            name='costo_unitario_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo Unitario Congelado'),
        ),
        migrations.AddField(
            model_name='salidarefaccionmantenimiento',
            name='stock_anterior_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Anterior Congelado'),
        ),
        migrations.AddField(
            model_name='salidarefaccionmantenimiento',
            name='stock_resultante_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Resultante Congelado'),
        ),
    ]
