# Generated by Django 5.0.6 on 2026-06-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_rename_mantenimien_empresa_7ef61a_idx_mantenimien_empresa_978693_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmantenimientocmms',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_cmms_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmantenimientocmms',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='mantenimiento.expedienteequipo'),
        ),
    ]
