# Generated by Django 4.2 on 2026-01-25 19:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscripcionVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Archivo de audio grabado', upload_to='transcripciones_voz/%Y/%m/%d/')),
                ('texto_transcrito', models.TextField(help_text='Texto transcrito del audio')),
                ('entidades_extraidas', models.JSONField(default=dict, help_text='Entidades clave extraídas del texto (ayuno, alergias, medicamentos, etc.)')),
                ('confianza_transcripcion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nivel de confianza de la transcripción (0-1)', max_digits=5)),
                ('duracion_audio', models.IntegerField(blank=True, help_text='Duración del audio en segundos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_asociada', models.ForeignKey(blank=True, help_text='Orden asociada a esta transcripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripcion_voz', to='laboratorio.orden')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripciones_voz_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcripción de Voz',
                'verbose_name_plural': 'Transcripciones de Voz',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_receta', models.ImageField(help_text='Imagen de la receta escaneada', upload_to='recetas_ocr/%Y/%m/%d/')),
                ('texto_extraido', models.TextField(help_text='Texto extraído por el OCR')),
                ('estudios_detectados', models.JSONField(default=list, help_text='Lista de estudios detectados con su nivel de confianza')),
                ('total_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total calculado automáticamente', max_digits=10)),
                ('confianza_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nivel de confianza promedio de la detección (0-1)', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_asociada', models.ForeignKey(blank=True, help_text='Orden creada a partir de esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_ocr', to='laboratorio.orden')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_ocr_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización OCR',
                'verbose_name_plural': 'Cotizaciones OCR',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
