# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionocr',
            name='imagen_receta',
            field=models.ImageField(help_text='Imagen de la receta escaneada', upload_to='recetas_ocr/%Y/%m/%d/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='transcripcionvoz',
            name='audio',
            field=models.FileField(help_text='Archivo de audio grabado', upload_to='transcripciones_voz/%Y/%m/%d/', validators=[core.validators.validate_audio_upload]),
        ),
    ]
