# Generated by Django 5.0.6 on 2026-04-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_consentimiento_marketing_y_orden_opcional'),
        ('ia', '0002_alter_cotizacionocr_imagen_receta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionocr',
            name='orden_asociada',
            field=models.ForeignKey(blank=True, help_text='Orden LIMS (core) creada a partir de esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_ocr', to='core.ordendeservicio'),
        ),
        migrations.AlterField(
            model_name='transcripcionvoz',
            name='orden_asociada',
            field=models.ForeignKey(blank=True, help_text='Orden LIMS (core) asociada a esta transcripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripcion_voz', to='core.ordendeservicio'),
        ),
    ]
