# Generated by Django 4.2 on 2026-01-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_director', models.CharField(blank=True, help_text='Teléfono del director para alertas de pánico (formato: +521234567890)', max_length=20, null=True)),
                ('telefono_seguridad', models.CharField(blank=True, help_text='Teléfono de seguridad privada para alertas de pánico', max_length=20, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Chat ID de Telegram para alertas', max_length=100, null=True)),
                ('boton_panico_activo', models.BooleanField(default=True, help_text='Activar/desactivar el botón de pánico')),
                ('atajo_teclado', models.CharField(default='Ctrl+Alt+P', help_text='Atajo de teclado para activar el botón de pánico', max_length=50)),
                ('metodo_notificacion', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('AMBOS', 'Ambos')], default='WHATSAPP', help_text='Método preferido para enviar alertas', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_seguridad', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='AlertaPanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se activó la alerta')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física donde se activó (IP, estación de trabajo, etc.)', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa Alarma')], default='PENDIENTE', help_text='Estado actual de la alerta', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la resolución de la alerta', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se resolvió la alerta', null=True)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('telegram_enviado', models.BooleanField(default=False)),
                ('mensajes_enviados', models.JSONField(default=list, help_text='Registro de mensajes enviados con timestamps')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_panico', to='core.empresa')),
                ('usuario', models.ForeignKey(help_text='Usuario que activó la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_panico_activadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_resolucion', models.ForeignKey(blank=True, help_text='Usuario que resolvió la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_panico_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Pánico',
                'verbose_name_plural': 'Alertas de Pánico',
                'ordering': ['-fecha_activacion'],
            },
        ),
    ]
