# Generated by Django 5.0.14 on 2026-01-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBackup2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de respaldo (formato: XXXX-XXXX-XXXX)', max_length=12, unique=True)),
                ('codigo_hash', models.CharField(help_text='Hash SHA256 del código para verificación segura', max_length=64)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_backup_2fa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código de Respaldo 2FA',
                'verbose_name_plural': 'Códigos de Respaldo 2FA',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número de teléfono en formato E.164 (ej: +5215512345678)', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('contador_usos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_sms', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo SMS (2FA)',
                'verbose_name_plural': 'Dispositivos SMS (2FA)',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del dispositivo (ej: iPhone 13, Google Authenticator)', max_length=100)),
                ('llave_secreta', models.CharField(help_text='Llave secreta TOTP (Base32)', max_length=32, unique=True)),
                ('activo', models.BooleanField(default=False, help_text='El dispositivo está activado y validado')),
                ('confirmado', models.BooleanField(default=False, help_text='El usuario confirmó el dispositivo ingresando un código válido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('contador_usos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_totp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo TOTP (2FA)',
                'verbose_name_plural': 'Dispositivos TOTP (2FA)',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogAccionSensible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FALLIDO', 'Intento Fallido de Login'), ('CAMBIO_PASSWORD', 'Cambio de Contraseña'), ('2FA_ACTIVADO', '2FA Activado'), ('2FA_DESACTIVADO', '2FA Desactivado'), ('VER_EXPEDIENTE', 'Ver Expediente Clínico'), ('EDITAR_EXPEDIENTE', 'Editar Expediente Clínico'), ('ELIMINAR_REGISTRO', 'Eliminar Registro'), ('EXPORTAR_DATOS', 'Exportar Datos'), ('CAMBIO_PERMISOS', 'Cambio de Permisos'), ('ACCESO_ADMIN', 'Acceso a Administración'), ('MODIFICAR_RESULTADO_LAB', 'Modificar Resultado de Laboratorio'), ('CANCELAR_FACTURA', 'Cancelar Factura')], help_text='Tipo de acción realizada', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('modelo_afectado', models.CharField(blank=True, help_text='Modelo de Django afectado (ej: Paciente, OrdenDeServicio)', max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación del objeto afectado', max_length=255)),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes de la modificación (JSON)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después de la modificación (JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('ruta_url', models.CharField(blank=True, help_text='Ruta URL de la acción', max_length=500)),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la acción')),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='INFO', help_text='Severidad de la acción', max_length=20)),
                ('exitosa', models.BooleanField(default=True, help_text='La acción fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la acción falló')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acciones_sensibles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Acción Sensible',
                'verbose_name_plural': 'Logs de Acciones Sensibles',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='seguridad_l_usuario_4fb3df_idx'), models.Index(fields=['accion', 'fecha_hora'], name='seguridad_l_accion_ca7a07_idx'), models.Index(fields=['severidad', 'fecha_hora'], name='seguridad_l_severid_0389a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Key de la sesión de Django', max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('dispositivo_tipo', models.CharField(blank=True, help_text='Tipo de dispositivo (Desktop, Mobile, Tablet)', max_length=50)),
                ('navegador', models.CharField(blank=True, help_text='Navegador utilizado', max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, help_text='Sistema operativo', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del cliente')),
                ('ubicacion_ciudad', models.CharField(blank=True, help_text='Ciudad (obtenida por GeoIP)', max_length=100)),
                ('ubicacion_pais', models.CharField(blank=True, help_text='País (obtenido por GeoIP)', max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True, help_text='La sesión está activa')),
                ('es_sospechosa', models.BooleanField(default=False, help_text='Marcada como sospechosa por el sistema')),
                ('razon_sospecha', models.TextField(blank=True, help_text='Razón por la que se marcó como sospechosa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_activas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión Activa',
                'verbose_name_plural': 'Sesiones Activas',
                'ordering': ['-fecha_ultima_actividad'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='seguridad_s_usuario_34dc5b_idx'), models.Index(fields=['session_key'], name='seguridad_s_session_4723af_idx')],
            },
        ),
    ]
