# Generated by Django 5.0.14 on 2026-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_codigobackup2fa_dispositivosms_dispositivototp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaccionsensible',
            name='ruta_url',
            field=models.CharField(blank=True, default='', help_text='Ruta URL de la acción', max_length=500),
        ),
        migrations.AlterField(
            model_name='logaccionsensible',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent del navegador'),
        ),
    ]
