# Generated by Django 5.1.15 on 2026-08-01 17:07

import core.fields
from django.db import migrations


def encrypt_existing_totp_secrets(apps, schema_editor):
    """Encrypt legacy plaintext TOTP secrets without double-encrypting them."""
    dispositivo_model = apps.get_model('seguridad', 'DispositivoTOTP')
    field = dispositivo_model._meta.get_field('llave_secreta')
    table = schema_editor.connection.ops.quote_name(dispositivo_model._meta.db_table)
    column = schema_editor.connection.ops.quote_name(field.column)
    with schema_editor.connection.cursor() as cursor:
        for pk, secret in dispositivo_model.objects.values_list('pk', 'llave_secreta').iterator():
            if not secret:
                continue
            encrypted = core.fields.EncryptedTextField.encrypt(str(secret))
            cursor.execute(
                f'UPDATE {table} SET {column} = %s WHERE id = %s',
                [encrypted, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_fix_user_agent_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivototp',
            name='llave_secreta',
            field=core.fields.EncryptedTextField(help_text='Llave secreta TOTP (Base32)', unique=True),
        ),
        migrations.RunPython(encrypt_existing_totp_secrets, migrations.RunPython.noop),
    ]
