# Generated by Django 5.1.15 on 2026-08-01 17:10

import core.fields
from django.db import migrations


def encrypt_existing_backup_codes(apps, schema_editor):
    model = apps.get_model('seguridad', 'CodigoBackup2FA')
    field = model._meta.get_field('codigo')
    table = schema_editor.connection.ops.quote_name(model._meta.db_table)
    column = schema_editor.connection.ops.quote_name(field.column)
    with schema_editor.connection.cursor() as cursor:
        for pk, code in model.objects.values_list('pk', 'codigo').iterator():
            if not code:
                continue
            encrypted = core.fields.EncryptedTextField.encrypt(str(code))
            cursor.execute(
                f'UPDATE {table} SET {column} = %s WHERE id = %s',
                [encrypted, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_dispositivototp_llave_secreta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigobackup2fa',
            name='codigo',
            field=core.fields.EncryptedTextField(help_text='Código de respaldo (formato: XXXX-XXXX-XXXX)', unique=True),
        ),
        migrations.RunPython(encrypt_existing_backup_codes, migrations.RunPython.noop),
    ]
