# Generated by Django 5.1.15 on 2026-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_alter_codigobackup2fa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigobackup2fa',
            name='codigo_hash',
            field=models.CharField(help_text='Hash adaptativo del código para verificación segura', max_length=128),
        ),
    ]
