# Generated by Django 4.2 on 2026-01-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultorio', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(blank=True, max_length=120, null=True)),
                ('chofer', models.CharField(max_length=255)),
                ('hora_salida', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_recoleccion', to='core.empresa')),
                ('sucursal_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_destino', to='core.sucursal')),
                ('sucursal_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_origen', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Ruta de Recolección',
                'verbose_name_plural': 'Rutas de Recolección',
                'ordering': ['-hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='VisitaDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('EN_RUTA', 'En ruta'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_domicilio', to='consultorio.agendacita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_domicilio', to='core.empresa')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_domicilio', to='core.ordendeservicio')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='logistica.rutarecoleccion')),
            ],
            options={
                'verbose_name': 'Visita a Domicilio',
                'verbose_name_plural': 'Visitas a Domicilio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
