# Generated by Django 5.0.14 on 2026-01-26 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudioimagen_plantillaestudioimagen_and_more'),
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('token_rastreo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDA', 'Recibida'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, help_text='Razón de la transferencia')),
                ('observaciones_origen', models.TextField(blank=True)),
                ('observaciones_destino', models.TextField(blank=True)),
                ('transportista', models.CharField(blank=True, max_length=255)),
                ('guia_transporte', models.CharField(blank=True, max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='core.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_creacion'],
                'permissions': [('autorizar_transferencia', 'Puede autorizar transferencias'), ('cancelar_transferencia', 'Puede cancelar transferencias')],
            },
        ),
        migrations.CreateModel(
            name='LogTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistica.transferenciainventario')),
            ],
            options={
                'verbose_name': 'Log de Transferencia',
                'verbose_name_plural': 'Logs de Transferencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('daños_reportados', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.transferenciainventario')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
                'ordering': ['orden', 'producto__nombre'],
            },
        ),
    ]
