# Generated by Django 5.0.6 on 2026-06-27 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0081_make_mensajeinterno_empresa_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Básico, Pro, Enterprise', max_length=50, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_usuarios', models.IntegerField(default=10, help_text='Límite de usuarios por cuenta')),
                ('incluye_iot', models.BooleanField(default=False, help_text='¿Permite Kioscos IoT?')),
                ('incluye_api', models.BooleanField(default=False, help_text='¿Acceso a API de integración?')),
            ],
            options={
                'verbose_name': 'Plan SaaS',
                'verbose_name_plural': 'Planes SaaS',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida (Bloqueada)'), ('CANCELADA', 'Cancelada'), ('TRIAL', 'Período de Prueba')], default='TRIAL', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_proximo_corte', models.DateTimeField(help_text='Fecha en que se cobrará o vencerá la suscripción')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='core.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suscripciones', to='suscripciones.plansaas')),
            ],
            options={
                'verbose_name': 'Suscripción de Tenant',
                'verbose_name_plural': 'Suscripciones de Tenants',
            },
        ),
    ]
