# Generated by Django 4.2 on 2026-01-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: MERMA_CAD, ROTURA, ROBO', max_length=20, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Ej: Merma por Caducidad Vencida', max_length=255, verbose_name='Descripción')),
                ('es_responsabilidad_empleado', models.BooleanField(default=False, help_text='Si es TRUE, puede generar descuento en nómina', verbose_name='Responsabilidad del Empleado')),
                ('requiere_evidencia_fotografica', models.BooleanField(default=False, verbose_name='Requiere Foto de Evidencia')),
                ('requiere_autorizacion_gerente', models.BooleanField(default=False, verbose_name='Requiere Autorización de Gerente')),
                ('activo', models.BooleanField(default=True, verbose_name='Motivo Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_ajuste_farmacia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Motivo de Ajuste',
                'verbose_name_plural': 'Motivos de Ajuste',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal del proveedor', max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes (12-13 caracteres)', max_length=13, unique=True, verbose_name='RFC')),
                ('categoria', models.CharField(choices=[('LABORATORIO', 'Laboratorio Farmacéutico'), ('DISTRIBUIDOR', 'Distribuidor / Mayorista'), ('IMPORTADOR', 'Importador'), ('OTRO', 'Otro')], default='DISTRIBUIDOR', max_length=20, verbose_name='Categoría de Proveedor')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('contacto_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Contacto')),
                ('dias_credito', models.IntegerField(default=0, help_text='0 = Contado, 30 = Crédito a 30 días', verbose_name='Días de Crédito')),
                ('descuento_volumen', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Descuento por Volumen')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor Activo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_farmacia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor Farmacéutico',
                'verbose_name_plural': 'Proveedores Farmacéuticos',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: KDX-2026-00001', max_length=50, unique=True, verbose_name='Folio Único del Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra a Proveedor'), ('ENTRADA_DEVOLUCION', 'Entrada por Devolución de Cliente'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste (Corrección Positiva)'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_MERMA', 'Salida por Merma/Caducidad'), ('SALIDA_ROBO', 'Salida por Robo/Faltante'), ('SALIDA_AJUSTE', 'Salida por Ajuste (Corrección Negativa)'), ('SALIDA_USO_INTERNO', 'Salida por Uso Interno/Laboratorio')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Siempre positivo. El tipo define si suma o resta.', max_digits=10, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=4, help_text='Para entradas: costo de compra. Para salidas: costo promedio actual.', max_digits=10, verbose_name='Costo Unitario en el Momento del Movimiento')),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='cantidad * costo_unitario', max_digits=12, verbose_name='Costo Total del Movimiento')),
                ('stock_anterior', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Stock Antes del Movimiento')),
                ('stock_resultante', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Stock Después del Movimiento')),
                ('costo_promedio_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Costo Promedio Anterior')),
                ('costo_promedio_nuevo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Costo Promedio Después del Movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Movimiento')),
                ('evidencia', models.ImageField(blank=True, help_text='Foto de producto roto, caducado, etc.', null=True, upload_to='kardex_evidencias/%Y/%m/', verbose_name='Evidencia Fotográfica')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('documento_referencia', models.CharField(blank=True, help_text='Ej: Factura, Remisión, Ticket de Venta', max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='core.ajusteinventario', verbose_name='Ajuste (para correcciones)')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('lote', models.ForeignKey(blank=True, help_text='CRÍTICO: El stock se mueve por lote, no por producto genérico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='core.lote', verbose_name='Lote Específico')),
                ('motivo_ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='farmacia.motivoajuste', verbose_name='Motivo del Ajuste')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='core.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='farmacia.proveedor', verbose_name='Proveedor (para compras)')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='core.venta', verbose_name='Venta (para salidas por venta)')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario (Kardex)',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
                'ordering': ['-fecha_movimiento'],
                'permissions': [('autorizar_movimientos', 'Puede autorizar movimientos de inventario')],
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['rfc'], name='farmacia_pr_rfc_b9e130_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'activo'], name='farmacia_pr_empresa_7d1979_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', '-fecha_movimiento'], name='farmacia_mo_product_059047_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['lote', '-fecha_movimiento'], name='farmacia_mo_lote_id_0f2f17_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['usuario_responsable', '-fecha_movimiento'], name='farmacia_mo_usuario_c81bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='farmacia_mo_tipo_mo_911d26_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['folio'], name='farmacia_mo_folio_7be9cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motivoajuste',
            unique_together={('empresa', 'codigo')},
        ),
    ]
