# Generated by Django 5.0.14 on 2026-02-10 09:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_voiceauditlog'),
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: APERT-2026-00001', max_length=50, unique=True, verbose_name='Folio de Apertura')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Apertura')),
                ('fondo_efectivo', models.DecimalField(decimal_places=2, help_text='Dinero en caja al abrir (para dar cambio)', max_digits=10, verbose_name='Fondo Inicial de Efectivo')),
                ('fondo_vales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Vales Disponibles (Opcional)')),
                ('activa', models.BooleanField(default=True, help_text='True mientras el turno está activo', verbose_name='Caja Abierta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones de Apertura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Abre (Nancy)')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CierreTurnoFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: CIERRE-2026-00001', max_length=50, unique=True, verbose_name='Folio de Cierre')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha/Hora de Apertura del Turno')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Cierre')),
                ('efectivo_declarado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo Declarado (Contado en Mano)')),
                ('tarjeta_declarado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tarjeta Declarado (Suma de Vouchers)')),
                ('vales_declarado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Vales Declarado (Vales Físicos Contados)')),
                ('efectivo_teorico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo Teórico (Por Ventas del Sistema)')),
                ('tarjeta_teorico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tarjeta Teórico (Por Ventas del Sistema)')),
                ('vales_teorico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Vales Teórico (Por Ventas del Sistema)')),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diferencia Efectivo (Declarado - Teórico)')),
                ('diferencia_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diferencia Tarjeta')),
                ('diferencia_vales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diferencia Vales')),
                ('diferencia_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diferencia Total (Faltante/Sobrante)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Cierre')),
                ('justificacion_diferencia', models.TextField(blank=True, help_text='Explicar faltantes o sobrantes', null=True, verbose_name='Justificación de Diferencias')),
                ('requiere_revision', models.BooleanField(default=False, help_text='Se activa automáticamente si diferencia > umbral', verbose_name='Requiere Revisión Gerencial')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado por Gerencia')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('apertura_caja', models.OneToOneField(blank=True, help_text='Vincula con la apertura para incluir fondo inicial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierre_asociado', to='farmacia.aperturacaja', verbose_name='Apertura de Caja Asociada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_farmacia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Cierra (Nancy)')),
            ],
            options={
                'verbose_name': 'Cierre de Turno Farmacia',
                'verbose_name_plural': 'Cierres de Turno Farmacia',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='cerrada_con',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apertura', to='farmacia.cierreturnofarmacia', verbose_name='Cerrada Con'),
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: DEV-2026-00001', max_length=50, unique=True, verbose_name='Folio de Devolución')),
                ('tipo', models.CharField(choices=[('TOTAL', 'Devolución Total'), ('PARCIAL', 'Devolución Parcial')], max_length=10, verbose_name='Tipo de Devolución')),
                ('motivo', models.CharField(choices=[('ERROR_VENTA', 'Error en la Venta'), ('PRODUCTO_DEFECTUOSO', 'Producto Defectuoso'), ('CLIENTE_INSATISFECHO', 'Cliente Insatisfecho'), ('PRODUCTO_EQUIVOCADO', 'Producto Equivocado'), ('OTRO', 'Otro (Especificar)')], max_length=30, verbose_name='Motivo de la Devolución')),
                ('motivo_detallado', models.TextField(blank=True, null=True, verbose_name='Motivo Detallado')),
                ('monto_devolucion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a Devolver')),
                ('reingresar_a_stock', models.BooleanField(default=True, help_text='Si=Vuelve al stock. No=Envía a Mermas', verbose_name='¿Reingresar Mercancía al Inventario?')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Devolución')),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='True si monto > umbral', verbose_name='Requiere Autorización Gerencial')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('evidencia_fotografica', models.ImageField(blank=True, null=True, upload_to='devoluciones/%Y/%m/', verbose_name='Evidencia Fotográfica')),
                ('procesada', models.BooleanField(default=False, help_text='True cuando se ejecutó reingreso/merma', verbose_name='Devolución Procesada')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_farmacia_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_procesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Procesa la Devolución')),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_farmacia', to='core.venta', verbose_name='Venta Original')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Venta',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='MermaFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: MERMA-2026-00001', max_length=50, unique=True, verbose_name='Folio de Merma')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad Dada de Baja')),
                ('motivo', models.CharField(choices=[('CADUCIDAD', 'Caducidad Vencida'), ('DAÑO', 'Daño Físico del Producto'), ('ROBO', 'Robo/Faltante'), ('USO_INTERNO', 'Uso Interno/Laboratorio'), ('OTRO', 'Otro (Especificar en Justificación)')], max_length=20, verbose_name='Motivo de la Merma')),
                ('justificacion_qc', models.TextField(help_text='Explicación detallada del motivo de la baja', verbose_name='Justificación QC')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('evidencia_fotografica', models.ImageField(blank=True, null=True, upload_to='mermas/%Y/%m/', verbose_name='Evidencia Fotográfica')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='core.lote', verbose_name='Lote Afectado')),
                ('movimiento_kardex', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merma', to='farmacia.movimientoinventario', verbose_name='Movimiento Kardex Generado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='core.producto', verbose_name='Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Reporta')),
            ],
            options={
                'verbose_name': 'Merma de Farmacia',
                'verbose_name_plural': 'Mermas de Farmacia',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAntibiotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Generado automáticamente. Ej: ATB-2026-00001', max_length=50, unique=True, verbose_name='Folio de Registro')),
                ('paciente_nombre', models.CharField(help_text='Si no hay paciente registrado, capturar nombre', max_length=255, verbose_name='Nombre del Paciente')),
                ('paciente_edad', models.IntegerField(blank=True, null=True, verbose_name='Edad del Paciente')),
                ('medico_cedula', models.CharField(help_text='OBLIGATORIO para antibióticos', max_length=50, verbose_name='Cédula Profesional del Médico')),
                ('medico_nombre', models.CharField(max_length=255, verbose_name='Nombre del Médico Prescriptor')),
                ('receta_folio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio de Receta Médica')),
                ('receta_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la Receta')),
                ('cantidad_vendida', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad Vendida')),
                ('fecha_venta', models.DateTimeField(verbose_name='Fecha/Hora de Venta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('lote_vendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_antibioticos', to='core.lote', verbose_name='Lote del Producto')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antibioticos_recibidos', to='core.paciente', verbose_name='Paciente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_antibioticos', to='core.producto', verbose_name='Antibiótico Vendido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antibioticos_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Vendió')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_antibioticos', to='core.venta', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Registro de Antibiótico (Libro COFEPRIS)',
                'verbose_name_plural': 'Registros de Antibióticos (Libro COFEPRIS)',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddIndex(
            model_name='cierreturnofarmacia',
            index=models.Index(fields=['sucursal', '-fecha_cierre'], name='farmacia_ci_sucursa_f6cb15_idx'),
        ),
        migrations.AddIndex(
            model_name='cierreturnofarmacia',
            index=models.Index(fields=['usuario_responsable', '-fecha_cierre'], name='farmacia_ci_usuario_b62c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cierreturnofarmacia',
            index=models.Index(fields=['folio'], name='farmacia_ci_folio_548481_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['sucursal', '-fecha_apertura'], name='farmacia_ap_sucursa_192722_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['usuario_responsable', '-fecha_apertura'], name='farmacia_ap_usuario_43f0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['activa', '-fecha_apertura'], name='farmacia_ap_activa_64a6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['venta_original', '-fecha_devolucion'], name='farmacia_de_venta_o_1d5665_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['sucursal', '-fecha_devolucion'], name='farmacia_de_sucursa_fa31cc_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['folio'], name='farmacia_de_folio_af001f_idx'),
        ),
        migrations.AddIndex(
            model_name='mermafarmacia',
            index=models.Index(fields=['producto', '-fecha_reporte'], name='farmacia_me_product_b956a2_idx'),
        ),
        migrations.AddIndex(
            model_name='mermafarmacia',
            index=models.Index(fields=['motivo', '-fecha_reporte'], name='farmacia_me_motivo_5e9f82_idx'),
        ),
        migrations.AddIndex(
            model_name='mermafarmacia',
            index=models.Index(fields=['folio'], name='farmacia_me_folio_290e84_idx'),
        ),
        migrations.AddIndex(
            model_name='registroantibiotico',
            index=models.Index(fields=['producto', '-fecha_venta'], name='farmacia_re_product_34e925_idx'),
        ),
        migrations.AddIndex(
            model_name='registroantibiotico',
            index=models.Index(fields=['medico_cedula', '-fecha_venta'], name='farmacia_re_medico__f8c5be_idx'),
        ),
        migrations.AddIndex(
            model_name='registroantibiotico',
            index=models.Index(fields=['sucursal', '-fecha_venta'], name='farmacia_re_sucursa_a62092_idx'),
        ),
        migrations.AddIndex(
            model_name='registroantibiotico',
            index=models.Index(fields=['folio'], name='farmacia_re_folio_c3c4bf_idx'),
        ),
    ]
