# Generated by Django 5.0.14 on 2026-02-21 19:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_aperturacaja_cierreturnofarmacia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionventa',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='Evidencia Fotográfica'),
        ),
        migrations.AlterField(
            model_name='mermafarmacia',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='mermas/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='Evidencia Fotográfica'),
        ),
        migrations.AlterField(
            model_name='mermafarmacia',
            name='motivo',
            field=models.CharField(choices=[('CADUCIDAD', 'Caducidad Vencida'), ('DAÑO', 'Daño Físico del Producto'), ('ROBO', 'Robo/Faltante'), ('USO_INTERNO', 'Uso Interno/Laboratorio'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('OTRO', 'Otro (Especificar en Justificación)')], max_length=20, verbose_name='Motivo de la Merma'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='evidencia',
            field=models.ImageField(blank=True, help_text='Foto de producto roto, caducado, etc.', null=True, upload_to='kardex_evidencias/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='Evidencia Fotográfica'),
        ),
    ]
