# Generated by Django 5.0.6 on 2026-03-31 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_historiaclinica_numero_expediente_and_more'),
        ('farmacia', '0003_alter_devolucionventa_evidencia_fotografica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proveedor',
            name='farmacia_pr_rfc_b9e130_idx',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(help_text='Registro Federal de Contribuyentes (12-13 caracteres)', max_length=13, verbose_name='RFC'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', '-fecha_movimiento'], name='farmacia_mo_empresa_17adda_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'tipo_movimiento', '-fecha_movimiento'], name='farmacia_mo_empresa_169ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['venta'], name='farmacia_mo_venta_i_d87bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'rfc'], name='farmacia_pr_empresa_372f28_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'rfc'), name='proveedor_empresa_rfc_unique'),
        ),
    ]
