# Generated by Django 5.0.6 on 2026-04-05 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_conveniopreciolims_and_legacy_lab_drop'),
        ('farmacia', '0004_remove_proveedor_farmacia_pr_rfc_b9e130_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cierreturnofarmacia',
            constraint=models.UniqueConstraint(condition=models.Q(('apertura_caja__isnull', False)), fields=('apertura_caja',), name='unique_cierre_por_apertura', violation_error_message='Ya existe un cierre para esta apertura de caja.'),
        ),
    ]
