# Generated by Django 5.1.15 on 2026-07-24 05:08

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_empresa_inventario_modo_adaptacion'),
        ('farmacia', '0005_cierreturnofarmacia_unique_cierre_por_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaRecetaFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recetas_farmacia/%Y/%m/%d/', validators=[core.validators.validate_image_upload])),
                ('texto_extraido', models.TextField(blank=True, default='')),
                ('datos_extraidos', models.JSONField(blank=True, default=dict)),
                ('sugerencias', models.JSONField(blank=True, default=list)),
                ('productos_confirmados', models.JSONField(blank=True, default=list)),
                ('confianza', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('PROCESADA', 'Procesada; requiere confirmación'), ('CONFIRMADA', 'Sugerencias confirmadas por usuario'), ('ERROR', 'Error de lectura')], db_index=True, default='PROCESADA', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_receta_farmacia_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_receta_farmacia', to='core.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_receta_farmacia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura OCR de receta de farmacia',
                'verbose_name_plural': 'Lecturas OCR de recetas de farmacia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
