# Generated by Django 5.1.15 on 2026-07-25 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_unique_active_apertura_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreturnofarmacia',
            name='diferencia_transferencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diferencia Transferencia'),
        ),
        migrations.AddField(
            model_name='cierreturnofarmacia',
            name='transferencia_declarado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Transferencia Declarado (SPEI)'),
        ),
        migrations.AddField(
            model_name='cierreturnofarmacia',
            name='transferencia_teorico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Transferencia Teórico (Por Ventas del Sistema)'),
        ),
    ]
