# Generated by Django 5.0.14 on 2026-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglas_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglanegocio',
            name='codigo',
            field=models.CharField(help_text='Ej: TRIPLE_LLAVE, CORTE_CIEGO, STOCK_MINIMO', max_length=100, unique=True, verbose_name='Codigo interno'),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, help_text='Parametros configurables: {"tolerancia": 0.50, "dias_vencimiento": 30}'),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='prioridad',
            field=models.IntegerField(default=10, help_text='Orden de evaluacion (menor = primero)'),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='tipo',
            field=models.CharField(choices=[('BLOQUEO', 'Bloquea accion si no se cumple'), ('ALERTA', 'Muestra alerta pero permite continuar'), ('AUTOMATICA', 'Se ejecuta automaticamente')], default='BLOQUEO', max_length=20),
        ),
    ]
