# Generated by Django 5.0.6 on 2026-04-07 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_pagoorden_empresa_tenant_guard'),
        ('reglas_negocio', '0002_alter_reglanegocio_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglanegocio',
            name='codigo',
            field=models.CharField(help_text='Ej: TRIPLE_LLAVE, CORTE_CIEGO, STOCK_MINIMO (único por empresa)', max_length=100, verbose_name='Codigo interno'),
        ),
        migrations.AddConstraint(
            model_name='reglanegocio',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='reglas_negocio_reglanegocio_empresa_codigo_uniq'),
        ),
    ]
